### ISSUE TITLE
Fragment queries with plugin-scope-auth and plugin-errors

### ISSUE THREAD

**Issue by platon-ivanov** [hayes/pothos#1002]
I have a project with the [Prisma Plugin](https://pothos-graphql.dev/docs/plugins/prisma), [Auth Plugin](https://pothos-graphql.dev/docs/plugins/scope-auth) and the [Errors Plugin](https://pothos-graphql.dev/docs/plugins/errors) set up. I'm trying to achieve the [recommended Errors Plugin usage](https://pothos-graphql.dev/docs/plugins/errors#recommended-usage) with using fragments in the queries. 

The builder has the following settings: 

```ts
export const builder = new SchemaBuilder({
  ...,
  plugins: [
    // no matter the order, the behavior is the same
    ErrorsPlugin,
    ScopeAuthPlugin,
    ...
    PrismaPlugin,
    PrismaUtils,
  ],
  scopeAuthOptions: {
    authorizeOnSubscribe: true,
    // treatErrorsAsUnauthorized and unauthorizedError aren't used as they don't result in the desired behavior
  },
  errorOptions: {
    defaultTypes: [UnauthorizedError],
  },
})
```

The fields are generated with [prisma-generator-pothos-codegen](https://github.com/Cauen/prisma-generator-pothos-codegen) with the following structure:

```ts
builder.prismaObjectField('User', 'username', (t) => t.field({
  ...
  authScopes: {
     admin: true
  },
  unauthorizedResolver: (q, r, i, c, e) =>
    throw new UnauthorizedError(e.message)
  },
  // adding "errors" field results in the field being split into fragments, which makes the queries too complex to write
})
```

Query fields have their own `authScopes` set up, as well as a list of available errors.

Running the following query:

```gql
query findUser {
  findFirstUser(where: {
    id: {
      equals: "21599895-8f9c-4537-abc2-0cac7ecec6c7"
    }
  }) {
    ... on QueryFindFirstUserSuccess {
      data {
        username
      }
    }

    ... on UnauthorizedError {
      message
    }
  }
}
```

Returns the following response:

```json
{
  "errors": [
    {
      "message": "Not authorized to resolve User.username",
      "path": [
        "findFirstUser",
        "data",
        "username"
      ],
      "extensions": {
        "code": "UNAUTHORIZED",
        "serviceName": "server"
      }
    }
  ],
  "data": {
    "findFirstUser": null
  }
}
```

This behavior is undesired since now `findFirst` returns `null` on an object which wasn't retrieved because of authorization issues, which are being caught.

Setting `nullable: false` on the query field only results in the response changing to:

```json
{
  "errors" [...],
  "data": null
}
```

The resolve-helper aggregates the issues into a single object:

https://github.com/hayes/pothos/blob/da2bc980dfb348830f8a46c0b05e30ec6b38be30/packages/plugin-scope-auth/src/resolve-helper.ts#L44

The failures can later be accessed as shown [in the documentation](https://pothos-graphql.dev/docs/plugins/scope-auth#surfacing-errors-thrown-in-authorization-checks). However, I wasn't able to throw the errors in a way which would let Errors Plugin handle them.

Is there a way in the current API to let the Errors plugin handle the Auth Plugin field issues?

**Comment by hayes** [comment]
I've created an example here, but I'm not sure if I am understanding your issue correctly:

https://stackblitz.com/edit/typescript-opc1zd?file=index.ts

Can't use the prisma plugin in browser, but hopefully this is good enough to either show how to handle the errors, or to better explain the desired behavior so I can update the example

**Comment by platon-ivanov** [comment]
Thank you for your swift response!

I have extended your example with the issue described more closely and comparison of three approaches to the issue:

https://stackblitz.com/edit/typescript-vxyqg3?file=index.ts

Thank you for the opportunity to work on the example! The code helped me understand the approaches better. 

The second approach "scopes on object with errors" is matching the requirements of validating every field individually, but as you can see, it results in larger queries. This can be easily overcome on the front-end with utilities generating the Error fragments on the fields. It would look prettier to if the "data" field for Objects was moved into the root of the success fragment, but that can't be done with primitive types, so it would introduce inconsistencies. I suppose some query building utilities would help with this too. 

Do you find this approach to be the optimal approach for setting up auth scopes for individual fields, or could there be some other approach I'm missing?

**Comment by hayes** [comment]
I think I understand your question better now, thanks for sharing that updated version!

To answer the simplest piece first, you can set `directResult: true` to avoid having the extra nested `data` field as long as it's returning and object, and not a list, scalar, or enum.


Unfortunately, its not possible to create your ideal version (currently).  Pothos is fundamentally just a schema builder that creates the schema types and resolvers, and is bound by how graphql js executes queries.

When you move the auth checks down to the User type, the checks won't be run until after the query field is fully resolved, and it's already been determined from graphqls perspective that you are returning a User and not an Error.

When the auth error is thrown, there isn't a way to go back and change what's being returned by the query resolver.  Unfortunately this means that the error plugin can currently only handle errors from its own resolver (or from things like auth, that Pothos adds into the resolver) but anything nested in a child resolver will happen too late for the error plugin to do anything.

**Comment by platon-ivanov** [comment]
Thank you for the wonderful answer! Now I better understand the workings of the system. I think that the way it currently works is great, and the somewhat longer syntax is something that can be easily dealt with but gives a lot of possibilities. 

The `directResult` option is exactly what was missing!

Looking further into auth-scopes, it seems that mutations can only be dealt with on the field itself. Plus, if the field scope checks run only after the query is resolved, it would throw only after the mutation for that field is complete, which is undesirable. 

So one option for per-field authorization is checking the scopes for each field inside the resolver before running any functions inside of the resolver. The functions would run on allowed fields only and on success return the values of the modified fields, and otherwise return ForbiddenError:

```ts
return {
  forbiddenField: new ForbiddenError(), 
  allowedField: "new value"
} 
```

However, for this approach to work, especially with [authscope functions to retrieve parent data](https://pothos-graphql.dev/docs/plugins/scope-auth#auth-that-depends-on-parent-value), it would be necessary to access the `authScopes` for an ObjectType inside of the resolver. 

Is there a way to achieve that, or should a different approach be taken with the current API?

**Comment by hayes** [comment]
Mutation fields are treated somewhat specially in GraphQL, and it is generally advised not to perform any mutations outside of the root mutation fields.  The only real difference form an implementation standpoint is that fields on the Mutation type are executed serially while fields on all other types are executed in parallel.

What I would recommend is that all mutations happen directly inside resolvers on the Mutation type, and anything nested is purely for querying the response of the mutation.   When you follow that pattern, you can put all your authorization checks for the mutation on the field itself, and then the auth checks on nested fields just for making sure the user is authorized to read that part of the response.   This makes it a lot easier to reuse types between queries and mutations, which can be important for efficient cache updates if you are using a client that has some sort of normalized cache
