### ISSUE TITLE
Update the package with out code generation.

### ISSUE THREAD

**Issue by RajaARK99** [hayes/pothos#1026]
Update the library like graph graphql [Graph graphql](https://github.com/stepci/garph) they generate typescript to inference like trpc.

**Comment by hayes** [comment]
This isn't something that Pothos will be able to support.  If I understand correctly, you want to be able to infer client types from the Pothos definitions.  Unfortunately this approach doesn't really scale.  Early versions of Pothos worked this way, but there are a number of important patterns in Pothos that don't work well with that style of API.

Specifically, Pothos definitions are modular, meaning that you can use methods like builder.queryField(s) and builder.objectField(s) that add fields in isolation.  We could potentially aggregate the return values of every builder method call into a combined schema, which could be used for inference, but even then, things like the errors plugin, the sub-graph plugin and the add-graphql plugin all cause the typescript types to substantially drift from the GraphQL schema definition. 

I think the approach that Garph takes is pretty cool for smaller projects, but scaling this up to giant APIs is hard.  The direction we went with Pothos optimizes for the backend developer experience, and makes building complex GraphQL schemas a great experience.  The trade off is that we aren't optimizing for the mono-repo full stack use case where you want to share frontend and backend types without any codegen step.

That being said, most graphql clients require codegen for their queries anyways (react, urql, apollo) so having to generate an intermediate schema.graphql as part of that process doesn't really have an effect on the developer experience

**Comment by RajaARK99** [comment]
@hayes Thanks for explaining this in detail. You put too much of an effect on this one greate.
