### ISSUE TITLE
Relay decoding returns weird value for GUID

### ISSUE THREAD

**Issue by jhalborg** [hayes/pothos#1029]
Hello 👋

I ran into a strange issue while trying to upgrade from `"@pothos/core": "3.27.1"` to the current version (`3.35.0`) and `"@pothos/plugin-relay": "3.37.0",` to `"@pothos/plugin-relay": "3.43.1"` 

When trying to decode a specific GUID, `a390e12f-fd71-46ed-9343-fc3b1f3d0a10`, the `decodeGlobalID` function from `@pothos/plugin-relay` returns `y߽ߍ�}�����ѭt` where I would instead have expected it to throw `PothosValidationError`

Reproduction here:

https://codesandbox.io/p/sandbox/small-browser-ljwfkm

**Comment by hayes** [comment]
thanks for reporting this... The change is the result of preferring `Buffer.from(id, 'base64')` over [atob(https://developer.mozilla.org/en-US/docs/Web/API/atob) which doesn't properly support unicode charaters.  Unfortunately they way base64 is not very strict, and won't error on invalid characters.  I think we could probably introduce a regex that validates that the provided ID is valid base64.  This isn't fully proof, but should catch some of the common cases

**Comment by jhalborg** [comment]
Not sure I follow. Would you add a regex test for the input ID [here](https://github.com/hayes/pothos/blob/6f2b643471b7960cd4c1bab88406b8cde60b73c5/packages/plugin-relay/src/utils/global-ids.ts#L8C19-L8C31) to make sure it's valid base64 before decoding?

How can `decodeGlobalID(valid-guid)` (such as the example, `a390e12f-fd71-46ed-9343-fc3b1f3d0a10`) ever result in `{"id": "y߽ߍ�}�����ѭt", "typename": "kt{]���{��"}` ?

**Comment by hayes** [comment]
You can run the following to reproduce the issue:

```ts
const [typename, id] =  Buffer.from('a390e12f-fd71-46ed-9343-fc3b1f3d0a10', 'base64').toString().split(':')
console.log({ typename, id })
```

Basically when node parses `a390e12f-fd71-46ed-9343-fc3b1f3d0a10` as base64 it decodes it as `k\x7Ft{]���{��:y߽ߍ�}�����ѭt`.  Pothos splits the decoded string on `:` which happens to be part of the decoded value, and then takes the first piece as the typename and the second piece as the id

**Comment by hayes** [comment]
The ID you provided isn't valid base64, but nodes parser is not strict, and tries to interpret the values anyway.  Adding a check using a regex like `/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/` would allow the parsing to error on more invalid IDs, although it still won't guarantee that the typename and ID are actually good values (thats pretty much impossible) 

We could also check to see the `typename` is part of the schema (accessible via the info object) but that may be a breaking change, and I can imagine use cases for resolving IDs that are not part of the current schema for people using stitching or federation.  Maybe just validating the typename is a valid GraphQL name (a letter followed by 0+ letters/numvers/underscores) would be more reasonable thing to add

**Comment by hayes** [comment]
Just pushed some changes that add a bit more validation around global IDs
