### ISSUE TITLE
Codegen with printSchema fails for ForbiddenError

### ISSUE THREAD

**Issue by trixobird** [hayes/pothos#1035]
Hello and thank you for all your hard work.

I was trying the error plugin along with the ScopeAuthPlugin and everything is working on the server side. I tried to execute the codegen and I am gettting 

```
PothosSchemaError: Received undefined as a type ref.

This is often caused by a circular import
If this ref is imported from a file that re-exports it (like index.ts)
you may be able to resolve this by importing it directly from the file that defines it.
```

If I replace `schema: printSchema(schema),` in codegen with `schema: 'http://localhost:4000/graphql', the codegen works.

I have a sample repo that the issue is reproducable: https://github.com/trixobird/typescript_playground/tree/pothos-codegen-auth-bug. Just execute the codegen script `pnpm codegen`

**Comment by hayes** [comment]
Thanks for the reproduction.  I was able to reproduce the issue, unfortunately I don't think this is something I'll be able to help fix.  This is a bug in graphql-code-generator (or more accurately, whatever they use to load typescript).  After some debugging, I found that their loader doesn't expose any named exports if you also have a default export.

You can run graphql-codegenerator manually with tsx
```bash
pnpm add -D tsx @graphql-codegen/core @graphql-codegen/schema-ast
```
then update `codegen.tsx`
```ts
import { printSchema, parse } from 'graphql';
import schema from './index.js';
import { codegen } from '@graphql-codegen/core'
import * as schemaAstPlugin from '@graphql-codegen/schema-ast'
import { writeFileSync } from 'node:fs';

const filename = './src/schema/generated/schema.graphql'
const result = await codegen({
  documents: [],
  schema: parse(printSchema(schema)),
  filename,
  plugins: [{
    'schema-ast': {}
  }],
  config: {
    scalars: {
      Date: 'Date',
      UUID: 'string',
    },
  },
  pluginMap: {
    'schema-ast': schemaAstPlugin
  }
})

writeFileSync(filename, result)
```
then run `pnpm tsx src/schema/codegen.ts`

But at that point, using `graphql-code-generator` is a bit over the top, and its better to just print the schema directly:
```ts
import { printSchema } from 'graphql';
import schema from './index.js';
import { writeFileSync } from 'node:fs';

const filename = './src/schema/generated/schema.graphql'

writeFileSync(filename, printSchema(schema))
```
