### ISSUE TITLE
Conditionaly set resolver return type

### ISSUE THREAD

**Issue by dylanlarrivee** [hayes/pothos#1055]
Hi,
I was wondering if it is possible to conditionally set the type that will be returned by a resolver based on a boolean arg variable. 

I am using the prisma integration and my situation is that I have an entity called alerts and they can either be active or inactive and this is based on a related table that stores alert status info connected by an alertStatusId (alert.alertStatus.name can be within an enum of values to be active else considered inactive). I was hoping to set up some type guard logic that will check when I pass an `isActive` boolean arg to the resolver which will update my prisma db filter logic to only include or exclude the the active options in the results and then would somehow let the resolver know what type would be returned.

I have been trying out a few things and seem to be running into an issue from my `alert.alertStatus.name` being a string (could update to a db enum if that helps) and finding a place to create a type based on the value. For example, if `alert.alertStatus.name` = `NEW` then it would be an active alert type, and for everything else it would be an inacttiveAlert type. Not sure if this is possible with the prisma plugin as it creates those types from the prisma.schema.

My current way to solve this is handling it on the frontend and manually casting a type based on if that arg gets passed in but I am worried that it isnt the safest method. 

**Resolver**
```
  getAlerts: t.prismaField({
    type: ['Alert'],
    authScopes: userAuthScope,
    nullable: true,
    args: {
      limit: t.arg.int(),
      skip: t.arg.int(),
      isActive: t.arg.boolean(),
      filter: t.arg({ type: GetAlertsFilter, required: true, defaultValue: {} }),
      orderBy: t.arg({
        type: AlertOrderBy,
        required: true,
        defaultValue: {
          startTime: 'desc',
        },
      }),
    },
    resolve: async (query, _root, args) => await getAlerts(query, args),
  }),
```

**Service**
```

export const updateFilterWithIsActiveWhereInput = (
  filter: Prisma.AlertWhereInput,
  isActive: boolean | undefined | null,
): Prisma.AlertWhereInput => {
  if (typeof isActive !== 'boolean') return filter;
  let updatedFilter = {};
  if ('alertStatus' in filter) {
    throw new Error("isActive and alertStatus filter options can't be used at the same time");
  } else if (isActive) {
    updatedFilter = {
      ...filter,
      alertStatus: {
        name: {
          in: Object.values(ActiveAlertStatusEnum),
        },
      },
    };
  } else {
    updatedFilter = {
      ...filter,
      alertStatus: {
        name: {
          in: Object.values(InactiveAlertStatusEnum),
        },
      },
    };
  }
  return updatedFilter;
};

export const getAlerts = async (
  query: AlertResolverQueryType,
  args: GetAlertsResultInputArgType,
): Promise<Alert[]> => {
  const { orderBy, isActive, filter, limit, skip } = args;

  const updatedFilter = updateFilterWithIsActiveWhereInput(filter, isActive);

  return db.alert.findMany({
    ...query,
    take: limit ?? DEFAULT_PAGE_SIZE,
    skip: skip ?? 0,
    orderBy: orderBy ?? undefined,
    where: updatedFilter,
  });
};

**Comment by hayes** [comment]
The type returned by a resolver can't really be changed based on arguments.  You can write a function yourself that has that constraint, but the resolver itself will only enforce constraints based in the the `type` provided for the field.   I would consider making this 2 separate queries, since the arguments and return values are split into 2 different flows.

**Comment by dylanlarrivee** [comment]
Ok yea that makes sense, thanks, I will go with the 2 separate queries approach. 

I think I will still end up with an issue trying to get my needed types from my prisma db table field. Is there a way to overwrite a field created with the `prismaObject` command if I wanted to take a this existing Alert object and created a new Active alert that I know will only have an `alertStatus` field like {name: ActiveAlertStatusNameEnum} (I will be using that enum in the prisma filter logic so I know the results will only contain those names.)? 

From what I have tried I will need to update a bunch of my objects to be non prisma objects because of the `t.relation` helper being used.

```
builder.prismaObject('Alert', {
  fields: (t) => ({
    alertId: t.exposeID('alertId'),
    smartMonitorId: t.exposeID('smartMonitorId'),
    runTime: t.expose('runTime', { type: 'DateTime' }),
    executionStatus: t.exposeString('executionStatus'),
    startTime: t.expose('startTime', { type: 'DateTime' }),
    endTime: t.expose('endTime', { type: 'DateTime' }),
    alertClosed: t.expose('alertClosed', { type: 'DateTime' }),
    pausedTime: t.expose('pausedTime', { type: 'DateTime' }),
    ownerId: t.exposeID('ownerId'),
    alertStatusId: t.exposeID('alertStatusId'),
    smartMonitor: t.relation('smartMonitor'),
    alertDetails: t.relation('alertDetails'),
    alertStatus: t.relation('alertStatus'),
    severity: t.relation('severity'),
    owner: t.relation('owner'),
  }),
});
```

**Comment by hayes** [comment]
```ts
const ActiveAlertStatus = builder.prismaObject('AlertStus', {
  variant: 'ActiveAlertStatus',
  fields: (t) => ({
    name: t.field({
      type: ActiveAlertStatusEnum,
      resolve: (status) => status.name as X // probably need to type cast here
  })
})

const ActiveAlert = builder.prismaObject('Alert', {
  variant: 'ActiveAlert',
  fields: (t) => ({
    ...
    alertStatus: t.relation('alertStatus', {
      type: ActiveAlertStatus,
    }),
    ...
});
```

**Comment by dylanlarrivee** [comment]
Whoa that's super cool. Not sure how I missed that in the docs. Thanks for sending over this example, I will play around with it today.
