### ISSUE TITLE
Integrating Apollo cacheControl feature not working

### ISSUE THREAD

**Issue by thomaswr** [hayes/pothos#1059]
I'm trying to get Apollo server 4's server side caching feature via `cachecontrol` headers to work, as described on https://www.apollographql.com/docs/apollo-server/performance/caching/#in-your-resolvers-dynamic but Pothos seems to interfere.

```typescript
interface SchemaTypes {
  Context: GQLContext;
  DefaultFieldNullability: true;
  SubGraphs: 'subgraph1' | 'subgraph2';
}

export const builder = new SchemaBuilder<SchemaTypes>({
  defaultFieldNullability: true,
  plugins: ['subgraph1', 'subgraph2'],
  subGraphs: {
    defaultForTypes: [],
    fieldsInheritFromTypes: true,
  },
});

builder.queryType({ subGraphs: ['subgraph1', 'subgraph2'] });
```

```typescript
import { cacheControlFromInfo } from '@apollo/cache-control-types';

builder.queryField('someField', (t) => {
  return t.field({
    subGraphs: ['subgraph1'],
    type: MyResponse,
    args: {
      id: t.arg({
        type: 'ID',
      }),
    },
    resolve: (parent, { id }, context, info) => {

        //  does not work
        // @ts-expect-error
      	info.cacheControl.setCacheHint({ maxAge: 123 });

        // does not work either
        cacheControlFromInfo(info).setCacheHint({ maxAge: 123 });

        return value;
    },
  });
});
```

If I remove pothos as the schema generator it works.
https://github.com/hayes/pothos/issues/782 didn't solve it for me.

Could this be an issue?

**Comment by hayes** [comment]
Tried to reproduce the issue, but this seems to be working as expected for me: https://github.com/hayes/apollo-cache-debug

**Comment by thomaswr** [comment]
The problem occured when queries returned more than one level of object types.
So Apollo wants me to set the cacheControl directive with the `inheritMaxAge` on child types.
(See: https://www.apollographql.com/docs/apollo-server/performance/caching/#recommended-starting-usage)

Solved that with the directives plugin:

```typescript
  Directives: {
    cacheControl: {
      locations: 'FIELD_DEFINITION' | 'OBJECT' | 'INTERFACE' | 'UNION';
      args: { inheritMaxAge?: boolean; maxAge?: number; scope?: CacheScope };
    };
  };
```
