### ISSUE TITLE
Prisma connection resolves incorrectly for fragment with abstract type

### ISSUE THREAD

**Issue by julioxavierr** [hayes/pothos#1060]
**Use case:** A connection is queried differently at the same time, using the field directly in the type and using a fragment that has a union (does not happen if the fragment does not use a union). 
**Problem:** The `totalCount` is resolved correctly, but the `edges` are always empty.

```graphql
query AppQuery {
  user {
    files {
      totalCount
    }
    ...App_node
  }
}

fragment App_node on Node {
  ... on User {
    id
    files {
      edges {
        node {
          name
          size
        }
      }
    }
  }
}
```

---

Related to #989 
Related to https://github.com/hayes/pothos/issues/989#issuecomment-1745559121

**Comment by hayes** [comment]
I think this should be fixed now, let me know if you still have any issues after updating

**Comment by julioxavierr** [comment]
@hayes I confirm that fixes the issue, thank you
