### ISSUE TITLE
Mutations to create related records 

### ISSUE THREAD

**Issue by Aladdin4u** [hayes/pothos#1068]
I'm trying to create a two related records at the same time.
Example: user related to a post.
```
await prisma.user.create({
  data: {
    email: 'email',
    name: 'joe',
    posts: {
      create: [
      { tittle: "how make it work"},
      { title: "can it work" },
      ],
    },
  },
})
```
Any way around pothos prisma

**Comment by hayes** [comment]
This is definitely possible in a number of different ways.  Can you share more details about your set up, and what piece of this is causing you issues?

**Comment by Aladdin4u** [comment]
I'm trying to add "bodymaps" to the create "Report" but can't figure it out. 
on the left image below is the Mutation on the right is prisma schema
![pothos](https://github.com/hayes/pothos/assets/101972392/a773a9f3-697f-45d1-aa14-e0ad3f04dae0)

**Comment by hayes** [comment]
on mobile, so this probably will be slightly wrong but:

```ts
const BodyMapInput = builder.inpitType('BodyMapInput', {
  fields: t => ({
    label: t.string(),
  }),
})

...

args: {
  ...
  bodyMaps: t.arg({
    type: [BodyMapInput]
  })
}

```

**Comment by Aladdin4u** [comment]
I got this error 
![pothos2](https://github.com/hayes/pothos/assets/101972392/24f301a4-f7c3-409d-a968-e8412dcb5770)

**Comment by hayes** [comment]
Seeing the actual error message would help, but you likely need to make the fids on your I put type (label and details) required

**Comment by Aladdin4u** [comment]
the error is still there: 
VScode hint: The expected type comes from property 'bodymaps' which is declared here on type '(Without<ReportCreateInput, ReportUncheckedCreateInput> & ReportUncheckedCreateInput) | (Without<...> & ReportCreateInput)'

**Comment by hayes** [comment]
Oh, you probably want to do `bodyMaps: { create: args.bodymaps }`

**Comment by Aladdin4u** [comment]
the create funcrion is underlined, having an error
VScode hint: Type 'InputShapeFromFields<{ label: InputFieldRef<string, "InputObject">; details: InputFieldRef<string, "InputObject">; }>[] | null | undefined' is not assignable to type '(Without<BodyMapCreateWithoutReportInput, BodyMapUncheckedCreateWithoutReportInput> & BodyMapUncheckedCreateWithoutReportInput) | (Without<...> & BodyMapCreateWithoutReportInput) | BodyMapCreateWithoutReportInput[] | BodyMapUncheckedCreateWithoutReportInput[] | undefined'.

**Comment by hayes** [comment]
Making the bodymaps arg required would work, or you can do `args.bodymaps ?? [] `

**Comment by Aladdin4u** [comment]
the error is still there

**Comment by Aladdin4u** [comment]
The error is gone. I had to close vs code and open it again.

**Comment by Aladdin4u** [comment]
the code for reference
![pothosdone](https://github.com/hayes/pothos/assets/101972392/c7ebb73a-c818-4114-81b1-371dba4c0a43)
