### ISSUE TITLE
Scalar type / authScopes on input type

### ISSUE THREAD

**Issue by armstrong-pv** [hayes/pothos#1073]
Hi, I'm declaring this input type.
````
export const UpdateUserRequest = builder.inputType('UpdateUserRequest', {
  fields: (t) => ({
    id: t.string({ required: true, validate: {
      schema: z.string().length(21)
    }}),
    disabledAt: t.field({ type: 'Date', required: false, authScopes: {} }),
  })
})
````
![image](https://github.com/hayes/pothos/assets/101402737/52648707-3bff-40c4-be6e-b94ca436ef12)

It uses the `Date` scalar, I've set up. But `authScopes` doesn't seem to be available from `field()`. Is there a way to set `authScopes` on a scalar field like this?

**Comment by hayes** [comment]
authScopes don't really make sense on an inputType, what is the action you are trying to authorize by adding scopes to the input?

**Comment by armstrong-pv** [comment]
For the example above, I want to make sure that the caller can only disable the user if they have the correct permission. The field is optional, so if the caller carries out an update without disabledAt, the operation would be allowed. Is there a better pattern for this?

**Comment by JipSterk** [comment]
instead of putting the authorization on the field directly can't you add the check the `authScopes` on the `mutation` directly? examples of this are located [here](https://pothos-graphql.dev/docs/plugins/scope-auth#auth-that-depends-on-parent-value) you would adjust this of course to the logic you would want so the mutation could look something like this:

```ts
builder. mutationField('updateUser', t => 
  t.field({
    type: User,
    args: {
      input: t.arg({ type: UpdateUserRequest })
    },
    authScopes: (_root, { input }, { user }) => {
      if (input.disableAt) {
        // either
        return user.permissions.include('some role") // or other authorization checks
        // or
        // return {
        //  isAdmin: true, // or other authorization checks
        // }
      }
    }
    resolve: (_root, { input }) => {
    // implement logic
    }
  })
);
```
