### ISSUE TITLE
`addScalarType` last argument (options) should default to an empty object

### ISSUE THREAD

**Issue by GauBen** [hayes/pothos#1081]
Hey, here is a small quality of life suggestion:

```ts
// Current implementation
builder.addScalarType('JSON', JSONResolver, {});
// Suggested implementation
builder.addScalarType('JSON', JSONResolver);
```

If this change is accepted I'm willing to open a pull request

**Comment by hayes** [comment]
Thanks for the suggestion.  We can definitely do this, but it's a little more complicated.  Pothos allows plugins to add required options, which needs to be accounted for.  You can look at the t.expose method for an example of how this is handled in other places

**Comment by GauBen** [comment]
Thanks for the heads up, I was hopping it was an easy fix but I. I'll take a closer look

**Comment by GauBen** [comment]
Thanks @s1owjke and @hayes!
