### ISSUE TITLE
Mutations execute serially; any means of executing in parallel?

### ISSUE THREAD

**Issue by michaelbridge** [hayes/pothos#1096]
Let's say my mutations need to hit a third-party service in the resolver, and I'd like to handle several mutation fields with a single request by batching together the mutations.  It seems per the GraphQL spec (or at least Pothos itself) that mutations are executed serially, while queries are executed in parallel.

I've attempted to write a plugin using `wrapResolve` that collects the various mutations. Each resolver would await a promise until the final resolver, at which point all of the fields can be batched into a single request and returned to the awaiting promises.  

Unfortunately, the await in the first resolver hangs infinitely. Is there any possible way around this behavior, patch or otherwise?

Thanks very much for any suggestions!

**Comment by hayes** [comment]
I think this would probably need to be handled by the execution layer (eg, an envelop plugin) pothos doesn't directly control execution, so this would be challenging to do in pothos itself

**Comment by hayes** [comment]
You could use the setExecute function of the onExecute hook here: https://the-guild.dev/graphql/envelop/docs/plugins/lifecycle#onexecuteapi to provide an execute function that handles executing in parallel.  Hope that helps
