### ISSUE TITLE
Invalid global ID: null when using optional arg.globalIdList

### ISSUE THREAD

**Issue by MarceloPrado** [hayes/pothos#1105]
Hi @hayes!
I'm trying to use the global ID list in my arguments with nullable items:

```
    categoryIds: arg.globalIDList({
      description:
        "A list of category IDs to filter transactions by. If provided, only transactions assigned to one of these categories will be returned.",
      for: CategoryNode,
      required: {
        items: false,
        list: false,
      },
    }),
```

The use-case here is that I also want to find transactions that have `categoryId: null`. When pothos intercepts my query, it throws a `Invalid global ID: null` error - defined [here](https://github.com/hayes/pothos/blob/main/packages/plugin-relay/src/utils/global-ids.ts#L12).

I think we need a check before decoding the base 64 to ensure the encoded value is defined. If it isn't and the list accepts nullable items, we should return null instead.

What do you think?

**Comment by hayes** [comment]
fixed here: https://github.com/hayes/pothos/commit/0f5cfa95036c3f5727a72885bd11cf35d48b8728

thanks for the report!
