### ISSUE TITLE
Pothos Prisma & Dataloaders

### ISSUE THREAD

**Issue by tylerjbainbridge** [hayes/pothos#1110]
Has anyone been able to integrate `prismaObject`s with Dataloaders? Would love some snippets/guidance here. Hoping to speed my site up.

**Comment by tylerjbainbridge** [comment]
Wow, thank you for such an in depth response! Really appreciate it.

I think I understand this better now. So, it's already optimized via spreading the `query` argument in the resolve function into the prisma call? Or is this something that happens behind the scenes with Prisma?

**Comment by hayes** [comment]
Yup, mostly through spreading the query argument, there are some additional optimizations internally for fallback cases when you don't spread the query argument correctly, or not everything can be loaded in the initial query, but for most queries, it's just that the query argument will include all the includes/selects needed to resolve the query

**Comment by tylerjbainbridge** [comment]
I'm a little confused on how `queryFromInfo` works, it seems just as slow as not using it at all on some of my fiends. However, I'm not using the `path` argument, is that why? I'm a big confused on what path should be.

Basically I have what amounts to a relation field but I want it to resolve as a Boolean (i.e. isLiked or isReposted) but this is causing huge performance hits despite using `queryFromInfo`

``` js
amIFollowing: t.field({
  type: 'Boolean',
  resolve: async (parent, args, context, info) => {
    const user = context.sessionUserMaybeNull;

    if (!user) {
      return false;
    }

    const exists = await prisma.userFollow.findFirst({
      ...queryFromInfo({
        context,
        info,
        path: ['']
      }),
      where: {
        originUser: {
          id: user.id,
        },
        targetUser: {
          id: parent.id,
        },
      },
    });

    return !!exists;
  },
}),
```

Any advice on how to speed this up?

**Comment by hayes** [comment]
`queryFromInfo` does what I was talking about before, it find create the appropriate select/includes based on what nested fields are selected by the current query.   In this case your field is a Boolean, so there is nothing nested to select, and nothing to optimize in that direction.  What it looks like you want to do here is not optimize a new query, but rather you want to include the selections for the amFollowing field in a parent query.  Pothos doesn't magically intercept calls to prisma, so any time you use prisma directly, it will be a new separate, query, and the most we can optimize is pre-selecting the data to resolve child fields.

What you can do here instead is something like:


```ts
builder.prismaObject('User', {
  fields: (t) => ({
    amIFollowing: t.field({
      type: 'Boolean',
      select: (args, ctx) => (ctx.sessionUserMaybeNull ? {
        followers: {
          limit: 1,
          where: {
            originUser: {
               id: ctx.sessionUserMaybeNull.id,
            }
          },
        },
      } : {}),
      resolve: async (parent, args, context, info) => {
        return parent.followers?.length === 1
      }
    }),
  },
})
```

**Comment by hayes** [comment]
This syntax and query may not be exactly right depending on your schema, but when you define a `select` like that, Pothos will ensure that the `parent` object passed to the resolver has that data selected.   If you query for both the amFollowing field, and a `followers` field, pothos may need to fall back and issue 2 queries, one for just the current user follower, and one for the full list since prisma doesn't allow selecting the same relation with different filters, but so long as only 1 is queried for, pothos will merge it into one query.  Either way it will work, but it will be better optimized if only one is selected, but Pothos will still ensure that your are getting the right data (as long as you properly spread the query)

**Comment by tylerjbainbridge** [comment]
Got it, definitely starting to understand how Pothos & Prisma actually work together here. Just fixed a bunch of problematic boolean fields by adding a select & the site is noticeably faster. Thank you again for taking the time to answer my Qs. 

Pothos rules.
