### ISSUE TITLE
plugin-scope-auth compilation error extending PothosValidationError

### ISSUE THREAD

**Issue by bmayen** [hayes/pothos#1112]
Using latest version, I'm getting the following error attempting to compile a project with ScopeAuth enabled.

```
/node_modules/@pothos/plugin-scope-auth/src/errors.ts:6
export class ForbiddenError extends PothosValidationError {
                                    ^
TypeError: Class extends value undefined is not a constructor or null
```

Inspecting the source I see the following error in my IDE:
`Module '@pothos/core' has no exported member PothosValidationError` on this line of errors.ts:
`import { PothosValidationError } from '@pothos/core';` 

I can see that exists though under my node_modules, so I'm not quite sure what the issue is here.

**Comment by hayes** [comment]
can you check to make sure that `@pothos/plugin-scope-auth` doesn't have its own nested copy of `@pothos/core` and that `@pothos/core` is also using the latest version?

**Comment by bmayen** [comment]
@hayes, thank you for the quick response. What's happening here is I'm using prisma-generator-pothos-codegen which has a peerDep on pothos/core 3.23.0. It looks like the Pothos plugins use `*` for the pothos/core peerDep range, so we're getting multiple versions installed. I'm able to work around this for now by downgrading the auth plugin to `3.17.0` and using NPM `overrides` to pin pothos/core to `3.23.0` for the plugins.

I was speaking with @Cauen over at https://github.com/Cauen/prisma-generator-pothos-codegen/issues/57#issuecomment-1863541371 yesterday about this peerDep range. This will be the best long-term solution. But for now I'm unblocked using NPM overrides.

**Comment by Cauen** [comment]
Hi @bmayen 
You can upgrade @pothos/core now :)

**Comment by bmayen** [comment]
Thank you!
