### ISSUE TITLE
Update Apollo Federation version to v2.6

### ISSUE THREAD

**Issue by TimboTambo** [hayes/pothos#1114]
The federation plugin currently references v2.3.

The latest version is [v2.6 and includes 3 new directives](https://www.apollographql.com/docs/federation/federated-types/federated-directives):
- `@authenticated`
- `@policy`
- `@requiresScopes`

The referenced version in the federation plugin should be updated and the new scopes included in the referenced list.

**Comment by TimboTambo** [comment]
Created a PR to address this: [https://github.com/hayes/pothos/pull/1115](https://github.com/hayes/pothos/pull/1115)

**Comment by hayes** [comment]
Thanks for the PR!  I think we'll need to add support for actually implementing those new directives as well before I can merge this, I can try to find some time to look into that in the next few days.   A lot of the existing directives are just added as options of fields or types which is almost trivial, but I haven't had a chance to look into these specific directives yet to know of there is anything more complex
