### ISSUE TITLE
Prisma Plugin not passing full include to query in resolvers

### ISSUE THREAD

**Issue by Arthur-Gab** [hayes/pothos#1124]
I am creating a Cart model and a CartItem in the prism, with a relationship of 1...N (Cart 1...N ------ CartItem 1...1).
When creating the prismaObject, I added ```include: {items: true, _count: true}``` to use the query in the resolvers. However, the query is not receiving ```_count: true```

I uploaded a repository where I placed the code containing this error, <strong>the tag with the error is "pothos-primsa_bug_include_not_passign_props_to_query"</strong>.

<a href="https://github.com/Arthur-Gab/One-Week-GraphQL">GitHub repository with the error</a>

**Comment by hayes** [comment]
You need to always spread the `query` argument when using `t.prismaField`:
<img width="616" alt="Screenshot 2024-02-13 at 7 53 57 PM" src="https://github.com/hayes/pothos/assets/816527/64cd2e39-4212-4753-834d-a0e37a29836a">
