### ISSUE TITLE
[plugin-prisma] `select` not present in `query`

### ISSUE THREAD

**Issue by MRVDH** [hayes/pothos#1131]
According to [the documentation](https://pothos-graphql.dev/docs/plugins/prisma#example):

> the `query` argument will add in `include`s or `select`s to resolve as much of the request in a single query as possible.

However, we notice that this is not happening in our case. In the example below we query only the field `hash`, but we notice that when adding a breakpoint and inspecting the `query` object, that there is no `select` inside, so it still queries all the fields. Is this a configuration issue?

I've included short examples of our setup. If you wan to peek at the full one, the repository is open source:

* [Yoga Server](https://github.com/kadena-community/kadena.js/blob/main/packages/apps/graph/src/index.ts)
* [SchemaBuilder](https://github.com/kadena-community/kadena.js/blob/main/packages/apps/graph/src/graph/builder.ts)
* [Block query](https://github.com/kadena-community/kadena.js/blob/main/packages/apps/graph/src/graph/objects/block.ts)

```gql
query {
  block(hash: "~snip~") {    
    hash
  }
}
```

```ts
builder.queryField('block', (t) =>
  t.prismaField({
    args: {
      hash: t.arg.string({ required: true }),
    },
    type: Block,
    nullable: true,
    async resolve(query, __parent, args) {
      return await prismaClient.block.findUnique({
        ...query,
        where: {
          hash: args.hash,
        },
      });
    },
  }),
);
```

**Comment by hayes** [comment]
This depends on how Block is defined.   The default behavior is to select all columns, and oy include the queried relations.  You need to define a `select` option on the Block type if you don't want to select all columns

**Comment by MRVDH** [comment]
So, I've found a way to do this, but it's probably error prone, and you have to ditch type safety mostly (also ts-ignoring the resolve since it only returns a partial Block).

```
builder.queryField('block', (t) =>
  t.prismaField({
    args: {
      hash: t.arg.string({ required: true }),
    },
    type: Block,
    nullable: true,
    // @ts-ignore
    async resolve(query, __parent, args, context, info) {
      try {
        const fieldNodes = info.fieldNodes;
        let select;

        if (fieldNodes.length) {
          const selectionSet = fieldNodes[0].selectionSet;
          select = selectionSet?.selections.reduce(
            (acc: any, selection: any) => {
              acc[selection.name.value as string] = true;
              return acc;
            },
            {},
          );
        }

        const block = await prismaClient.block.findUnique({
          ...query,
          where: {
            hash: args.hash,
          },
          select,
        });

        return block;
      } catch (error) {
        throw normalizeError(error);
      }
    },
  }),
);
```

**Comment by hayes** [comment]
That will probably cause a lot of other issues.   Just add select: {} to your Block type definition and everything should work the way you want

**Comment by MRVDH** [comment]
That worked!

Some findings:

* In `prismaNode` Block I do `select: {}`, then for every field in Block that calls `parent.<some_field>` I have to do a `select: { <some_field>: true }`, otherwise it will throw Typescript errors, thinking the field does not exist. This is by design I assume?
* One of my fields in `prismaNode` Block is a reference to a different Block, thus ebing the same type. I noticed that here Prisma still queries all fields, even if only one if requested form the GraphQL query.
* To continue on the first point, if a `prismaConnection` field inside `prismaNode` Block references `parent.<some_field>`, then adding `select: { <some_field>: true }` does not work, it will still throw type errors, unlike the other types of fields. So here I have to do a `ts-ignore` or cast parent to type Prisma Block.

**Comment by hayes** [comment]
> * In `prismaNode` Block I do `select: {}`, then for every field in Block that calls `parent.<some_field>` I have to add a `select: { <some_field>: true }` on that specific field, otherwise it will throw Typescript errors, thinking the field does not exist on the parent. This is by design I assume?

Yes this is by design, the select on the type determines what is selected by default, and therefore what is available on the parent object.   t.expose, t.relation, and t.relatedConnection add their required selections automatically.  Anything else we don't know what columns you might depend on so you need to select them yourself.

> * One of my fields in `prismaNode` Block is a reference to a different Block, thus being of the same type. I noticed that here Prisma still queries all fields, even if only one field is requested form the GraphQL query.

I don't know what this means


> * To continue on the first point, if a `prismaConnection` field inside `prismaNode` Block references `parent.<some_field>`, then adding `select: { <some_field>: true }` on that specific field does not work, it will still throw type errors, unlike the other types of prisma functions (like prismaNode, where it does work). So here I have to do a `ts-ignore` or cast parent to type Prisma Block.

This may be a bug, and is something I usually don't need.  I'll look into it but in the meantime time, usually relatedConnection is better if it can work, if not, looking at the docs for indirect connections may help.   The other thing you can do is just add the selection to the who type, usually things like the primary key are selected anyway so adding that to the base selection for the type doesn't add any overhead.



> * This is not configurable for the `node` and `nodes` queries (as far as I could find), there it will still select all fields.

This should work fine for the node/nodes queries, do you have an example of this not working?  If you are talking about other fields defined with t.node that probably depends on how you are defining the fields

**Comment by hayes** [comment]
Your not using the `query` arg in your prisma call.  If you don't spread that into prisma query the query obviously won't have the right selections
