### ISSUE TITLE
DirectivePlugin "No plugin named directives was registered"

### ISSUE THREAD

**Issue by tylerjbainbridge** [hayes/pothos#1137]
Including the DirectivePluginin the plugins array results in this error.

```js
import DirectivePlugin from '@pothos/plugin-directives';
...
plugins: [PrismaPlugin, ScopeAuthPlugin, RelayPlugin, DirectivePlugin],
```

**Comment by hayes** [comment]
I would start by checking to see if if @pothos/plugin-directives has a separate copy of @pothos/core nested inside it's node_modules directory.  This could happen if you have multiple copies of @pothos/core

**Comment by hayes** [comment]
Hope this got resolved, going to close this out since there isn't enough info to go off of
