### ISSUE TITLE
Creating relay mutations with no input fields

### ISSUE THREAD

**Issue by julioxavierr** [hayes/pothos#1140]
When utilizing the Relay Plugin's `relayMutationField`, it appears that there is currently no way to generate a mutation without the "inputFields" or "inputOptions". If attempted, it will result in a crash. Consequently, it is not feasible to create a mutation without any input arguments, thus leading to a mutation with an input argument that lacks additional fields.

With "inputOptions" as an empty object:

```
TypeError: inputFields is not a function
```

With "inputOptions" as null:

```
TypeError: Cannot read properties of null (reading 'name')
```

**Comment by hayes** [comment]
thanks for the report, this should be easy enough to fix.  I'll try to get a fix together this weekend

**Comment by hayes** [comment]
Just pushed an update to allow inputOptions to be passed as null to remove the input type
