### ISSUE TITLE
Feature Request: Pothos Errors Plugin: Allow mapping multiple error classes to one GraphQL error object

### ISSUE THREAD

**Issue by jasonkuhrt** [hayes/pothos#1142]
Apologies if this is already supported somehow. If it is, a docs example of it would be useful probably.

The issue I am facing is with the Pothos Errors plugin https://pothos-graphql.dev/docs/plugins/errors.

The issue (simplified for this feature request) is that I have a backend function that can return either of these two error classes:

1. `ErrorInternal`
2. `ErrorInternalInvariantViolation`

Note that (2) is a sub class of (1).

What I would like to do is that, when a resolver throws either `ErrorInternal` or `ErrorInternalInvariantViolation`, it maps to the same GraphQL object.

How can this be achieved, if at all? If not, the its a feature request. Thanks!

**Comment by hayes** [comment]
I would expect just only listing `ErrorInternal` in your list of errors should work.  Throwing a subclass should work the same as throwing the base class directly.  If this is not working as intended let me know. 

You should just be able to define a GraphQL type using the sub-type, and then if you want to change behavior in some fields, you can do something like `if (parent instanceof ErrorInternalInvariantViolation) { return 'its a variant' } else { return 'its the base class' }` or something similar

**Comment by jasonkuhrt** [comment]
Thanks @hayes-mysten I think I thought I  had tried your point and now I'm actually not sure. I'm going to double check next week, probably Monday. I'm going to pre-emptively close this issue and re-open if needed. Thanks!

**Comment by hayes** [comment]
Created a quick example here: https://stackblitz.com/edit/typescript-oxn7ex?file=index.ts

**Comment by jasonkuhrt** [comment]
Confirmed works, thanks @hayes !
