### ISSUE TITLE
`scopeAuthOptions.defaultStrategy = 'all'` not respected for context type augmentation

### ISSUE THREAD

**Issue by cyrilchapon** [hayes/pothos#1150]
When defining :

```ts
  AuthScopes: {
    authenticated: boolean;
    brandOwner: boolean;
  };
```

```ts
  AuthContexts: {
    authenticated: Context & { user: User };
    // brandOwner: nothing special
  };
```

with
```ts
  scopeAuthOptions: {
    defaultStrategy: 'all',
  },
```

if then using

```
  t
    .withAuth({
     authenticated: true,
     brandOwner: true
    })
```

The `resolve` function receives a wrong inferred `ctx` type with a **nullable** `user`, which is not correct in that case, whereas using an explicit `$all` operator narrows correctly.

Workaround :

- Leave `defaultStrategy: 'any'`
- Use explicit `$all` operator in `withAuth`; which narrows correctly

**Comment by hayes** [comment]
You can now provide `DefaultAuthStrategy: 'all'` when setting up the builder, this should the types for you
