### ISSUE TITLE
Relay Plugin - Cursor Type Default

### ISSUE THREAD

**Issue by xiavn** [hayes/pothos#1151]
Hello, thank you for the excellent documentation so far, however I ran into a slight issue where I think the documentation for the relay plugin is a little confusing.

The setup code example block says `cursorType: 'String'` will become the new default in the next major version, but then slightly further down the page, the explanation for the cursorType property reads like so:

> `cursorType`: `String` | `ID`. Determines type used for cursor fields. Defaults behavior due to legacy reasons is String for everything except for connection arguments which use ID. Overwriting this default is highly encouraged.

I think this is quite confusing wording on the explanation, as it simply says overwriting the default is highly encouraged, but the previous sentence has mentioned two defaults. Presumably you are suggesting overwriting the default to be String for everything due to the code example mentioned prior? Either way I think a small tweak to mention which default you recommend might make this clearer.

**Comment by hayes** [comment]
Set cursorType to String.  The default behavior is a mixed state where cursors are String, but the before/after arguments are ID.

**Comment by xiavn** [comment]
Thank you for the quick clarification, perhaps a clarification in the docs to something like:

> `currsorType`: `String` | `ID`. Determines type used for cursor fields. Default behavior due to legacy reasons is String for everything except for connection arguments which use ID. Overwriting this default to `String` is highly encouraged.

Might be helpful as it would also reinforce the settings mentioned in the earlier code block too.

**Comment by hayes** [comment]
Updated the docs
