### ISSUE TITLE
@tsconfig/node20: Could not find a declaration file for module '@pothos/plugin-federation'

### ISSUE THREAD

**Issue by brianmorin-ef** [hayes/pothos#1152]
Hi folks,

I'm running into an issue using @tsconfig/node20 and TS 5.1.6. The types file can't be found for the federation plugin, but it's found for the other plugins. I think it's just because the package.json has a missing types line that exists in the other plugin packages. It's just a matter of changing the exports field to match the other plugins:

```
"exports": {
  "import": {
    "default": "./esm/index.js"
  },
  "require": {
    "types": "./dts/index.d.ts",
    "default": "./lib/index.js"
  }
},
```

Happy to submit a PR if that's helpful.

**Comment by hayes** [comment]
good catch, I'll publish a fix in a minute

**Comment by hayes** [comment]
should be fixed now!
