### ISSUE TITLE
Enable setting global connection default size / max size

### ISSUE THREAD

**Issue by julioxavierr** [hayes/pothos#1157]
This is a feature request to allow overriding the global configuration for the default and maximum size of connections. Currently, the default size is set to 20. However, for teams that heavily rely on client-side pagination, this limit can be too low. It is common for us to forget to increase the size whenever we create a new connection.

https://pothos-graphql.dev/docs/plugins/relay#creating-connections

**Comment by hayes** [comment]
The defaults are part of the connection helpers, and don't have access to anything on the builder.   It would be trivial to wrap these helpers yourself to inject your own default values.  Forcing passing in the builder to extract global defaults would be a breaking change, and I wouldn't want to provide a way to set some kind of global state for defaults

**Comment by julioxavierr** [comment]
@hayes I see your point. From what I understand, I'd need a function that uses the connection helper under the hood and then import that function? 

Example:

```ts
customRelatedConnection = (t) => {
  ... // calls t.relatedConnection
}
```

Do you think it would be possible for me to override the `relatedConnection` in the field builder instead? So it includes the new defaults and I don't have to refactor the existing connections / change the way I create them?

**Comment by hayes** [comment]
If you are using the Prisma plugin with related connections, we could make the max and default sizes configurable for that.  The r.relatedConnection does have access to the builder options

**Comment by hayes** [comment]
Added new options to control the default and maxSize for prismaConnection, relatedConnection and prismaConnectionHelpers
