### ISSUE TITLE
Every `select` in `prismaField` inside `prismaObject` raises type error

### ISSUE THREAD

**Issue by devunt** [hayes/pothos#1159]
After upgrading to [@pothos/plugin-prisma@3.64.0](https://github.com/hayes/pothos/releases/tag/%40pothos%2Fplugin-prisma%403.64.0) from 3.63.1, every `select` in `prismaField` inside `prismaObject` raises type error.

Type signature of `select` insists that it expects the type `(args, ctx, nestedSelection) => never`.

**Comment by hayes** [comment]
have you re-run `prisma generate`?

**Comment by hayes** [comment]
Haven't heard back, so I am assuming that resolved your issue, but let me know if your still running into any problems after regenerating the types
