### ISSUE TITLE
Key Directive On Federation Plugin: Ability to set resolvable to false?

### ISSUE THREAD

**Issue by cameronmakarchuk** [hayes/pothos#1165]
Hi,

Maybe a simple question and I'm just missing something, but I'm using Pothos with Apollo Federation 2.0 and Prisma, and have been setting up entities. I'm able to resolve the entities, but on the `key` directive I can't seem to figure out how to set `resolvable: false` like you're able to with Apollo Server.

I feel like I'm just missing something but I can't find any reference to this anywhere in the docs or examples.

Any direction would be appreciated, thanks!

**Comment by hayes** [comment]
Thanks for spotting this, just pushed a fix, should be published in the next couple minutes, let me know if that works for you.

After updating, you should be able to do:

```ts
builder.asEntity(UserType, {
  key: builder.selection<{ id: string }>('id'),
  resolvable: false,
});
```

**Comment by cameronmakarchuk** [comment]
Thanks for jumping on this quickly! Maybe I have this backwards, but wouldn't it make more sense to be able to set `resolvable: false` on the other side in the `externalRef<>().implement()` ?

Something like this:

```
const UserType = builder.externalRef(
	'UserType',
	builder.selection<{ id: string; }>('id', {resolvable: false}),
).implement({
	fields: (t) => ({
		id: t.exposeString('id'),
	}),
});
```

Then you'd still define your entity type in the subgraph that resolves it, and when you're doing an `externalRef` in a different subgraph, that's where you can define whether that subgraph is going to add fields or not?

**Comment by hayes** [comment]
My concern was that builder.selection isn't strictly tied to the `@key` directive.  Looking at adding a key method for this:


Would something like this work for you?
```ts
const UserType = builder.externalRef(
	'UserType',
	builder.keyDirective(
	  builder.selection<{ id: string; }>('id', {resolvable: false}),
	  false
	)
).implement({
	fields: (t) => ({
		id: t.exposeString('id'),
	}),
});
```

**Comment by hayes** [comment]
Sorry for the churn.  I pushed out a new version with the above API.  I wanted to quickly get something a little better out so I could revert the previous attempt before anyone else started using it

**Comment by cameronmakarchuk** [comment]
That looks great! Thanks so much for getting that added so quickly 🙏 I'll play around with that this weekend.
