### ISSUE TITLE
Sentry tracing not showing the field name in description

### ISSUE THREAD

**Issue by mmahalwy** [hayes/pothos#1186]
With Sentry and all fields allowed, the field name is not sent as description, unlike see Prisma:
![image](https://github.com/hayes/pothos/assets/3749095/11732674-675d-4c67-ab18-0ad325fa19b3)

**Comment by hayes** [comment]
It looks like maybe https://github.com/hayes/pothos/blob/c67d1c8bc91d07ee3005fe202578244ecf2d8b99/packages/tracing-sentry/src/index.ts#L53 needs to be changed from description to name.  I don't have any apps set up with sentry right now, is that something you could test out?

**Comment by hayes** [comment]
This should be fixed now
