### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'never'

### ISSUE THREAD

**Issue by homerjam** [hayes/pothos#1194]
Hello,

I have the following in my code:

```js
	export type Result = {
		_id: string;
	};

	const Result = builder.objectRef<Result>('Result');

	builder.objectType(Result, {
		fields: (t) => {
			const fields: Record<keyof Result, FieldRef> = {
				_id: t.exposeString('_id', {}),
...
```

Which gives me the TS error `Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)`

I can remove the error with:

```js
_id: t.exposeString('_id' as never, { nullable: false as never }),
```

Any ideas why? 🤔

**Comment by hayes** [comment]
I don't see anything obviously wrong, and a quick attempt to reproduce your setup doesn't produce any errors: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAZQMYAsCmICGAhArsAGwBM0oAaOAbzgDFg1iAlNAMzgF84WoIQ4ByAAKQYKCAGcA9Emhp+AKHkyAduPgAjfMVJwAvHGVoA7olQYcWklAAUldgEpFaAB6RYcGAE8waOM3G4BPD6lPIAkGEA+sBEAFxwalDAygDmANzh7BlKEKrw-oHBcJqEVgB0EOoAVmhIMMwsADwFQQB81vwtMPz22SXaUBXVtTAAKt5o1l0UoXBc9MTi8dYw9nqtVPJzcypq8wxES3610ESNANZonhBs07QLRA0bIVvbc9FxHmUukOJoCDAkqkOh9+DMHGRXnN2Io3lA0DBcFBlPtFq8YQ4gA

Can you provide anymore info on how to reproduce the issue?

**Comment by homerjam** [comment]
Thanks very much for looking into this. I found the issue, sort of - in the non-example version I created the `Result` type from another type like so:

```js
type Result = SanityDocument;
```

The referenced type:
```js
export declare interface SanityDocument {
  _id: string
  _type: string
  _createdAt: string
  _updatedAt: string
  _rev: string
  [key: string]: unknown
}
```

I'm not sure why this doesn't work but it's fixed by manually creating the type as per the example.
