### ISSUE TITLE
Got error `Module '"xxx/node_modules/@pothos/plugin-prisma/generated"' has no default export` after upgrading to `4.0.0`

### ISSUE THREAD

**Issue by vimutti77** [hayes/pothos#1233]
After upgrading `pothos` to `4.0.0`, I got this error

![image](https://github.com/hayes/pothos/assets/27840664/1687f77f-840b-4923-a2bf-3e8a4a36f116)

I use the default `pothos` generator in prisma schema

![image](https://github.com/hayes/pothos/assets/27840664/459f3e5c-ae15-4209-8151-43d0c875d076)

**Comment by hayes** [comment]
thanks for reporting this, I just published a fix, let me know if you run into any other issues with v4!
