### ISSUE TITLE
v4 generates empty Prisma types

### ISSUE THREAD

**Issue by half0wl** [hayes/pothos#1235]
Versions:
```
    "@pothos/core": "^4.0.0",
    "@pothos/plugin-prisma": "^4.0.0",
```

Reproduce:

1. Have an existing schema and Prisma file configured:
```
generator pothos {
  provider = "prisma-pothos-types"
}
```
2. Run `prisma generate`, receive:
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema

✔ Generated Prisma Client (v5.16.2) to ./../../node_modules/.pnpm/@prisma+client@5.16.2_prisma@5.16.2/node_modules/@prisma/client in 112ms

✔ Generated Pothos integration to ./../../node_modules/.pnpm/@pothos+plugin-prisma@4.0.0_@pothos+core@4.0.0_graphql@16.9.0__@prisma+client@5.16.2_prisma@5_ablr3ngknrqxop6yh5fpzaxnqa/node_modules/@pothos/plugin-prisma/generated.d.ts in 32ms

...
```
4. See an empty file in `./../../node_modules/.pnpm/@pothos+plugin-prisma@4.0.0_@pothos+core@4.0.0_graphql@16.9.0__@prisma+client@5.16.2_prisma@5_ablr3ngknrqxop6yh5fpzaxnqa/node_modules/@pothos/plugin-prisma/generated.ts`:
```
/*
This File should be overwritten by adding the pothos generator to you prisma schema
and running `prisma generate`.  See https://pothos-graphql.dev/docs/plugins/prisma for more details
*/

export {};
```

The full types appear to be inside `./../../node_modules/.pnpm/@pothos+plugin-prisma@4.0.0_@pothos+core@4.0.0_graphql@16.9.0__@prisma+client@5.16.2_prisma@5_ablr3ngknrqxop6yh5fpzaxnqa/node_modules/@pothos/plugin-prisma/generated.d.ts` (note `.d.ts` instead of `.ts`), but I'm unable to import them

**Comment by hayes** [comment]
thanks for reporting this, I just published a fix, let me know if you run into any other issues with v4!
