### ISSUE TITLE
DataLoader missing fields using v4

### ISSUE THREAD

**Issue by kansson** [hayes/pothos#1236]
The `loadableObject` builder is missing dataloader specific fields like `load` and `cacheResolved` using v4.

**Comment by hayes** [comment]
Can you provide any more details or an example?

I tried to replicate the issue here: https://stackblitz.com/edit/typescript-jimqlg?file=index.ts. but haven't seen the same issue

**Comment by hayes** [comment]
Did you update the plugin as well when you upgraded to 4.0?

**Comment by kansson** [comment]
> Did you update the plugin as well when you upgraded to 4.0?

Oops you're right, forgot to update the plugin. Thanks.
