### ISSUE TITLE
[Simple Objects Plugin] Simple Interfaces fail to implement other interfaces

### ISSUE THREAD

**Issue by austin-statsig** [hayes/pothos#1238]
When trying to migrate some existing graphql schema over to pothos using the simple objects plugin to avoid defining classes I came across a case where I wasn't able to create a interface implementing other interfaces.
```
interface testInterface1 {
  interfaceBool: boolean;
  interfaceInt: number;
}

interface testInterface2 extends testInterface1 {
  interfaceString: string;
}

export const t1Ref = builder.interfaceRef<testInterface1>('t1');

t1Ref.implement({
  fields: (t) => ({
    interface1Bool: t.boolean({ nullable: false }),
    interface1Int: t.int({ nullable: false }),
  }),
});

export const t2Ref = builder.interfaceRef<testInterface2>('t2');

t2Ref.implement({
  interfaces: [t1Ref],
  fields: (t) => ({
    interface2String: t.string({ nullable: false }),
  }),
});
```

Runs just fine and gives expected behavior but doing the same with simple-objects

```
export const otherInterface1 = builder.simpleInterface("otherInterface1", {
  fields: (t) => ({
    otherInterface1Bool: t.boolean(),
  }),
});


export const otherInterface2 = builder.simpleInterface("otherInterface2", {
  // Type error on the interfaces array
  interfaces: [otherInterface1],
  fields: (t) => ({
    otherInterface2String: t.string(),
  }),
});

Interfaces array error:
Type 'InterfaceRef<ExtendDefaultTypes<{}>, { otherInterface1Bool?: boolean | null | undefined; }, { otherInterface1Bool?: boolean | null | undefined; }>' is not assignable to type 'InterfaceRef<ExtendDefaultTypes<{}>, { otherInterface1Bool?: boolean | null | undefined; }, { otherInterface1Bool?: boolean | null | undefined; }> & "Object shape must extend interface shape"'.
  Type 'InterfaceRef<ExtendDefaultTypes<{}>, { otherInterface1Bool?: boolean | null | undefined; }, { otherInterface1Bool?: boolean | null | undefined; }>' is not assignable to type '"Object shape must extend interface shape"'.
```
Gives the error listed above and fails to compile. I have a small reproduction of this in my profile.

**Comment by hayes** [comment]
This is somewhat expected, and not too hard to work around.  The simpleInterface helper does 2 things:  It defines the fields of the interface, and at the same time it defines the expected data type for the interface.  

The inferred type for otherInterface2 is:  `{ otherInterface2String: string }`, which pothos checks against the type for otherInterface1: `{ otherInterface1Bool: boolean }`.  and Sees they are not compatible. 
 
The easiest fix is to just define the inherited fields as well:
```ts
const otherInterface1 = builder.simpleInterface('otherInterface1', {
  fields: (t) => ({
    otherInterface1Bool: t.boolean(),
  }),
});

const otherInterface2 = builder.simpleInterface('otherInterface2', {
  // Type error on the interfaces array
  interfaces: [otherInterface1],
  fields: (t) => ({
    otherInterface1Bool: t.boolean(),
    otherInterface2String: t.string(),
  }),
});
```

I could see an argument for changing how interfaces work on simpleObjects/simpleInterfaces so that the inferredType is something like `TypeFromFields & TypeFromInterfaces` rather than checking compatibility like other object types

**Comment by hayes** [comment]
Thanks for opening this issue, having the interfaces just work without re-declaring fields makes a lot more sense.  I just pushed out an update that fixes this, and enforces that revolvers meet the requirements of both the interfaces and the fields defined on the object/interface

**Comment by hayes** [comment]
Let me know if you have an issues after updating

**Comment by austin-statsig** [comment]
Thanks! Having interface changes propagate to everything that implements them was a big reason I looked into this library the first place. This will be great for my use case now
