### ISSUE TITLE
Typescript version 4 errors when running pothos v4.0

### ISSUE THREAD

**Issue by austin-statsig** [hayes/pothos#1241]
When trying to run pothos with typescript 4.9.5 i get errors
```
TSError: ⨯ Unable to compile TypeScript:
schemaGen.ts:6:31 - error TS2339: Property 'toSchema' does not exist on type 'SchemaBuilder<ExtendDefaultTypes<{}>>'.

export const schema = builder.toSchema();
```
Issue goes away when when running version ^5.0.2. The [migration page](https://pothos-graphql.dev/docs/migrations/v4) specifies that min typescript version is 4.7.0. Not sure if also related but the min graphql version is listed as 16.6.0 but when running any package installs I get
```
 WARN  Issues with peer dependencies found
.
├─┬ @pothos/core 4.0.0
│ └── ✕ unmet peer graphql@^16.8.1: found 16.6.0
├─┬ @pothos/plugin-add-graphql 4.0.0
│ └── ✕ unmet peer graphql@^16.8.1: found 16.6.0
└─┬ @pothos/plugin-simple-objects 4.0.0
  └── ✕ unmet peer graphql@^16.8.1: found 16.6.0
```

**Comment by hayes** [comment]
Thanks for reporting this. I am looking into the typescript version issue.  The graphql peerDependency was unintentionally bumped, and I can revert it back down

**Comment by hayes** [comment]
I am publishing a new version that fixes the minimum graphql peer dependency (back to 16.6.0) and updated the docs to make typescript 5.0.2 as the minimum version.  Sorry for the mixup.

Let me know if you have any other issues with the upgrade!
