### ISSUE TITLE
Sentry tracing plugin no longer obeys ignoreError option

### ISSUE THREAD

**Issue by kingston** [hayes/pothos#1244]
The Sentry tracing plugin offers an ignoreError option to avoid capturing the exception in Sentry while still allowing tracing. However, it seems the latest version of Sentry removed the functionality of that option. Is this intentional or accidental? (just checking - I could file a PR to add it back but not sure what the intended behavior is).

I'm hoping to use it since I have a custom capture exception that adds additional functionality.

https://github.com/hayes/pothos/commit/cea5c66e6ceb1e837043cc91155a38eff3069bdd#diff-38f3e1881f8a4d5faf4709b839fcb0821c015dfbf76a1719f2f2e53046c59e41L64

**Comment by hayes** [comment]
Definitely unintentional, a pr would be more than welcome!

**Comment by hayes** [comment]
Just pushed a fix, will have a release out shortly.  Thanks for reporting this

**Comment by kingston** [comment]
Ah great thanks!  That was fast - didn't get a chance to write a PR :)
