### ISSUE TITLE
Default nullability in printed schemas is true

### ISSUE THREAD

**Issue by cedeerwe** [hayes/pothos#1254]
Hey, thanks for the cool package, like it a lot!

It seems that for printing schemas the default for nullability is `true` instead of `false`.

Using the example from the docs:
```
import { writeFileSync } from 'fs';
import { printSchema, lexicographicSortSchema } from 'graphql';
import SchemaBuilder from '@pothos/core';
 
const builder = new SchemaBuilder({});
 
builder.queryType({
  fields: (t) => ({
    hello: t.string({
      args: {
        name: t.arg.string(),
      },
      resolve: (parent, { name }) => `hello, ${name || 'World'}`,
    }),
  }),
});
 
const schema = builder.toSchema();
const schemaAsString = printSchema(lexicographicSortSchema(schema));
 
writeFileSync('/path/to/schema.graphql', schemaAsString);
```
gives 
```
type Query {
  hello(name: String): String
}
```
while explicitly stating `nullable: false` like this
```
import { writeFileSync } from 'fs';
import { printSchema, lexicographicSortSchema } from 'graphql';
import SchemaBuilder from '@pothos/core';
 
const builder = new SchemaBuilder({});
 
builder.queryType({
  fields: (t) => ({
    hello: t.string({
      args: {
        name: t.arg.string(),
      },
      nullable: false,
      resolve: (parent, { name }) => `hello, ${name || 'World'}`,
    }),
  }),
});
 
const schema = builder.toSchema();
const schemaAsString = printSchema(lexicographicSortSchema(schema));
 
writeFileSync('/path/to/schema.graphql', schemaAsString);
```
gives 
```
type Query {
  hello(name: String): String!
}
```

Is suppose it's just a simple bug somewhere. I will explicitly state the nullability in my code to overcome this.

**Comment by hayes** [comment]
Changing the default nullability of fields is described here: https://pothos-graphql.dev/docs/guide/changing-default-nullability

**Comment by hayes** [comment]
If there are docs that indicate that the default should be for fields to be non-nullable, let me know and I can get them updated.  Making fields nullable by default is intentional, but might be incorrectly documented somewhere.

**Comment by cedeerwe** [comment]
I believe this made me confused: https://pothos-graphql.dev/docs/guide/fields#nullable-fields

> Unlike some other GraphQL implementations, fields in Pothos are non-nullable by default.

**Comment by cedeerwe** [comment]
I also recall that this was "softly" mentioned on multiple places, when I read through the documentation from start to end.

**Comment by hayes** [comment]
Just pushed up some changes to the docs that should remove some of the references to the old defaults.  Let me know if you notice anything else!
