### ISSUE TITLE
Prisma Utils plugin does not have createMany option

### ISSUE THREAD

**Issue by SpeedySH** [hayes/pothos#1256]
Maybe I'm wrong, but since we have updateMany, deleteMany, there should also be createMany. Since the original prisma client has such a field.

```
const EnvironmentVariableCreate = builder.prismaCreateRelation("Project", "environmentVariables", {
  name: "EnvironmentVariableCreate",
  fields: (t) => ({
    create: EnvironmentVariableCreateInput,
    createMany: { data: EnvironmentVariableCreateInput, skipDuplicates: t.boolean() },  // ERROR: <unnamed ref or enum> has not been implemented
  }),
});

const EnvironmentVariablesUpdate = builder.prismaUpdateRelation("Project", "environmentVariables", {
  name: "EnvironmentVariablesUpdate",
  fields: (t) => ({
    create: EnvironmentVariableCreateInput,
    createMany: { data: EnvironmentVariableCreateInput, skipDuplicates: t.boolean() }, // ERROR: <unnamed ref or enum> has not been implemented
    update: {
      where: EnvironmentVariableUniqueFilter,
      data: EnvironmentVariableCreateInput,
    },
    updateMany: {
      where: EnvironmentVariableUniqueFilter,
      data: EnvironmentVariableCreateInput,
    },
    delete: EnvironmentVariableUniqueFilter,
    deleteMany: EnvironmentVariableUniqueFilter,
  }),
});

```
Thanks in advance for the clarification :)

**Comment by hayes** [comment]
The reason this hasn't been implemented is that the createMany updates for fields use very specific types that are scoped to the specific relation, so you need to create a very specific input type.  The type would be something like:

`ProjectCreateManyEnvironmentVariables`.  This input type doesn't support nested relations, and omits the source relation.  To accomidate this, we either need to define this type inline (which gets complicated with nested field builder callbacks), or we need to add another builder method like:

```ts
builder.prismaRelateCreateMany('Project', 'environmentVariables',  {
  fields: ...createManyFields
})
```

This is probably manageable, but adds a lot of overhead for a relatively small use-case

**Comment by hayes** [comment]
Added a new `builder.prismaCreateMany` helper added a `createMany` field to `prismaUpdateRelation`.  Let me know how that works for you!
