### ISSUE TITLE
Latest plugin-prisma-utils not published on NPM

### ISSUE THREAD

**Issue by OllieJennings** [hayes/pothos#1262]
Hey,

It looks like the latest version of `@pothos/plugin-prisma-utils` is not published to NPM.

From the output of your CI: ` @pothos/plugin-prisma-utils is not being published because version 2.0.0 is already published on npm`

Then from looking at npm itself: https://www.npmjs.com/package/@pothos/plugin-prisma-utils?activeTab=versions the latest version seems to be `1.1.0`.

Only found out because l tried to do a dependency update, and it failed to install some deps because plugin-prisma-utils was v1.1.0 which requires the older version of plugin-prisma:

```
While resolving: xxx@0.24.0
Found: @pothos/plugin-prisma@4.1.0
node_modules/@pothos/plugin-prisma
  @pothos/plugin-prisma@"^4.1.0" from xxx@0.24.0
  apps/xxx
    xxx@0.24.0
    node_modules/xxx
      workspace apps/xxx from the root project

Could not resolve dependency:
peer @pothos/plugin-prisma@"4.0.5" from @pothos/plugin-prisma-utils@1.1.0
node_modules/@pothos/plugin-prisma-utils
  @pothos/plugin-prisma-utils@"^1.1.0" from xxx@0.24.0
  apps/xxx
    xxx@0.24.0
    node_modules/xxx
      workspace apps/xxx from the root project
```

**Comment by hayes** [comment]
Very weird, I don't know why that got a major bump... That definitely should not have been a 2.0 release.  I'll try to figure out what's going on later today

**Comment by OllieJennings** [comment]
No worries, just thought l would flag incase others had issues.

**Comment by hayes** [comment]
manually reverted the version to 1.1.1 which was the expected next release, I'll try to keep an eye on the changeset release process for upcoming release to see if something like this happens again.
