### ISSUE TITLE
[BUG Replay plugin] PothosValidationError: Invalid global ID: RXN0YXRlOjRlYTk5YmYxLTA3MTktNDNkZi04ZTZkLWM4MjA1YjE5MGNhZQ%3D%3D

### ISSUE THREAD

**Issue by arnaud-deprez** [hayes/pothos#1273]
# Description

It seems the regex used to validate base64 encoded string is not taking into account some special characters.

See the regex: https://github.com/hayes/pothos/blob/main/packages/core/src/utils/base64.ts#L40
See this string for example: `RXN0YXRlOjRlYTk5YmYxLTA3MTktNDNkZi04ZTZkLWM4MjA1YjE5MGNhZQ%3D%3D`

**Comment by hayes** [comment]
This id isn't valid base64, it looks like it's been URL encoded or something?

**Comment by hayes** [comment]
%3D is the URL encoded = which would be valid base64

**Comment by arnaud-deprez** [comment]
Ah indeed @hayes my bad. I put the in an url before reusing it. So I was wondering why replay could not decode its own id, but it has been re-encoded in url format by NextJS.

Will close this, sorry for the inconvenience

Thanks!
