### ISSUE TITLE
[plugin-add-graphql] Nested arrays are removed from existing schema 

### ISSUE THREAD

**Issue by tuttleb** [hayes/pothos#1311]
When using the Add GraphQL Plugin to gradually migrate from Nexus to Pothos, the schema outputted by Pothos is incompatible with the original schema because it collapses nested list arguments into non-nested lists.

In Nexus I'm defining an argument like this `arg({ type: list(list(CollectionFilter)) })`. The generated schema from Nexus for this arg has type: `[[CollectionFilter!]!]`

I then pass the schema from Nexus into Pothos:
```
const builder = new SchemaBuilder({
  plugins: [AddGraphQLPlugin],
  add: {
    schema: nexusSchema,
  },
});
const schema = builder.toSchema()
```

if I take that schema from Pothos and lookup the same arg type, I now get back: `[CollectionFilter!]` which is incompatible with what the original schema because it is no longer a nested list.

I can sort of manually override / repair the schema like:

```
const arg = // lookup the arg in the schema generated by Pothos
arg.type = new GraphQLList(new GraphQLNonNull(arg.type));
 ```

Interestingly it seems like any arbitrary amount of list nesting gets collapsed in Pothos. Meaning if I define an argument's type as something like: `list(list(list(list(CollectionFilter))))` Nexus would output this as: `[[[[CollectionFilter!]!]!]!]`. When that schema gets added to Pothos, this is again interpreted as a non-nested array `[CollectionFilter!]`.

**Comment by tuttleb** [comment]
I've done some debugging here and the issue seems to come from the `resolveInputType` function here: https://github.com/hayes/pothos/blob/afdce2b39f7d95e39f3e3dd14979a9d95cd754e4/packages/plugin-add-graphql/src/schema-builder.ts#L86-L110 which assumes that only one level of nesting is possible for a list

**Comment by hayes** [comment]
thanks for reporting this, should be fixed now if you upgrade

**Comment by tuttleb** [comment]
Awesome, thanks so much! Just upgraded to the latest release and my problem is solved.
