### ISSUE TITLE
TypeError: User.id was defined as a undefined field but User is a Object

### ISSUE THREAD

**Issue by botoxparty** [hayes/pothos#1326]
I don't understand why this is not working, i'm going crazy. Is it obvious to anyone else?:

`api:dev: TypeError: User.id was defined as a undefined field but User is a Object`

My definition:

```
import builder from '@/src/builder';

export const Role = builder.enumType('Role', {
  values: ['ADMIN', 'DOCTOR', 'PATIENT', 'PHARMACY'],
  description: 'User role',
});

export const User = builder.prismaObject('User', {
  fields: (t) => ({
    id: t.exposeID('id'),
  }),
});

```

My prisma schema:

```
model User {
  id            String           @id @default(cuid())
  email         String
  role          String           @default("USER")
}

```

**Comment by hayes** [comment]
What versions of Pothos packages are you using? My best guess here are that you are using incompatible versions of core and the Prisma plugin.

I didn't see that error in the current version of Pothos code base, but I might have missed it

**Comment by botoxparty** [comment]
Totally right, it was a version mismatch. Updated all my pothos versions and works perfectly now.
