### ISSUE TITLE
[Add GraphQL plugin] Subscribe implementation removed from existing schema

### ISSUE THREAD

**Issue by tuttleb** [hayes/pothos#1332]
When an existing schema includes subscription fields, the implementation of `subscribe` is lost from the original schema.

I think the issue is coming from [this section of code](https://github.com/hayes/pothos/blob/main/packages/plugin-add-graphql/src/schema-builder.ts#L148-L154), where the subscribe functions are not included in the same way that resolve is.

I think the fix could be as simple as adding subscribe to that block:

```
        combinedFields[fieldName] = t.field({
          ...resolveOutputType(this, field.type),
          args,
          description: field.description ?? undefined,
          deprecationReason: field.deprecationReason ?? undefined,
          resolve: (field.resolve ?? defaultFieldResolver) as never,
          subscribe: field.subscribe, // include subscribe here
        });
```

but I'm not quite sure the correct way to make it mesh with the current types

**Comment by hayes** [comment]
this should be fixed now if you update
