### ISSUE TITLE
Drizzle plugin -Schema property required

### ISSUE THREAD

**Issue by olup** [hayes/pothos#1335]
I had to add the schema property to the drizzle option - or else I would get an error `Cannot convert undefined or null to object` when creating my objects. 
Maybe this should be documented ?

**Comment by hayes** [comment]
The schema option is shown in the docs for `installing` the plugin (https://pothos-graphql.dev/docs/plugins/drizzle#installing) which has a link to the drizzle docs describing how to create a relational query builder:

> The drizzle plugin is built on top of drizzles relational query builder, and requires that you define and configure all the relevant relations in your drizzle schema. See https://orm.drizzle.team/docs/rqb for detailed documentation on the relations API.

More than happy to accept PRs to improve the docs though

**Comment by olup** [comment]
Hey thanks for the quick reply and of course I can lend a hand. Thanks for this necessary library.
