### ISSUE TITLE
directives will lose type information which makes you unable to use scope in cacheControl directive

### ISSUE THREAD

**Issue by macrozone** [hayes/pothos#1353]
i have a a cache control directive:

```
export const cacheControlDirective = new GraphQLDirective({
  locations: [
    DirectiveLocation.FIELD_DEFINITION,
    DirectiveLocation.OBJECT,
    DirectiveLocation.INTERFACE,
    DirectiveLocation.UNION,
  ],
  name: "cacheControl",
  description: "Marks a field as cacheable",
  args: {
    scope: {
      defaultValue: "PRIVATE",
      description: "The scope for the cache",
      type: new GraphQLEnumType({
        name: "CacheControlScope",
        values: {
          PUBLIC: { value: "PUBLIC" },
          PRIVATE: { value: "PRIVATE" },
        },
      }),
    },
    maxAge: {
      description: "The maximum age of the cache in seconds",
      type: GraphQLInt,
    },
    inheritMaxAge: {
      description: "Inherit max age from parent",
      type: GraphQLBoolean,
    },
  },
});


export const subgraphSchemaConfig = {
  federationDirectives: [
    "@key",
    "@extends",
    "@external",
    "@requires",
    "@provides",
    "@composeDirective",
  ],
  
  directives: [visibleInSchemaDirective, cacheControlDirective],
};



export const schema = builder.toSubGraphSchema(subgraphSchemaConfig);
```

i then have a object ref:

```

builder.queryField("organisation", (t) =>
  t.prismaField({
    type: "Organisation",
    directives: {
      cacheControl: {
        scope: "PRIVATE",
        maxAge: 1234,
      },
    },
    args: {
      where: t.arg({
        required: true,
        type: OrganisationWhereUniqueInputRef,
      }),
    },
...
```

the maxAge time is accepted both in the response header and is used by the responseCache, but the scope is always "PUBLIC"

i can confirm that PRIVATE is not used by logging like this:

```
new ApolloServer<{}>({
      schema: config.schema,
      plugins: [
        {
          requestDidStart: async () => ({
            willSendResponse(requestContext) {
              console.log("Cache hints:", requestContext.overallCachePolicy);
            },
          }),
        },
```

not sure if this is a problem with how pothos builds the subgraph schema or with apollo server. I am currently lost and need some help

**Comment by macrozone** [comment]
after turning on the good old debugger, i found out that

here: https://github.com/apollographql/apollo-server/blob/99bcaaa6e1d8f4d5f20453b8d8715ae5e1552bae/packages/server/src/plugin/cacheControl/index.ts#L394

the scope value is of type "StringValue" , but it expect an EnumValue in the AST

<img width="583" alt="Screenshot 2024-11-29 at 16 37 40" src="https://github.com/user-attachments/assets/e71ce10c-0915-4b30-9acd-3cfe0d44af59">

in the printed graphql schema, the directive has definitly an enum type:

```graphql

enum CacheControlScope {
  PUBLIC
  PRIVATE
}


"""Marks a field as cacheable"""
directive @cacheControl(
  """Inherit max age from parent"""
  inheritMaxAge: Boolean

  """The maximum age of the cache in seconds"""
  maxAge: Int

  """The scope for the cache"""
  scope: CacheControlScope
) on FIELD_DEFINITION | INTERFACE | OBJECT | UNION
```

but it looks like when generating the ast, the type is wrong here

**Comment by macrozone** [comment]
after digging deeper the problem happens here:

https://github.com/hayes/pothos/blob/main/packages/plugin-directives/src/mock-ast.ts#L163C14-L163C24

there it will create a stringValue type, because it uses no information about the directive type in the schema

**Comment by hayes** [comment]
Thanks for reporting this, and providing a detailed investigation into the issue.  This makes sense, but doesn't look easy to fix.

We don't currently have any idea about the types of directives when building up the fake AST nodes.

The tooling around directives in code-first graphql is very hacky, and there aren't great existing solutions..

I am also not entirely sure the AST nodes are the real source of the issue.  Apollo shouldn't be looking at the AST nodes as the source of truth for these values.

I'll try to find some time soon to see if I can understand what Apollo is doing here

**Comment by macrozone** [comment]
hey @hayes,

wow, i did not expect such immediate fix! 

i tested it, and indeed it seems to fix the issue: the astNode of the directive argument has the right type and indeed in apollo the overall cache policy is now correct at first glance. I do some proper testing later today.

I also briefly looked at the code and I assumed the fix would have looked like this: to lookup type information about the directive from the schema.

I was just not sure how it was designed to work, so i wasn't sure whether i was missing something.

> The tooling around directives in code-first graphql is very hacky, and there aren't great existing solutions..
> 
> I am also not entirely sure the AST nodes are the real source of the issue. Apollo shouldn't be looking at the AST nodes as the source of truth for these values.

I was wondering this as well, since they could just check the values of the directive args in that line of code, instead of additionaly comparing the types.

But I was wondering, how they expect the schema to be in that case. I guess they normally assume you build the schema with makeExecutableSchema or so from typedefs and resolvers. That function also has to add this type information in the directive, maybe its worth to checkout how they do that. Otherwise the same error would happen.

**Comment by macrozone** [comment]
looks fixed, I close! thank you very much!
