### ISSUE TITLE
`prismaField` in prisma plugin doesn't use `subGraphs` property from the subgraph plugin

### ISSUE THREAD

**Issue by alanko0511** [hayes/pothos#1356]
Hi, I'm not sure if my setup is wrong or if it is a bug, but it seems that if I declare a field using `prismaField` with the `subGraphs` property like this:
```ts
builder.queryFields((t) => ({
  currentUser: t.prismaField({
    subGraphs: ["Global"],
    type: "User",
    resolve: (query, parent, qrgs, ctx) => {
      return ctx.req.currentUser;
    },
  }),
}));

builder.queryField("test", (t) => t.string({ resolve: () => "test", subGraphs: ["Global"] }));

export const schema = builder.toSchema({
  subGraph: ["Global"],
});
```

I can only see the `test` field in the query, but the `currentUser` is missing. I can see both if I don't set the `subGraph` property in the `builder.toSchema` function.

**Comment by hayes** [comment]
Is your user field part of the global subgraph?

**Comment by alanko0511** [comment]
Ahh, that's the fix. Thanks for reminding me of that 👍
