### ISSUE TITLE
Module not found SchemaBuilder - deno

### ISSUE THREAD

**Issue by ollosh** [hayes/pothos#259]
I'm using deno 1.17.1 and have just tried to follow the docs and run the example code, but whatever I try I keep getting the same error. Anyone had issues with this?

![image](https://user-images.githubusercontent.com/12979324/148251669-ca8b44d6-69ce-4a35-9cea-ca468031f51e.png)

Edit: Seems like deno can't determine where exactly to fetch the latest version from. When I follow the link from the example the url transforms to: `https://deno.land/x/giraphql@%40giraphql%2Fdeno%402.20.0/packages/core/mod.ts` so it seems it has something to do with url encoding

**Comment by hayes** [comment]
Sorry it took my a while to respond.  I don't know what's going on with deno.land, but it seems like their previous behavior of defaulting to the latest version from their cdn has stopped working.  I don't have time right now to re-design the release process and try to figure out how to improve the deno.land experience.  Instead, I think just using jsdeliver or another cdn should be a decent work around.


Here is an updated set of imports and an import map that seems to work:

```ts
import { Application, Router } from "https://deno.land/x/oak@v10.1.0/mod.ts";
import { shouldRenderGraphiQL } from "https://cdn.jsdelivr.net/gh/contrawork/graphql-helix@master/packages/deno/should-render-graphiql.ts";
import { processRequest } from "https://cdn.jsdelivr.net/gh/contrawork/graphql-helix@master/packages/deno/process-request.ts";
import { getGraphQLParameters } from "https://cdn.jsdelivr.net/gh/contrawork/graphql-helix@master/packages/deno/get-graphql-parameters.ts";
import playground from "https://gist.githubusercontent.com/hayes/5c99f7b4f71234452036fd88e142a825/raw/655245a052b10c2912a803c8a6d537096b73c10b/playground.ts";
import SchemaBuilder from "https://cdn.jsdelivr.net/gh/hayes/giraphql/packages/deno/packages/core/mod.ts";
```
```json
{
  "imports": {
    "https://cdn.skypack.dev/graphql@16.0.0-experimental-stream-defer.5?dts": "https://cdn.skypack.dev/graphql@v16.2.0?dts",
    "https://cdn.skypack.dev/graphql?dts": "https://cdn.skypack.dev/graphql@v16.2.0?dts"
  }
}
```

**Comment by zaiste** [comment]
I may have a similar issue. I'm trying to set up `import_map.json` as shown below:

```
{
  "imports": {
    "@pothos/core": "https://deno.land/x/pothos@@pothos%2Fcore@3.3.2",
    "graphql": "https://cdn.skypack.dev/graphql"
  }
}
```

so that I could keep the same `import` statements as in Node.js.

`deno run` returns: 

```
error: Module not found "https://deno.land/x/pothos@@pothos%2Fcore@3.3.2"
```

I suspect the `@` character in the package name could be the culprit. At the same time, if this URL is opened in the browser, it shows the correct Deno Land page.

Is there a way to solve this?

**Comment by hayes** [comment]
as I mentioned above, there is an issue I haven't had time to investigate with deno.land, Importing from jsdelivr seems to work thougnh

**Comment by zaiste** [comment]
No worries! I'll investigate that

**Comment by hayes** [comment]
Took me a long time to get back around to updating the deno docs, but I've added some new docs on the current best options for using pothos in deno.

Now that graphql-yoga supports deno, building graphql apis in deno is super easy!

https://pothos-graphql.dev/docs/guide/deno
