### ISSUE TITLE
Error when using multiple `prismaObject`s for a single model.

### ISSUE THREAD

**Issue by kesne** [hayes/pothos#262]
In my database, I have a single model `User`, but I want two types that are generated in the GraphQL schema as a result (`User` and `Viewer`). However, when trying to do this, I just get one output type.

```typescript
builder.prismaObject('User', {
	name: 'Viewer',
	findUnique: (user) => ({ id: user.id }),
	fields: (t) => ({
		id: t.exposeID('id'),
	}),
});

builder.prismaObject('User', {
	name: 'User',
	findUnique: (user) => ({ id: user.id }),
	fields: (t) => ({
		id: t.exposeID('id'),
	}),
});
```

**Comment by hayes** [comment]
That is a bit of an issue... Would need a way to determine what version, would need a way for relations and prismaFields to know which type they are supposed to use

**Comment by kesne** [comment]
Yeah I realized that this is really tricky because of how the rest of the API uses the prisma model names. Maybe the perfect API just doesn't exist 😭

**Comment by hayes** [comment]
Might be able to make something work with refs

**Comment by hayes** [comment]
Will eventually be fixed by https://github.com/hayes/giraphql/pull/263

**Comment by hayes** [comment]
This is now available as https://www.pothos-graphql.dev/docs/plugins/prisma#variants
