### ISSUE TITLE
Breaking changes for v4

### ISSUE THREAD

**Issue by hayes** [hayes/pothos#279]
This issue contains a list of changes I would like to make, but require some breaking changes to the API.  Most of these changes will not affect the majority of users, but still requires a major version bump.

* [ ] Refs should maintain types and have a reference to builder for chaining, mutation, and creating derivative types. 
* [ ] resolveType API should be redesigned to be more configurable
* [ ] typing around interfaces should be made more flexible
* [ ] relay plugin options should be made consistent with other options
* [ ] validation plugin API needs to be re-visited
* [ ] re-evaluate default type for ids
* [ ] field refs should not be pre-assigned to a type so they can be re-used
* [ ] Investigate return value authorization via isTypeOf checks
* [ ] Unify/standardize/share loadOne/loadMany across plugins
* [ ] Relay plugin should be update default nullability to match connection spec 
* [ ] Add typescript 4.7 variance hints to improve type-checking speed and responsiveness
* [ ] Enable builder-independent refs for sharing type across packages
* [ ] Standardize naming conventions for how plugin options are nested in builder options
* [ ] Prisma connection total counts should be filtered by default
* [ ] Consider alternative changeset versioning for linked packages
* [ ] Brand all loaded nodes and make isTypeOf optional on node definitions
* [ ] Bump min graphql to 16 and ts to ~4.7?
* [ ] Support read-only tuples for list type references

**Comment by hayes** [comment]
There should be an easy way to apply defaults from Pothos 3.0:

```ts
condt builder = new Schema builder<{ Defaults: 'v3' }>({ defaults: 'v3' })
```

**Comment by aniravi24** [comment]
It would be cool if the next iteration of the validation API was able to support more schema libraries besides zod (e.g. [@effect/schema](https://github.com/Effect-TS/schema)) or have a generic enough design that you could plug in a custom validator. Not sure exactly how this might look, but would be interesting!

**Comment by hayes** [comment]
these changes are being worked on in #855
