### ISSUE TITLE
Mismatching `parent` types on `prismaNode` api

### ISSUE THREAD

**Issue by baristikir** [hayes/pothos#280]
## Issue
Mismatching `parent` types on the `prismaNode` api. Can be tested with the usage of `scope-auth` plugin where the parent value of grantScopes / authScopes are typed as `any`.

![prismaNode-parent-any](https://user-images.githubusercontent.com/44122379/151148494-92ff8705-a8da-4cae-9404-9a7c0f7798e7.png)

Can this be related to the `ObjectRef<Shape>` on the `prisma` plugin https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/types.ts#L148 ?

I've also added a small repro as example here
https://github.com/baristikir/giraphql/blob/prisma-relay-auth/examples/prisma-relay-auth/src/schema.ts

**Comment by baristikir** [comment]
besides that a general question, I've never worked with pnpm and so how should dependencies be added to examples? 
Is `pnpm add @pothos/plugin-scope-auth` the right way to do it? It adds this line to the `package.json` (https://github.com/baristikir/giraphql/blob/prisma-relay-auth/examples/prisma-relay-auth/package.json#L22) which confused me a bit.

**Comment by hayes** [comment]
Yup, that seems to have been causing the issue.  I should have tested more manually before assuming the earlier fix was sufficient.

Just pushed up a fix, should be released in a few minutes.

Yes, generally `pnpm add` is the way you add deps with pnpm.  But, I have not been doing that in this repo, and just been editing package.json manually to add the dependencies I want, before running `pnpm install`.  I think the `workspace:` prefix is the correct way to add a dep that uses the local version, but I haven't been using it, and haven't tested it to make sure it works well with other tools that analyze dependencies (like turbo repo and changesets)

**Comment by hayes** [comment]
fix should be published now
