### ISSUE TITLE
Object type - allow type as first argument instead of class

### ISSUE THREAD

**Issue by homoky** [hayes/pothos#300]
Hey! 

I am coming from nexus and checking out the pothos.

I've tried to setup first Object type and I don't know if I miss something. I would love to create very simple object from the scratch.

Nexus:

```
export default objectType({
  name: 'SimpleObject',
  definition(t) {
    t.id("id")
    t.string("name")
  },
});
```

Pothos:

```
export class Chord {
  id: string;
  name: string;
  constructor(id: string, name: string) {
    this.id = id;
    this.name = name;
  }
}

export default builder.objectType(Chord, { name: 'Chord' });
```

Do I miss something? Can I create objectType without class and set fields with builder? Also it would be great, if `type` would be accepted as first parameter.

Thanks.

**Comment by xoldyckk** [comment]
Read this thoroughly :- [https://pothos-graphql.dev/docs/guide/schema-builder](https://pothos-graphql.dev/docs/guide/schema-builder).

**Comment by hayes** [comment]
@homoky there are a number of options.

Unlike nexus, Pothos does not generate types based on your definition, so every type needs to get it's type information from somewhere. Classes are one option, but not one I ever use.

You can explicitly provide a type using `builder.objectRef<Type>(name).implement({})`

You can add types when you create the schema builder, so you can reference the types by name.  This is roughly equivalent to manually defining something like what nexus creates automatically.

The easiest option is probably to use the simple-objects plugin.  This will feel most like what you are used to from nexus.  It will infer the needed types from the fields you define, so you don't have to provide any types yourself.
