### ISSUE TITLE
Feature Request: add 'parent' to field complexity function parameter

### ISSUE THREAD

**Issue by 100BC** [hayes/pothos#307]
Hi there, I was wondering if it'd be possible for the complexity parameter on a field capable of being written as this.

`complexity: (parent, args, ctx) => ({ field: X, multiplier: Y })` 

The use case is based of this section in the documentation: [How to add Prisma and Pothos without a plugin](https://pothos-graphql.dev/docs/plugins/prisma#pothos--prisma-without-a-plugin). If you follow the guide to create a schema that sometimes loads in another shape, calculating the complexity is somewhat unnecessary. From the example given in the doc:

```
PostObject.implement({
  fields: (t) => ({
    id: t.exposeID('id'),
    title: t.exposeString('title'),
    author: t.field({
      type: UserObject,
      
      // Ability to do this
      complexity: (post, _args, _ctx) => (post.author ? 1 : { field: 50, multiplier: 5 })
      
      resolve: (post) =>
        post.author ?? db.user.findUnique({ rejectOnNotFound: true, where: { id: post.authorId } }),
    }),
  }),
});
```
Mostly a nice to have feature, rather than something critical, but I am hoping this is a simple request.

Thanks for the great library!

**Comment by hayes** [comment]
The complexity plugin does not run along side revolvers.  Complexity is calculated up front to prevent even attempting to resolve a query that has a complexity over the defined limit.  The downside of this is that you won't be able to access the parent value, since the complexity is already determined before the parent value is resolved.

**Comment by 100BC** [comment]
Well that's unfortunate but this was mostly a nice to have rather a crucial thing. Closing this issue. Thanks!

**Comment by hayes** [comment]
@100BC if it was important to you, you could implement a copy of the plugin that does runtime complexity.  The implementation would probably be pretty simple, and could copy all the types from the current plugin as a starting place.  If you end up doing that, let me know and I'd be happy to help

**Comment by 100BC** [comment]
It isn't really, mostly for a hobby project. That being said, it does sound like a interesting challenge so if I do get some free time I might poke around, but I won't reopen the issue as I won't be actively working on it.
