### ISSUE TITLE
isTypeOf seems to have lost type inference 

### ISSUE THREAD

**Issue by theogravity** [hayes/pothos#336]
I updated my example repo to the latest package versions:

https://github.com/theogravity/graphql-pothos-server-example

When I run `yarn dev`, I get the following:

```
[INFO] 14:55:12 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.5)
Compilation error in /Users/theo/projects/graphql-giraphql-server-client-example/src/gql/subscriptions/posts/new-post.event.ts
[ERROR] 14:55:15 ⨯ Unable to compile TypeScript:
src/gql/subscriptions/posts/new-post.event.ts:21:12 - error TS2571: Object is of type 'unknown'.

21     return value.eventType === PostEventType.NewPost;
              ~~~~~
```

Trying to apply the following in `new-post.event.ts` doesn't work either:

```
  isTypeOf: (value: NewPostEvent) => {
    return value.eventType === PostEventType.NewPost;
  },
```

<img width="1203" alt="CleanShot 2022-02-27 at 14 59 26@2x" src="https://user-images.githubusercontent.com/855434/155903580-4aea033e-efb9-4d85-b451-c305245fc207.png">

You can pull down the example repo and mess around if you need to.

**Comment by hayes** [comment]
The inferred type there was actually a bug, and should always have been unknown.  There is no way to know safely that the object type is not used in a union meaning that we can't assume that the value past to isTypeOf must be of the same type as one of it's interfaces.

**Comment by theogravity** [comment]
That's fair. What's the recommended approach for clearing out the type error?

**Comment by hayes** [comment]
Depends a lot on your application.  A good option might be to create a type predicate function for the type you are expecting: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

I frequently just use an inline cast like `(val as {type: SomeTypeUnion}).type === ExpectedType`

**Comment by theogravity** [comment]
Thanks!
