### ISSUE TITLE
NexusGenObjectNames and NexusGenFieldTypes with pothos

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#344]
Hello, thank you for this great library!
I am currently migrating a nexus codebase to pothos.
I use [graphql-shield](https://www.graphql-shield.com) to protect my schema and created a helper type that ensures that all the fields that I specify in my rules, exist in my schema and that every query and mutation is explicitly assigned a rule:

```ts
// Objects that require an explicit rule for every field
type ObjectsWithStrictTyping = 'Query' | 'Mutation'

// Rules type enriched by nexus generated types to ensure a rule for each object
// exists and fields in objects are correctly spelled.
type Rules = {
	[ObjectName in Exclude<NexusGenObjectNames, ObjectsWithStrictTyping>]:
		| ShieldRule
		| { [FieldName in keyof NexusGenFieldTypes[ObjectName] | '*']?: ShieldRule }
} & {
	[ObjectName in ObjectsWithStrictTyping]: {
		[FieldName in keyof NexusGenFieldTypes[ObjectName]]: ShieldRule
	}
}
```

Is there an alternative to the nexus generated types`NexusGenObjectNames` and `NexusGenFieldTypes` in pothos?
Can that information be somehow extracted from `typeof schema`?

**Comment by hayes** [comment]
Short answer is no.  Pothos does not use codegen, and is fairly modular, so there is no way to infer the fields defined in your whole schema.

One of the design goals of Pothos was specifically to eliminate this kind of duplication where you create structures like this for mapping each field/type in your schema.  

These rules should be defined alongside your field or type definitions, so you think about them as you write your schema.  

Pothos makes it really easy to write plugins that require defining something for each field or type.  I can put an example together for you later today

**Comment by P4sca1** [comment]
Thank you for the info!
I previously wrote a nexus plugin, which let me define the graphql-shield rules along with my schema, but I decided for myself, that I prefer a single shield file, because it makes it easier to scan the rules that are assigned to my schema (authorization is quite complex in my case).
I will work without typed Rules for now, graphql-shield provides runtime validation anyways.

**Comment by hayes** [comment]
I has already mostly written the example by the time you replied, so I cleaned it up a bit and added it to the repo in case anyone else had a similar question: https://github.com/hayes/pothos/blob/main/examples/graphql-shield/src/shield-plugin.ts
