### ISSUE TITLE
Dataloader cycle, use of ref does not bring same experience

### ISSUE THREAD

**Issue by homoky** [hayes/pothos#358]
I am reffering to #59 

This makes type any because it is self referenced:

```
import { builder } from '../schema';
import Piece from './Piece';
import Arrangement from './Arrangement';

export default builder.loadableObject('Composer', {
  load: (ids: string[], ctx) => ctx.prisma.composer.findMany({ where: { id: { in: ids } } }),
  sort: (composer) => value.id,
  fields: (t) => ({
    id: t.exposeID('id', {}),
    firstName: t.exposeString('firstName'),
    lastName: t.exposeString('lastName'),
    fullName: t.string({ resolve: (parent, _args, _ctx) => parent.firstName + ' ' + parent.lastName }),
    slug: t.exposeString('slug'),
    bio: t.string({ resolve: async (parent, _args, ctx) => ctx.prismaTranslation(parent.bio) }),
    pieces: t.field({
      type: [Piece],
      resolve: async (parent, _args, ctx) => ctx.prisma.piece.findMany({ where: { composerId: parent.id }, orderBy: { createdAt: 'desc' } }),
    }),
    arrangements: t.field({
      type: [Arrangement],
      resolve: async (parent, _args, ctx) => {
        return ctx.prisma.arrangement.findMany({ where: { publishedAt: { not: null }, piece: { composerId: parent.id } }, orderBy: { publishedAt: 'desc' } });
      },
    }),
  }),
});
```

```
import { builder } from '../schema';
import { Context } from '../context';
import Composer from './Composer';
import Arrangement from './Arrangement';

export default builder.loadableObject('Piece', {
  load: (ids: string[], ctx: Context) => ctx.prisma.piece.findMany({ where: { id: { in: ids } } }),
  sort: (piece) => piece.id,
  fields: (t) => ({
    id: t.exposeID('id'),
    name: t.string({ resolve: async (parent, _args, ctx) => ctx.prismaTranslation(parent.name) }),
    slug: t.exposeString('slug'),
    description: t.string({ resolve: async (parent, _args, ctx) => ctx.prismaTranslation(parent.description) }),
    composer: t.field({
      type: Composer,
      resolve: async (parent, _args, ctx) => ctx.prisma.piece.findUnique({ where: { id: parent.id }, select: { composer: true }, rejectOnNotFound: true }).then((piece) => piece.composer),
    }),
    arrangements: t.field({
      type: [Arrangement],
      resolve: async (parent, _args, ctx) => {
        return ctx.prisma.arrangement.findMany({ where: { pieceId: parent.id, publishedAt: { not: null } } });
      },
    }),
  }),
});
```

When I use `ref` as suggested in #59 like this:

```
const Arrangement = builder.objectRef<Prisma.Arrangement>('Arrangement');

builder.loadableObject(Arrangement, {
  load: async (keys: string[], ctx: Context) => ctx.prisma.arrangement.findMany({ where: { id: { in: keys } } }),
  sort: (arrangement) => arrangement.id,
  fields: (t) => ({
    id: t.expose('id', { type: 'ID' }),
    difficulty: t.expose('difficulty', { type: 'Difficulty' }),
    numberOfPages: t.expose('numberOfPages', { type: 'Int', nullable: true }),
    audioPreviewDuration: t.expose('audioPreviewDuration', { type: 'Int' }),
    piece: t.field({
      type: Piece,
      resolve: async (parent, _args, _ctx) => ({ id: parent.pieceId }),
    }),
    composer: t.field({
      type: Composer,
      resolve: async (parent, _args, ctx) => {
        return ctx.prisma.arrangement
          .findUnique({ where: { id: parent.id }, select: { piece: { select: { composer: true } } }, rejectOnNotFound: true })
          .then((arrangement) => arrangement.piece.composer);
      },
    }),
    chords: t.field({
      type: [Chord],
      resolve: async (parent, _args, ctx) => {
        return ctx.prisma.chord.findMany({ where: { arrangements: { some: { id: parent.id } } } });
      },
    }),
  }),
});

export default Arrangement;
```

But I have a few issues with this aproach:

- I need to write type (`Prisma.Arrangement`) and in resolvers I need to write whole type
- But I can use type  `const Arrangement = builder.objectRef<{id: string}>('Arrangement');`, then types for extending are used from `load` method that is what is required, but in resolvers I have to return object like: `{id: piece.arrangementId}` instead of just `piece.arrangementId` - there is no possibilty to return just string that is case when just `loadableObject` is used instead of `ref`.

**Comment by hayes** [comment]
This is definitely not optimal.  Looked at it briefly, I think it should be relatively easy to add a builder.loadableObjectRef method that you can call implement on like normal objects.  This would take the load method (and other dataloader props) when creating the ref so you still get inference and don't have to provide any manual types.

Thanks for opening this issue! I'll try to get this implemented in the next couple days

**Comment by hayes** [comment]
@homoky still going to add the above solution, but another workaround is to add the circular reference field separately, basically just add the field that causes the issue with `builder.objectField('fieldName, t => t.field(...))`

**Comment by hayes** [comment]
Implemented a bunch of new ref logic for the dataloader plugin here: https://github.com/hayes/pothos/pull/74/commits/6778777316860a66213f211e899ea7af28f4e79d

Still need to write docs and tests, but its pretty close.  I'm going to try to get that finished up tomorrow

**Comment by hayes** [comment]
New version should be released with these changes.  Also added a new guide with some general docs on circular references.  Let me know if you run into any issues

**Comment by homoky** [comment]
I've tried the new dataloader and gotta say, it works better than I expected. I run into an issue I have no idea how to solve and I did not get it before without the resolver.

/schema/Piece.ts

```
import { builder } from '../schema';
import Composer from './Composer';
import Arrangement from './Arrangement';
import { Piece, Prisma } from '@~internal/prisma';
import { Context } from '../context';
import { SetRequired } from 'type-fest';

export const include: SetRequired<Prisma.PieceInclude, 'arrangements' | 'composer'> = {
  composer: { select: { id: true } },
  arrangements: { select: { id: true }, where: { publishedAt: { not: null } } },
};

const Piece = builder.loadableObjectRef('Piece', {
  load: (ids: string[], ctx: Context) =>
    ctx.prisma.piece.findMany({
      where: { id: { in: ids } },
      include,
    }),
  sort: (object) => object.id,
});

builder.objectType(Piece, {
  fields: (t) => ({
    id: t.exposeID('id'),
    name: t.string({ resolve: async (parent, _args, ctx) => ctx.prismaTranslation(parent.name) }),
    slug: t.exposeString('slug'),
    description: t.string({ resolve: async (parent, _args, ctx) => ctx.prismaTranslation(parent.description) }),
    composer: t.field({
      type: Composer,
      resolve: async (parent, _args, _ctx) => parent.composerId,
    }),
    arrangements: t.field({
      type: [Arrangement],
      resolve: async (parent, _args, _ctx) => parent.arrangements.map((arrangement) => arrangement.id),
    }),
  }),
});

export default Piece;
```

schema/Arrangement.ts

```
import { Arrangement, Prisma } from '@~internal/prisma';
import { builder } from '../schema';
import Piece from './Piece';
import Composer from './Composer';
import Chord from './Chord';
import { Context } from '../context';
import { SetRequired } from 'type-fest';

export const include: SetRequired<Prisma.ArrangementInclude, 'chords' | 'piece'> = {
  chords: { orderBy: { order: 'asc' } },
  piece: true,
};

const Arrangement = builder.loadableObjectRef('Arrangement', {
  load: (ids: string[], ctx: Context) =>
    ctx.prisma.arrangement.findMany({
      where: { id: { in: ids } },
      include,
    }),
  sort: (object) => object.id,
});

builder.objectType(Arrangement, {
  fields: (t) => ({
    id: t.expose('id', { type: 'ID' }),
    difficulty: t.expose('difficulty', { type: 'Difficulty' }),
    numberOfPages: t.expose('numberOfPages', { type: 'Int', nullable: true }),
    audioPreviewDuration: t.expose('audioPreviewDuration', { type: 'Int' }),
    piece: t.field({
      type: Piece,
      resolve: async (parent, _args, _ctx) => parent.piece.id,
    }),
    composer: t.field({
      type: Composer,
      resolve: async (parent, _args, _ctx) => parent.piece.composerId,
    }),
    chords: t.field({
      type: [Chord],
      resolve: async (parent, _args, _ctx) => parent.chords,
    }),
  }),
});

export default Arrangement;
```

/schema.ts

```
import SchemaBuilder from '@pothos/core';
import DataloaderPlugin from '@pothos/plugin-dataloader';
import { Context } from './context';
import { Difficulty } from '@~internal/prisma';

type Builder = {
  Context: Context;
  Scalars: {
    Difficulty: {
      Input: Difficulty;
      Output: Difficulty;
    };
    ID: {
      Input: string;
      Output: string;
    };
  };
  DefaultInputFieldRequiredness: true;
};

export const builder = new SchemaBuilder<Builder>({
  defaultInputFieldRequiredness: true,
  plugins: [DataloaderPlugin],
});

builder.queryType({});

import './schema/Piece';
import './schema/Arrangement';

export default builder.toSchema({});
```

When I open the graphql endpoint, it shows:

<img width="959" alt="Screen-Shot-2022-04-10-07-56-49 71" src="https://user-images.githubusercontent.com/893917/162604457-eaaa4968-e66c-417f-800b-ceac7185d959.png">

I would say that imports are from my standpoint one of the most complicated things for beginers for Pothos when they want to structure their schema and resolver files, because they run in this kind of issues and can stoped them from trying Pothos.

It would be great, not knowing if possible for providing folder paths to Schema builder and Pothos could self resolve all files.

**Comment by hayes** [comment]
@homoky This should be very easy to fix (If the issue I see is actually what is causing the issue).  You just need to split up you schema file into builder.ts (setup and export the builder) and then schema.ts just handles the imports and toSchema call:

builder.ts:
```ts
import SchemaBuilder from '@pothos/core';
import DataloaderPlugin from '@pothos/plugin-dataloader';
import { Context } from './context';
import { Difficulty } from '@~internal/prisma';

type Builder = {
  Context: Context;
  Scalars: {
    Difficulty: {
      Input: Difficulty;
      Output: Difficulty;
    };
    ID: {
      Input: string;
      Output: string;
    };
  };
  DefaultInputFieldRequiredness: true;
};

export const builder = new SchemaBuilder<Builder>({
  defaultInputFieldRequiredness: true,
  plugins: [DataloaderPlugin],
});

builder.queryType({});
```

schema.ts
```ts
import './schema/Piece';
import './schema/Arrangement';

export default builder.toSchema({});
```

This avoids the cycle `schema -> Arragment -> schema (builder import)` by making the imports `schema -> aragment -> builder`.  As long as schema and builder are not a part of a cyclic import the other files can all reference each other as much as they want and it should all just work, Pothos already has a LOT of internal logic that tries to ensure that these kinds of issues don't cause problems.  Automatically importing files based on some path pattern probably wouldn't work very well, and would be hard to build in a way that works for everyones setup.

I could probably document this requirement (builder should be defined in a file that does not import anything that uses the builder, and toSchema should be called in a file that is not imported by anything that uses the builder.  Other than that, everything else should be okay.  

I have the basic pattern described here: https://pothos-graphql.dev/docs/guide/app-layout But not the actual reasoning behind why this is the pattern that works best.

**Comment by homoky** [comment]
Thanks for reply.

Yes you are absulutely right. It would be great, if users could find it in documentation. I tried your proposed solution and it works, build is ok and some basic queries runs (not the subfields):


```
import builder from '../builder';
import Piece from './Piece';
import Arrangement from './Arrangement';
import { Context } from '../context';
import { SetRequired } from 'type-fest';
import { Prisma } from '@~internal/prisma';

export const include: SetRequired<Prisma.ComposerInclude, 'pieces'> = {
  pieces: { orderBy: { createdAt: 'desc' } },
};

const Composer = builder.loadableObjectRef('Composer', {
  load: async (ids: string[], ctx: Context) => {
    console.log('composer dataloader', ids);

    return ctx.prisma.composer.findMany({
      where: { id: { in: ids } },
      include,
    });
  },
});

builder.objectType(Composer, {
  fields: (t) => ({
    id: t.exposeID('id'),
    firstName: t.exposeString('firstName'),
    lastName: t.exposeString('lastName'),
    fullName: t.string({ resolve: (parent, _args, _ctx) => parent.firstName + ' ' + parent.lastName }),
    slug: t.exposeString('slug'),
    bio: t.string({ resolve: async (parent, _args, ctx) => ctx.prismaTranslation(parent.bio) }),
    pieces: t.field({
      type: [Piece],
      resolve: async (parent, _args, _ctx) => parent.pieces.map((piece) => piece.id),
    }),
    arrangements: t.field({
      type: [Arrangement],
      resolve: async (parent, _args, ctx) => {
        console.log({ parent });
        return ctx.prisma.arrangement
          .findMany({ where: { publishedAt: { not: null }, piece: { composerId: parent.id } }, orderBy: { publishedAt: 'desc' } })
          .then((arrangements) => arrangements.map((arrangement) => arrangement.id));
      },
    }),
  }),
});

export default Composer;
``

When I return string with `composer` ID in parent of subfields obejct I get the ID, not object. It seems that the load function is never called (no console.log in the console). Only I one get is: 

```
{ parent: 'ckxqo9z9d00192lhoqoyyfti9' }
```

**Comment by hayes** [comment]
@homoky thats weird, how are you defining the field that returns the composer id?  Just tried to reproduce the issue, but it was working correctly for me.

**Comment by hayes** [comment]
One issue I do see (I don't think this is the issue you are running into though) is that your load method does a findMany that will NOT return the Composers in the right order.  Without a sort, this will mean that the composers that get referenced may be the wrong ones.  using the `sort` option is probably the easiest way to fix that.

**Comment by hayes** [comment]
Looks like you are also returning ids for `arrangements` and `pieces` do those loadableRefs work, or are they all not working?

**Comment by homoky** [comment]
I tried using sort method, but in the process I removed it before I posted the snippets here.

I used `sort: (composer)=> composer.id`.

**Comment by homoky** [comment]
> Looks like you are also returning ids for `arrangements` and `pieces` do those loadableRefs work, or are they all not working?

Yes. Same effect everywhere.

**Comment by hayes** [comment]
@homoky figured out the issue, working on a fix.  Basically there is some inconsistency between how `ref.implement` vs `builder.objectType(ref)` works, and I wasn't properly testing all the combinations.  I'll try to get a fix up in the next hour or so

**Comment by hayes** [comment]
Fix should be published now

**Comment by hayes** [comment]
Here is the simplified example I was using to test, this was not working on the previous version of the Pothos, so I think this should fix your issue: https://stackblitz.com/edit/typescript-k3vn7z?file=index.ts

Sorry it took a while to get this right.

**Comment by homoky** [comment]
Thanks hayes. I can confirm it works now. Let's close this issue.
