### ISSUE TITLE
Duplicate field definition for field constructor in Query

### ISSUE THREAD

**Issue by marceloverdijk** [hayes/pothos#363]
I'm trying to migrate a project to Pothos but one query field is giving me problems...

Below definition

```
    constructor: t.prismaField({
      type: 'Constructor',
      nullable: true,
      args: {
        id: t.arg.string({ required: true }),
      },
      resolve: (query, _root, args) => 
        prisma.constructor.findUnique({
          ...query,
          where: { id: String(args.id) }
        }),
    }),
```

gives the following error:

    Error: Duplicate field definition for field constructor in Query

The `constructor` field is not defined twice by myself -- I've verified that.

Is it maybe that `constructor` is also used by javascript/typescript itself?

I also tried with:

```
    'constructor': t.prismaField({
      type: 'Constructor',
      ..
    }),
```

but it gives the same error.

I cannot change the field name as the schema is already used... the migration to Pothos should deliver the same schema.
Is there any workaround I could do?

**Comment by hayes** [comment]
This is probably because constructor is a default property of any object, I'll look at getting this fixed later today

**Comment by hayes** [comment]
Should be fixed in the latest release (merged to main, should be published in the next couple minutes).  Let me know if you run into any more issues.

**Comment by marceloverdijk** [comment]
Thx Michael for the swift reply, fix and release. Very much appreciated and I can confirm it works now.
