### ISSUE TITLE
[WithInput] global required option

### ISSUE THREAD

**Issue by Jomik** [hayes/pothos#365]
Setting `required` to false for the input arg is correctly reflected in the schema, but the resolver types will still think it is required.

```ts
export const builder = new SchemaBuilder<{
  Context: Context;
}>({
  plugins: [WithInputPlugin],
  withInput: {
    argOptions: {
      required: false,
    },
  },
});
```
We are also unable to change it on a per-field basis:
![image](https://user-images.githubusercontent.com/699655/162764455-05844187-9d2e-4a37-8e1d-de424739059e.png)

**Comment by hayes** [comment]
Should be fixed now, added an update to the docs that describes how to do this.
