### ISSUE TITLE
Federation Plugin not adding directives to SDL

### ISSUE THREAD

**Issue by YElyousfi** [hayes/pothos#382]
I followed the example of extending an external entity [here](https://pothos-graphql.dev/docs/plugins/federation) however,  during supergraph composition, the gateway complains that the extension doesn't have an `@key` defined. In fact, none of the directives such as `@external` are added to the sdl. I confirmed this via the _service query below.

```graphql
query IntrospectionQuery {
  _service {
    sdl
  }
}
```

I managed to get the gateway to  recognize the directives after passing the output of `toSubgraphSchema` into the function provided by [graphql-transform-federation](https://www.npmjs.com/package/graphql-transform-federation) and defining the directives myself like below. 

```typescript
import { transformSchemaFederation } from 'graphql-transform-federation'
// ...
export const schema = transformSchemaFederation(builder.toSubGraphSchema({}), { /* directives specified here */ })
```

I know this defeats the purpose of the plugin but I wasn't sure what else to do. Running the same query above using this approach outputs the sdl with specified directives.

This project is awesome btw!

**Comment by hayes** [comment]
Interesting, any chance you could provide a reprouction.  I've tested this on a couple examples I have, and the directives do show up correctly for me when running

```graphql
query IntrospectionQuery {
  _service {
    sdl
  }
```

I assume there is some difference in the versions of dependencies we are using.    Just to confirm, you do have the directives plugin set up as well correct? (Sharing your builder setup may also help me reproduce the issue).


Sorry it took me a few days to get back to you on this, been a busy week.

**Comment by hayes** [comment]
Just seeing that the directive plugin is missing from the federation plugin instructions, but it is definitely required.  Try adding the directive plugin and see if that fixes your problem.

**Comment by YElyousfi** [comment]
> Just seeing that the directive plugin is missing from the federation plugin instructions, but it is definitely required.  Try adding the directive plugin and see if that fixes your problem. 

This was exactly the issue! Works flawlessly. Thank you 🎉

**Comment by hayes** [comment]
Updated the docs, thanks for reporting this!
