### ISSUE TITLE
Create a reusable connection edge type with Relay plugin

### ISSUE THREAD

**Issue by willianhf** [hayes/pothos#383]
It would be nice if the plugin let us create or even access the connection edge type.
I thought the API could be something like the following:
```typescript
const ThingsEdge = builder.connectionEdge({ type: SomeThing });
const ThingsConnection = builder.connectionObject({ edge: ThingsEdge });

// or maybe access it
const ThingsConnection = builder.connectionObject({ type: SomeThing });
const ThingsEdge = ThingsConnection.edge();
```

I don't know if it's possible to implement like this, so it's just a suggestion.

**Comment by hayes** [comment]
Thanks for opening this issue. 

This is probably something that should be supported, I can't give a definite timeline, but I'll try to look into the some when I have a some more time in next couple weeks.

**Comment by hayes** [comment]
This should be supported now.  Sorry it took a while to get implemented.  The edge objects created automatically are not exported, but if you can now create an edge object directly and pass in a ref to that edge object when creating a connection or a connectionObject 

https://pothos-graphql.dev/docs/plugins/relay#reusing-edge-objects
