### ISSUE TITLE
Prisma plugin: function as select does not work correctly

### ISSUE THREAD

**Issue by fehnomenal** [hayes/pothos#385]
First of all thanks for this great library, I really enjoy using it.

I am building a shop and want to display how many of the items the user placed into their cart. I need to use a select function to filter for the cart id (which is in the context object):
```ts
    inCart: t.int({
      select: (_args, { activeCartId }) => ({
        inCarts: {
          where: {
            cart: {
              id: activeCartId,
              order: null,
            },
          },
        },
      }),
      resolve: (product) => {
        return product.inCarts.reduce((acc, { amount }) => acc + amount, 0);
      },
    }),
```

At least that's what I want to have because prisma does not like the generated query:
```
Invalid `prisma.product.findUnique()` invocation:

{
  inCarts: {
  ~~~~~~~
    where: {
      cart: {
        id: 'cl2jxcuuy000003vdhtwsgqb9',
        order: null
      }
    }
  },
  where: {
    externalId: '1600927231'
  }
}

Unknown arg `inCarts` in inCarts for type Product. Did you mean `where`? Available args:
type findUniqueProduct {
  where: ProductWhereUniqueInput
}
```

If I use a plain function with the id hardcoded (or without, whatever) the query is generated correctly. Also as a function the typings seem off because typescript complains about `inCarts` not existing.

Now the fun thing: when I follow prisma's complaint and wrap the return of `select()` with `select:{...}` then it works but of course typescript is not happy with `select()`'s signature.

So, without diving too deeply into the code, it seems to me that the `select: {...}` wrapper is missing if `select` is a function.

**Comment by hayes** [comment]
Yup, I see the issue.  I completely forgot to test selects defined with a function like that.  Looks like a really easy fix.  I can probably get something together tomorrow

**Comment by fehnomenal** [comment]
https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/tests/example/schema/more.ts has a select defined with a function but maybe it is not used for the tests?

**Comment by fehnomenal** [comment]
If I extract the select function (like linked above) then the typings are correct again. So scratch that.

**Comment by hayes** [comment]
I don't think that file gets used in any tests.

The changes needed to fix this are here: https://github.com/hayes/pothos/pull/384/files#diff-a87c7ba5891f0b94999ac5d7810dd583f8d2727221320a155f06ba7f331ccd9f

**Comment by hayes** [comment]
Just merged a fix for this, should be published in the next few minutes

**Comment by hayes** [comment]
let me know if you are still running into any issues after upgrading

**Comment by fehnomenal** [comment]
Works perfectly, good work!
