### ISSUE TITLE
VS Code can't find nested types with prisma plugin

### ISSUE THREAD

**Issue by felixhaeberle** [hayes/pothos#398]
Hey, thanks for providing this great library, I really like it!!

I have a problem with the generated types, a few nested Prisma types doesn't get recognized by VS Code.

This is the following output:

```
The namespace ""/Users/felixhaberle/Desktop/git/project/node_modules/.prisma/client/index".Prisma" doesn't have an exported member "UserWhereUniqueInput".ts(2694)
```

I have already deleted node modules, reinstalled all libraries, and checked my node version which is v14.17.0 – still the same error.

Do you know what can help in such a case? Thank you very much!!

**Comment by felixhaeberle** [comment]
Nevermind, I fixed it with looking into the VS Code settings, there was a custom Typescript reference. When I removed that reference, the problem was gone. Thanks very much!

**Comment by hayes** [comment]
glad you got it figured out!
