### ISSUE TITLE
Relay globalID doc example doesn't seem to work

### ISSUE THREAD

**Issue by nicolascvoodoo** [hayes/pothos#403]
Hi,

I am investigating Pothos for our project and I am trying to make the relay plugin work.

 In the documentation, it is said that we can return the global ID in the following format: `{ type: "MyType", id: "123"}`. But I get an error.

Here is the code:

```typescript
builder.queryType({
  fields: (t) => ({
    workingSingleId: t.globalID({
      resolve: (parent, args, context) => {
        return encodeGlobalID('SomeType', 123);
      },
    }),
    workingListOfIds: t.globalIDList({
      resolve: (parent, args, context) => {
        return [encodeGlobalID('Foo', '123'), encodeGlobalID('Foo', '234')];
      },
    }),
    crashedSingleId: t.globalID({
      resolve: (parent, args, context) => {
        return { id: 123, type: 'SomeType' };
      },
    }),
    creashedListOfIds: t.globalIDList({
      resolve: (parent, args, context) => {
        return [{ id: 123, type: 'SomeType' }];
      },
    }),
});
```

Here is the query:

```graphql
query ExampleQuery {
  workingListOfIds
  workingSingleId
  crashedSingleId
  creashedListOfIds
}
```

And here is the error:

```graphql
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "crashedSingleId"
      ]
    }
  ],
  "data": null
}
```

BTW, how can we get a more meaningful error message (like stack trace)? The console displays nothing about this error.

Thanks you for your time.

**Comment by hayes** [comment]
Errors are probably hidden by whatever server you are using (eg yoga does this: https://www.graphql-yoga.com/docs/features/error-masking)

The issue you are running into is that when you return a global ID like that it expects that type to exist.  See https://stackblitz.com/edit/typescript-ci9ki9?file=index.ts,tsconfig.json  

If you comment out the SomeType definition, you should see the error you are running into.

**Comment by nicolascvoodoo** [comment]
Thank you for your quick answer. Very clear. It seems to be a better practice to not use `encodeGlobalID` with `t.globalID` as `encodeGlobalID` doesn't do the type checking.

Good job btw! I'm impressed by Pothos 👍
