### ISSUE TITLE
Add `prismaFieldWithInput`

### ISSUE THREAD

**Issue by screfy** [hayes/pothos#408]
It would be nice to have the `prismaFieldWithInput`  method when is With-Input plugin installed.

Something like this:

```ts
builder.mutationField('updateUser', (t) =>
  t.prismaFieldWithInput({
    type: 'User',
    input: {
      displayName: t.input.string({ required: false })
    },
    resolve: () => { ... }
  })
);
```

**Comment by hayes** [comment]
Definitely on my list of things to do, should have some time for this pretty soon, sorry its taken me a while to get around to it.

**Comment by hayes** [comment]
just released a new version that has support for this

**Comment by RIP21** [comment]
> just released a new version that has support for this

Legend!
