### ISSUE TITLE
[plugin-prisma] Upcoming rename of `@prisma/sdk` to `@prisma/internals` with Prisma 4

### ISSUE THREAD

**Issue by janpio** [hayes/pothos#423]
Hey,

Jan from Prisma Engineering here.
 
Quick heads up that we will soon rename our `@prisma/sdk` package to `@prisma/internals` with Prisma 4, which we plan to release on June 28th (soon!). 

The `@prisma/sdk` package was meant as an Prisma internal package only, but somehow it leaked out over time and is now used across all kinds of tools - including yours of course 😄

With the rename of the Npm package we want to make it clearer that we can not give any API guarantees for `@prisma/internals`, might need to introduce breaking changes to the API from time to time and will not follow semantic versioning (breaking changes only in major upgrade) with it. We think that it is better communicated with `internals` than with `sdk`.
With Prisma 4, besides the package name nothing should change though.

Additionally it would be super helpful if you could help us gain an understanding where, how and why you are using `@prisma/sdk` (soon `@prisma/internals`, remember 😀) to achieve, what exactly. We want to cleanup that package and your feedback will be valuable to us to define a better API.

Looking forward to your feedback.

Best
Jan & your friends at Prisma

PS: Are you using `Prisma.dmmf` from `import { Prisma } from '@prisma/client'` in your code somewhere by chance? That will also change soon and not include the `Prisma.dmmf.schema` sub property. Instead you can use `getDmmf` from `@prisma/internals` moving forward.

**Comment by hayes** [comment]
Hey, thanks for reaching out!

It doesn't look like I am using `@prisma/sdk` anywhere, which is good.

I am using parts of the `dmmf` data though.  Pothos currently does not load the dmmf data directly, instead it grabs it from a private property of the client (`pirsmaClient._dmmf`).   The prisma generator also uses dmmf data passed in to the generator api (using `@prisma/generator-helper`) 

pothos uses `dmmf.datamodel` in it's prisma generator script and `dmmf.modelMap` at runtime.

Is there a pre-release version I can test with to make sure

**Comment by hayes** [comment]
If I'm reading this correctly, _dmmf is still available on client instances here: https://github.com/prisma/prisma/commit/a91a4d0ef01153cf3e94072dd0c4271b75fb64b0#diff-09784fc0113a735572cff48990efa35434fb6ec6ec8876845ec9cf423642e5fdR1063?

**Comment by hayes** [comment]
Oh, actually, looks like _dmmf is now loaded when connecting, and there is a new _baseDmmf that is available immediately?

**Comment by millsp** [comment]
Yes, that's correct. The `_baseDmmf` has the bare minimum information for us to be able to do `prisma.<model>.<method>`. `_dmmf` is the full one, and includes the type information used for generation or input validation. Right now that one is computed on the very first query and it is asynchronous. If it can help, we can also load it on `$connect`?

**Comment by hayes** [comment]
skimming through the implementation it looks like the baseDmmf has everything pothos needs at runtime, which is good, having to do something async would be challenging.  Pothos really just needs to know about what relations exist on each model, and which fields are either unique or part of a unique index, both of which look like are available in the base dmmf.  I'll need to actually test this, but I *think* everything should just work if I move over to _baseDmmf, and backwards compatiblity should be easy by just falling back to _dmmf if that doesn't exist.

**Comment by hayes** [comment]
I think the only required change should be this: https://github.com/hayes/pothos/pull/424

Looks like this change hasn't been merged or released as a snapshot version yet, but I can test to make sure its all working correctly once that change lands.

**Comment by Jolg42** [comment]
@hayes You could try prisma packages on the `dev` tag on npm, like `@prisma/internals@3.16.0-dev.84`

**Comment by hayes** [comment]
thanks! Just merged that change, so Pothos should be ready for prisma@4 when it releases

**Comment by Jolg42** [comment]
@hayes Prisma 4.0.0 was published on Tuesday :canoe: 

The internal package `@prisma/sdk`
- was published for the last time to ease the upgrade (in the future we might reuse the package name, but its content will be different)
- marked deprecated on npm
- available under the new, more explicit package name `@prisma/internals`.

If you know people affected by this, feel free to point them to this [GitHub discussion](https://github.com/prisma/prisma/discussions/13877).
It will help us understand where, how, and why people are using it, so we can define a better API.
