### ISSUE TITLE
Nullability: Object field list

### ISSUE THREAD

**Issue by lbozzo** [hayes/pothos#435]
Hello, I'm trying out the pothos. Amazing creation. I stumbled upon a TS error and I tried to find a solution but I'm a bit lost on the type definition. Trying to specify the nullability inside an object implementation only allows `boolean | undefined`. 

**Code:** 
```ts
const builder = new PothosBuilder({});

type User = {
  posts: Post[];
};

type Post = {
  title: string;
};

const PostObject = builder.objectRef<Post>("Post").implement({
  fields: (t) => ({
    title: t.expose("title", { type: "String" }),
  }),
});

const UserObject = builder.objectRef<User>("User").implement({
  fields: (t) => ({
    posts: t.expose("posts", {
      type: [PostObject],
      nullable: { list: true, items: true },
    }),
  }),
});
```
**Error:** 
```error TS2322: Type '{ list: true; items: true; }' is not assignable to type 'boolean | undefined'.```

**Workaround**
```ts
...
 nullable: { list: true, items: true } as any,
...
```
Expected outcome:
![image](https://user-images.githubusercontent.com/6489448/176173154-728c9f32-beb9-4c2e-be4e-6ffd4d008d56.png)

**Comment by hayes** [comment]
Thanks for reporting this.  Should be easy to fix

**Comment by hayes** [comment]
This should be fixed in the latest release, let me know if you have an more issues with this after upgrading!

**Comment by lbozzo** [comment]
Thank you very much @hayes. That was very fast, amazing. I can confirm it's fixed.👍
