### ISSUE TITLE
[plugin-relay] nodeTypeOptions is of type ObjectTypeOptions instead of InterfaceTypeOptions

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#436]
I expected the type of `relayOptions.nodeTypeOptions` to be `InterfaceTypeOptions` instead of `ObjectTypeOptions`, because it configures the `Node` **interface**.
I noticed this, when adding a required property to `ObjectTypeOptions` in a plugin and TypeScript started to complain, that I did not define this property in `relayOptions.nodeTypeOptions`.

**Comment by hayes** [comment]
This is a bug.  I'll get a fix out soon! Thanks for reporting

**Comment by hayes** [comment]
This should be fixed in the latest release, let me know if you have an more issues with this after upgrading!

**Comment by P4sca1** [comment]
I can confirm that this issue has been fixed. Thank you!
