### ISSUE TITLE
[plugin-prisma/relay] t.relatedConnection is missing typings for relay arguments

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#437]
The issue is best shown by a small code snippet. Note the comments In `complexity` and `args`. It works fine when using `t.prismaConnection` in the query type.

```ts
// ... (in builder.prismaNode fields definition)
sessions: t.relatedConnection('sessions', {
	description: 'The sessions of the user.',
	cursor: 'id',
	complexity: (args) => ({
		field: 10,
                // ERROR HERE: args only includes orderBy, but not first, last, after, and before
		multiplier: args.first ?? args.last ?? 20, 
	}),
	args: {
		orderBy: t.arg({
			type: SessionOrder,
			defaultValue: {
				field: SessionOrderField.LAST_ACTIVIY,
				direction: OrderDirection.ASC,
			},
		}),
	},
	query: (args) => ({
                // Here, args also only includes orderBy, but not first, last, after, and before
		orderBy: convertOrderBy(args.orderBy),
	}),
	totalCount: true,
}),
// ...
```

**Comment by hayes** [comment]
Yup, connection args should definitely be included there, this should be relatively straight forward to fix.

**Comment by hayes** [comment]
This should be fixed in the latest release, let me know if you have an more issues with this after upgrading!

**Comment by P4sca1** [comment]
Relay connection arguments are now fully typed in the `complexity` function. Thank you for the quick fix! 🥳

**Comment by P4sca1** [comment]
@hayes I noticed, that the fix does not work when not adding any extra arguments. In this case, you have to add `args: {}` to the options of `t.relatedConnection`.
