### ISSUE TITLE
[plugin-prisma/relay] Error in full select mode when not selecting anything from node

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#439]
When you have defined a prisma node with full select mode (`select: {}`) and then have defined a `t.prismaConnection` for this node, queries throw an error when nothing from node is selected: `The select statement for type X must not be empty.`

Sample query that fails:
```gql
query {
  myPrismaConnection {
    totalCount
    edges {
      cursor
    }
  }
}
```

Some ideas:
* Don't run the resolver defined in `t.prismaConnection` at all, when no fields from `node` are selected. I don't know if this is possible, there might be other side-effects that I am not aware of right now (e.g. you have to load nodes in order to calculate the cursor).
* Always add the cursor field, defined in `t.prismaConnection` to the selection set
* Always add the id field, defined in `t.prismaNode` to the selection set

**Comment by hayes** [comment]
This should be fixed in the latest release, let me know if you have an more issues after upgrading!

**Comment by P4sca1** [comment]
The query no longer throws errors, but only the id is selected instead. Thanks again for the quick fix :)

**Comment by hayes** [comment]
Slight clarification here, the selection for this case is now the cursor field (or fields in case the cursor is a compound index).  This will give us enough information to calculate cursors and pageInfo.
