### ISSUE TITLE
[plugin-relay] Add defaultConnectionTypeOptions and defaultEdgeTypeOptions

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#441]
It would be great if there was a type-safe way to apply object type options to all automatically created `Connection` and `Edge` types.

**Background:**
I use a modified version of your `graphql-shield` plugin and configured it so that everything is denied by default and needs to be explicitly allowed. To not forget this, I made the `shield` attribute on object types non-optional.
This means that I have to explicitly set `shield: allow` on every `Connection` and `Edge` object type when using `prismaConnection` or `relatedConnection`.

**Comment by hayes** [comment]
Added `defaultConnectionTypeOptions` and `defaultEdgeTypeOptions` in relayOptions
