### ISSUE TITLE
[plugin-complexity] Custom errors

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#447]
Some GraphQL server implementation default to masking errors in production. Because of this, complexity related errors just return an internal server error. 2 popular examples include GraphQL Yoga (https://www.graphql-yoga.com/docs/features/error-masking) and Apollo Server.
It would be great if there was a way to customise the error that is returned. I have 3 new config options in my mind:

* `maxDepthError(maxDepth: number, actualDepth: number): Error`
* `maxBreadthError(maxBreadth: number, actualBreadth: number): Error`
* `maxComplexityError(maxComplexity: number, actualComplexity: number): Error`

Naming can be changed, but the general idea is that you can return another error, like `GraphQLYogaError`, `EnvelopError`, or `ForbiddenError`, so that it is exposed to the client.

**Comment by hayes** [comment]
Yup, we definitely should add that.  I added something similar for the authorization plugin a while back, which might be a good reference for how this API could work, but the requirements might be slightly different.

**Comment by hayes** [comment]
Added a new option for this in the latest version: https://pothos-graphql.dev/docs/plugins/complexity#options
