### ISSUE TITLE
Add complexity score as part of extensions

### ISSUE THREAD

**Issue by mmahalwy** [hayes/pothos#457]
With Apollo, an extension object can be part of the results. It'd be great if the complexity score is returned as opposed to only returned when a failure happens.

**Comment by hayes** [comment]
Pothos doesn't handle the execution of queries, so it can't directly add things to extensions.  Would be pretty easy to provide an API that lets you get the complexity of the current request though, and provide some examples of how use that to add it to extensions in a couple of the common libraries

**Comment by hayes** [comment]
Added here: https://pothos-graphql.dev/docs/plugins/complexity#complexityfromqueryquery-options

**Comment by mmahalwy** [comment]
Sorry, killin you here. How to add `extensions` to the response with pothos? Ideally, Id use this utility in dev to add that score to extensions for developers to see.

**Comment by hayes** [comment]
Short answer is you don't.  As mentioned above, Pothos really only defines the schema and it's resolvers.  Extensions are something that is generally added by the server implementation (apollo, yoga, etc).  response extensions don't really exist during the execution phase of a GraphQL request. 

For yoga this might look something like:

```ts
import {
  createServer,
  handleStreamOrSingleExecutionResult,
  OnExecuteDoneEventPayload,
} from '@graphql-yoga/node';
import { schema } from './schema';

const server = createServer({
  schema,
  plugins: [
    {
      onExecute: () => ({
        onExecuteDone: (payload: OnExecuteDoneEventPayload<{}>) =>
          handleStreamOrSingleExecutionResult(
            payload,
            ({ result, args: { contextValue, variableValues, document } }) => {
              result.extensions = {
                ...result.extensions,
                complexity: complexityFromQuery(document, {
                  variableValues,
                  context: contextValue,
                }),
              };
            },
          ),
      }),
    },
  ],
});
```

Not sure if that is fully correct, haven't tested it myself.
