### ISSUE TITLE
Troubleshooting slowness?

### ISSUE THREAD

**Issue by mmahalwy** [hayes/pothos#458]
We're experiencing huge slowdown as of recent and trying to figure out how to troubleshoot pothos' parsing, response and validation timing.

Thoughts?

**Comment by hayes** [comment]
pothos doesn't do any parsing, that is all handled by what ever server implementation you are using.  Response timing is pretty vague, but you could look into the tracing plugin to get insight into what resolvers are slowing things down.  Validation is a little trickier, and I don't know of an easy way to measure validation timing.  It would probably be pretty easy to add some sort of hook or callback for this.

 When you say huge slowdown what are you actually measuring.  Was this related to upgrading pothos, just adding new features or something else?

**Comment by hayes** [comment]
This may be relevant: https://github.com/n1ru4l/envelop/issues/1248

**Comment by hayes** [comment]
okay, sounds like this is probably unrelated to pothos then, going to close this for now
