### ISSUE TITLE
[plugin-prisma] Type issue in SchemaBuilder

### ISSUE THREAD

**Issue by Pasi-D** [hayes/pothos#462]
I'm getting this type error when setting up the builder.
```
Argument of type '{ plugins: "prisma"[]; prisma: { client: PrismaClient<Prisma.PrismaClientOptions, never, Prisma.RejectOnNotFound | Prisma.RejectPerOperation>; }; }' is not assignable to parameter of type 'RemoveNeverKeys<SchemaBuilderOptions<ExtendDefaultTypes<{ PrismaTypes: PrismaTypes; }>>>'.
  Property 'notStrict' is missing in type '{ plugins: "prisma"[]; prisma: { client: PrismaClient<Prisma.PrismaClientOptions, never, Prisma.RejectOnNotFound | Prisma.RejectPerOperation>; }; }' but required in type 'RemoveNeverKeys<SchemaBuilderOptions<ExtendDefaultTypes<{ PrismaTypes: PrismaTypes; }>>>'.ts(2345)
```

Following is my code snippet

```typescript
import SchemaBuilder from "@pothos/core";
import { PrismaClient } from "@prisma/client";
import PrismaPlugin from "@pothos/plugin-prisma";

import type PrismaTypes from "@pothos/plugin-prisma/generated";

const prisma = new PrismaClient({});

const builder = new SchemaBuilder<{
    PrismaTypes: PrismaTypes;
}>({
    plugins: [PrismaPlugin],
    prisma: {
        client: prisma
    }
});
```

However if I add the `notStrict` property as follows it won't show up. 
I haven't enabled `strict` mode in `tsconfig.json`

```typescript
...

const builder = new SchemaBuilder<{
    PrismaTypes: PrismaTypes;
}>({
    plugins: [PrismaPlugin],
    prisma: {
        client: prisma
    },
    notStrict:
        "Pothos may not work correctly when strict mode is not enabled in tsconfig.json"
});
...
```

Using

```package.json
"@pothos/core": "^3.12.2",
"@pothos/plugin-prisma": "^3.13.2",
"@prisma/client": "^3.15.1",
```

**Comment by hayes** [comment]
This is expected behavior.  Basically it's a warning that if you do not enable strict mode in tsconfig some features of Pothosay not work correctly.  Enabling strict mode is encouraged, but just adding the notStrict option as you have it is also okay.

**Comment by nickmartinwebdev** [comment]
I'm also getting a similar issue with my schema builder setup. I feel like this could be a recent issue as I set up Pothos with PrismaPlugin about a week ago with same requirements and had no error.


Error im getting in the below code snippet is **Type 'typeof PrismaPlugin' is not assignable to type '"prisma"'.ts(2322)**

```
import SchemaBuilder from "@pothos/core";
import { PrismaPlugin } from "@pothos/plugin-prisma";

import db from "./db";
import type PrismaTypes from "@pothos/plugin-prisma/generated";

export const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes;
}>({
  plugins: [PrismaPlugin],
  prisma: {
    client: db.prisma,
  },
});
```

using 
`   "@pothos/core": "^3.12.2",
    "@pothos/plugin-prisma": "^3.13.2",
    "@prisma/client": "^4.0.0"`

**Comment by nickmartinwebdev** [comment]
When I start the server I get this run time error also which I assume is related

Error: No plugin named class PrismaPlugin extends _core.BasePlugin {
    onOutputFieldConfig(fieldConfig) {
        if (fieldConfig.kind === 'PrismaObject' && fieldConfig.pothosOptions.select) {
            const { select  } = fieldConfig.pothosOptions;
            return {
                ...fieldConfig,
                extensions: {
                    ...fieldConfig.extensions,
                    pothosPrismaSelect: typeof select === 'function' ? (args, ctx, nestedQuery)=>({
                            select: select(args, ctx, nestedQuery)
                        }) : select
                }
            };
        }
        return fieldConfig;
    }
    wrapResolve(resolver, fieldConfig) {
        var ref, ref1, ref2, ref3;
        if (fieldConfig.kind !== 'PrismaObject' || !((ref = fieldConfig.extensions) === null || ref === void 0 ? void 0 : ref.pothosPrismaSelect)) {
            return resolver;
        }
        const parentConfig = this.buildCache.getTypeConfig(fieldConfig.parentType, 'Object');
        const loadedCheck = (ref1 = fieldConfig.extensions) === null || ref1 === void 0 ? void 0 : ref1.pothosPrismaLoaded;
        const loaderCache = (ref2 = parentConfig.extensions) === null || ref2 === void 0 ? void 0 : ref2.pothosPrismaLoader;
        const fallback = (ref3 = fieldConfig.extensions) === null || ref3 === void 0 ? void 0 : ref3.pothosPrismaFallback;
        return (parent, args, context, info)=>{
            const mapping = (0, _loaderMap.getLoaderMapping)(context, info.path, info.parentType.name);
            if ((!loadedCheck || loadedCheck(parent)) && mapping) {
                (0, _loaderMap.setLoaderMappings)(context, info, mapping);
                return resolver(parent, args, context, info);
            }
            if (fallback) {
                return fallback((0, _mapQuery.queryFromInfo)(context, info), parent, args, context, info);
            }
            const selectionState = (0, _mapQuery.selectionStateFromInfo)(context, info);
            return loaderCache(parent).loadSelection(selectionState, context).then((result)=>{
                const mappings = selectionState.mappings[info.path.key];
                if (mappings) {
                    (0, _loaderMap.setLoaderMappings)(context, info, mappings.mappings);
                }
                return resolver(result, args, context, info);
            });
        };
    }
    constructor(cache){
        super(cache, pluginName);
    }
} was registered
    at map (/Users/nicholasmartin/dev/client-app/node_modules/@pothos/core/src/build-cache.ts:104:15)
    at Array.map (<anonymous>)
    at new BuildCache (/Users/nicholasmartin/dev/client-app/node_modules/@pothos/core/src/build-cache.ts:100:55)
    at SchemaBuilder.toSchema (/Users/nicholasmartin/dev/client-app/node_modules/@pothos/core/src/builder.ts:558:24)
    at Object.<anonymous> (/Users/nicholasmartin/dev/client-app/src/schema/index.ts:4:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/nicholasmartin/dev/client-app/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/private/var/folders/nh/v5sxnsqj10nfpbcsxkt40sdc0000gn/T/ts-node-dev-hook-20047625242127598.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/nh/v5sxnsqj10nfpbcsxkt40sdc0000gn/T/ts-node-dev-hook-20047625242127598.js:114:20)
(node:94272) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] 10:14:55 Error: No plugin named class PrismaPlugin extends _core.BasePlugin {
    onOutputFieldConfig(fieldConfig) {
        if (fieldConfig.kind === 'PrismaObject' && fieldConfig.pothosOptions.select) {
            const { select  } = fieldConfig.pothosOptions;
            return {
                ...fieldConfig,
                extensions: {
                    ...fieldConfig.extensions,
                    pothosPrismaSelect: typeof select === 'function' ? (args, ctx, nestedQuery)=>({
                            select: select(args, ctx, nestedQuery)
                        }) : select
                }
            };
        }
        return fieldConfig;
    }
    wrapResolve(resolver, fieldConfig) {
        var ref, ref1, ref2, ref3;
        if (fieldConfig.kind !== 'PrismaObject' || !((ref = fieldConfig.extensions) === null || ref === void 0 ? void 0 : ref.pothosPrismaSelect)) {
            return resolver;
        }
        const parentConfig = this.buildCache.getTypeConfig(fieldConfig.parentType, 'Object');
        const loadedCheck = (ref1 = fieldConfig.extensions) === null || ref1 === void 0 ? void 0 : ref1.pothosPrismaLoaded;
        const loaderCache = (ref2 = parentConfig.extensions) === null || ref2 === void 0 ? void 0 : ref2.pothosPrismaLoader;
        const fallback = (ref3 = fieldConfig.extensions) === null || ref3 === void 0 ? void 0 : ref3.pothosPrismaFallback;
        return (parent, args, context, info)=>{
            const mapping = (0, _loaderMap.getLoaderMapping)(context, info.path, info.parentType.name);
            if ((!loadedCheck || loadedCheck(parent)) && mapping) {
                (0, _loaderMap.setLoaderMappings)(context, info, mapping);
                return resolver(parent, args, context, info);
            }
            if (fallback) {
                return fallback((0, _mapQuery.queryFromInfo)(context, info), parent, args, context, info);
            }
            const selectionState = (0, _mapQuery.selectionStateFromInfo)(context, info);
            return loaderCache(parent).loadSelection(selectionState, context).then((result)=>{
                const mappings = selectionState.mappings[info.path.key];
                if (mappings) {
                    (0, _loaderMap.setLoaderMappings)(context, info, mappings.mappings);
                }
                return resolver(result, args, context, info);
            });
        };
    }
    constructor(cache){
        super(cache, pluginName);
    }
} was registered

**Comment by hayes** [comment]
You need to use the default export of the plugin instead of the named export.  Probably should update it to support either

**Comment by nickmartinwebdev** [comment]
Thanks for that, was indeed the problem.

**Comment by ChamaraWP** [comment]
I'm getting the same error even with the default like this `import PrismaPlugin from "@pothos/plugin-prisma";`
