### ISSUE TITLE
[plugin-prisma] Pass query to totalCount

### ISSUE THREAD

**Issue by amok** [hayes/pothos#466]
I'm trying to solve the following case:

```js
builder.queryType({
  fields: (t) => ({
    foods: t.prismaConnection({
      type: "Food",
      cursor: "id",
      resolve: (query, root, args, ctx) => prisma.food.findMany(getFoodsParams(query, ctx)),
      totalCount: (conn, args, ctx) => prisma.food.count(getFoodsParams(QUERY_IS_NEEDED_HERE, ctx)),
    }),
  }),
});
```

As you can see there (in totalCount), to build proper `count` params a `query` is needed

**Comment by hayes** [comment]
Can you elaborate a bit on why you need query in the toalCount?  I see you are trying to re-use the same getFoodParams method, but I don't think any of the properties of `query` make sense to use here.

`query` will contain a few pieces.  `limit`, `offset`, and `cursor`, which are important for getting the correct page, and `select` or `include` for determining what fields/relations to select.  None of these are relevant for a count query.  I assume getFoodsParams adds a `where` and maybe an `orderBy` to the query.  I think you should be fine just passing in an empty query object when getting the count.  I'm not sure, but having things like a cursor or offset may either cause an error from prisma for passing invalid parameters.

**Comment by amok** [comment]
@hayes thank you for the answer. For now I decided to go without `totalCount`. But your argumentation seems totally makes sense. Thanks again!
