### ISSUE TITLE
Hiding Fields

### ISSUE THREAD

**Issue by knpwrs** [hayes/pothos#468]
In Hasura when a user doesn't have permission to query / access a field (or if the field is marked backend only) the field does not appear in the schema introspection. Is this possible with Pothos and GraphQL Yoga?

**Comment by hayes** [comment]
This isn't something that currently exists in Pothos.  The closest thing in pothos is the sub-graph plugin.  What could be done is to create a sub-graph for each role, and then have your Server serve the sub-graph schema for what ever role the user has, but this is likely not a very elegant solution, and would require a non-trivial amount of work to get set up and working correctly.
