### ISSUE TITLE
`relatedConnection` doesn't limit the size

### ISSUE THREAD

**Issue by shtse8** [hayes/pothos#482]
while `prismaConnection` is working perfect, `relatedConnection` is missing the `LIMIT` and `OFFSET`.

## schema
```ts
const ArticleOrderBy = builder.enumType('ArticleOrderBy', {
  values: { viewedAt: {}, createdAt: {} },
})

const Order = builder.enumType('Order', {
  values: { desc: {}, asc: {} },
})

builder.prismaNode('Locale', {
  id: { field: 'id' },
  fields: t => ({
    articles: t.relatedConnection('articles', {
      cursor: 'id',
      args: {
        orderBy: t.arg({ type: ArticleOrderBy, defaultValue: 'createdAt', required: true }),
        order: t.arg({ type: Order, defaultValue: 'desc', required: true }),
      },
      query: (args, context) => {
        return ({
          orderBy: {
            [args.orderBy]: args.order,
          },
        })
      },
    }),
  }),
})

builder.queryField('locale', t => t.prismaField({
  type: 'Locale',
  args: {
    locale: t.arg.string({ required: true }),
  },
  resolve: async (query, parent, args, context) => {
    return await prisma.locale.findUniqueOrThrow({
      where: {
        id: args.locale,
      },
      ...query,
    })
  },
}))

builder.queryType({
  fields: t => ({
    articles: t.prismaConnection({
      type: 'Article',
      cursor: 'id',
      args: {
        locale: t.arg.string({ required: true }),
        orderBy: t.arg({ type: ArticleOrderBy, defaultValue: 'createdAt', required: true }),
        order: t.arg({ type: Order, defaultValue: 'desc', required: true }),
      },
      resolve: async (query, root, args, context) => {
        return prisma.article.findMany({
          where: {
            localeId: {
              equals: args.locale,
            },
          },
          orderBy: {
            [args.orderBy]: args.order,
          },
          ...query,
        })
      },
    }),
  }),
})
```

## GQL:
```gql
query test {
  articles(locale: "en", first: 19) {
      edges {
        node {
          id
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
}
```

## query executed
```sql
Query: SELECT `project`.`Locale`.`id`, `project`.`Locale`.`code`, `project`.`Locale`.`name`, `project`.`Locale`.`languageId`, `project`.`Locale`.`regionId`, `project`.`Locale`.`toLocaleId` FROM `project`.`Locale` WHERE `project`.`Locale`.`code` = ? LIMIT ? OFFSET ?
Params: ["en",1,0]
Duration: 6ms
Query: SELECT `project`.`Article`.`id`, `project`.`Article`.`articleRawId`, `project`.`Article`.`title`, `project`.`Article`.`subtitle`, `project`.`Artic
le`.`imageId`, `project`.`Article`.`content`, `project`.`Article`.`localeId`, `project`.`Article`.`wordCount`, `project`.`Article`.`viewCount`, `project`
.`Article`.`authorId`, `project`.`Article`.`viewedAt`, `project`.`Article`.`createdAt`, `project`.`Article`.`updatedAt` FROM `project`.`Article` WHERE (
`project`.`Article`.`id`) IN (SELECT `t0`.`id` FROM `project`.`Article` AS `t0` INNER JOIN `project`.`Locale` AS `j0` ON (`j0`.`id`) = (`t0`.`localeId`) WHERE (`j0`.`code` = ? AND `t0`.`id` IS NOT NULL)) ORDER BY `project`.`Article`.`createdAt` DESC LIMIT ? OFFSET ?
Params: ["en",20,0]
Duration: 38ms
```

It works fine for `prismaConnection`, LIMIT 20 OFFSET 0 for taking size 19.

but `relatedConnection` is different story.

## GQL:
```gql
query test {
  locale(locales: "en") {
    id
    articles(first: 19) {
      edges {
        node {
          id
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
```

## query executed
```sql
locale
Query: SELECT `project`.`Locale`.`id`, `project`.`Locale`.`code`, `project`.`Locale`.`name`, `project`.`Locale`.`languageId`, `project`.`Locale`.`regionId`, `project`.`Locale`.`toLocaleId` FROM `project`.`Locale` WHERE `project`.`Locale`.`code` = ? LIMIT ? OFFSET ?
Params: ["en",1,0]
Duration: 5ms
Query: SELECT `project`.`Article`.`id`, `project`.`Article`.`articleRawId`, `project`.`Article`.`title`, `project`.`Article`.`subtitle`, `project`.`Artic
le`.`imageId`, `project`.`Article`.`content`, `project`.`Article`.`localeId`, `project`.`Article`.`wordCount`, `project`.`Article`.`viewCount`, `project`
.`Article`.`authorId`, `project`.`Article`.`viewedAt`, `project`.`Article`.`createdAt`, `project`.`Article`.`updatedAt` FROM `project`.`Article` WHERE `project`.`Article`.`localeId` IN (?) ORDER BY `project`.`Article`.`createdAt` DESC
Params: [3]
Duration: 201ms
```
it will fetch all database result behind but showing correct result. the speed is very slow because it is fetching the whole database.

**Comment by shtse8** [comment]
Additionally, I tried to add resolver to `relatedConnection`.

```ts
     resolve: (query, parent, args, context) => {
        console.log('query', query)
        return prisma.article.findMany({
          where: {
            localeId: parent.id,
          },
          orderBy: {
            [args.orderBy as string]: args.order,
          },
          ...query,
        })
      },
```

but the `query` is always `{}`

**Comment by hayes** [comment]
thanks for reporting this!  definitely something weird going on here, and I think these 2 things are related.  Seems like arguments are not being processed correctly here.  I'll try to get this fixed in the next couple days.  I'm traveling right now so, might be a couple days

**Comment by hayes** [comment]
I spent some time trying to debug this on my end.  There is some inconsistency in the query passed to the fallback resolver, but I think as you pointed out, this underlying issue is with how prisma is optimizing queries.  

I think the root issue needs to be solved in prisma (I see you already opened https://github.com/prisma/prisma/issues/14499). I'll get a fix out for the missing args issue pretty soon

**Comment by hayes** [comment]
Shirt term, using t.prismaConnection instead of relatedConnection should be a reasonable workaround.

I *think* the reason this hasn't been addressed in Prisma is because most relationships have a lower number of records.  Definitely should be a high priority fix for Prisma though

**Comment by hayes** [comment]
Okay, the issue I found with some query params not being passed to resolvers for `relatedConnection` should be fixed now.  This won't fix the original issue you were trying to solve though.

I looked into this a bit more to understand why this works the way it does, and I am not sure there will be a "fix" any time soon.

`t.relation` is designed to take advantage of prisma query optimizations around n+1 issues, and hoist as much of a query into a query in running in a parent resolver as possible.  To do this, we are stuck with the way that prisma optimizes queries.  In this case, prisma is trying to optimize the n+1 case by loading all the locals for a query (in this case it's just 1), and then selecting all articles with any of those locals.  The limit and offset can't be applied to the query, because the query is supposed to return articles for several different locals (potentially, but not in this case) and if you applied a limit, it would cut off results meant for other locals.

The main benefits of `t.relatedConnection` and this query optimization (which in your case is a major de-optimization) and the ability to define the field without a resolver.

Since the optimization is not helping here, it's better to use t.prismaConnection instead (`t.prismaConnection({ type: 'Article', cursor: 'id', resolve: (query, local) => prisma.acticle.findMany({ where: { local:_id: local.id }, ...query })`)

I know this isn't an ideal resolution, but hopefully it gives you a path forward.

Let me know if you run into any more issues.

**Comment by shtse8** [comment]
> I spent some time trying to debug this on my end. There is some inconsistency in the query passed to the fallback resolver, but I think as you pointed out, this underlying issue is with how prisma is optimizing queries.
> 
> I think the root issue needs to be solved in prisma (I see you already opened [prisma/prisma#14499](https://github.com/prisma/prisma/issues/14499)). I'll get a fix out for the missing args issue pretty soon

> Short term, using t.prismaConnection instead of relatedConnection should be a reasonable workaround.
> 
> I _think_ the reason this hasn't been addressed in Prisma is because most relationships have a lower number of records. Definitely should be a high priority fix for Prisma though

I have switched to use `prismaConnection` for pagination at the moment. n+1 issue is a tough, but as least it won't fetch whole table at once and causing slow query issue. in my case, query slows down as article as relation grows. Hope `prisma` can address this issue as soon as possible. the `take` argument in `include` has been completely ignored, which is hard to notice unless you print all executed queries to check or feeling the query is unusual slow.



> Okay, the issue I found with some query params not being passed to resolvers for `relatedConnection` should be fixed now. This won't fix the original issue you were trying to solve though.
> 
> I looked into this a bit more to understand why this works the way it does, and I am not sure there will be a "fix" any time soon.
> 
> `t.relation` is designed to take advantage of prisma query optimizations around n+1 issues, and hoist as much of a query into a query in running in a parent resolver as possible. To do this, we are stuck with the way that prisma optimizes queries. In this case, prisma is trying to optimize the n+1 case by loading all the locals for a query (in this case it's just 1), and then selecting all articles with any of those locals. The limit and offset can't be applied to the query, because the query is supposed to return articles for several different locals (potentially, but not in this case) and if you applied a limit, it would cut off results meant for other locals.
> 
> The main benefits of `t.relatedConnection` and this query optimization (which in your case is a major de-optimization) and the ability to define the field without a resolver.
> 
> Since the optimization is not helping here, it's better to use t.prismaConnection instead (`t.prismaConnection({ type: 'Article', cursor: 'id', resolve: (query, local) => prisma.acticle.findMany({ where: { local:_id: local.id }, ...query })`)
> 
> I know this isn't an ideal resolution, but hopefully it gives you a path forward.
> 
> Let me know if you run into any more issues.

Same thought. I tried to execute the query multiple times and hoping the query will run faster after the first loading, but it is not. it is still trying to load the whole table each time and causing the relation endpoint very slow.


Anyway, thanks for your help!!! so effective.
