### ISSUE TITLE
Can `dmmf` be passed from context?

### ISSUE THREAD

**Issue by shtse8** [hayes/pothos#483]
I don't want to create `PrismaClient` while building schema. Luckily the prisma client can be passed to pothos from context.
but not the dmmf.

Without dmmf, 
```ts
TypeError: Cannot read properties of undefined (reading 'modelMap')
    at getModel (file:///D:/project/node_modules/@pothos/plugin-prisma/esm/util/datamodel.js:30:28)
    at getDefaultIDSerializer (file:///D:/project/node_modules/@pothos/plugin-prisma/esm/util/cursors.js:78:19)
    at SchemaBuilder.prismaNode (file:///D:/project/node_modules/@pothos/plugin-prisma/esm/schema-builder.js:41:81)
```

What can I do in this case?

I want something like:
```ts
prisma: {
    client: context => context.prisma,
    // Because the prisma client is loaded dynamically, we need to explicitly provide the some information about the prisma schema
    dmmf: context => (context.prisma as unknown as { _baseDmmf: Prisma.DMMF.Document })._baseDmmf,
  },
```

**Comment by hayes** [comment]
No, this isn't possible.  The ddmf is what describes the Prisma schema.  This is what Pothos uses to understand when you do something like t.relation('author') that author is a User type.  The separation of dmmf from the client used was to allow client to be instantiated at run time, but you still need to understand the Prisma schema to build the graphql schema

**Comment by hayes** [comment]
I think there is a getDmmf method that Prisma added recently to a utils package that might help you get the dmmf without creating a cliebt instance

**Comment by hayes** [comment]
Made a small change to the prisma plugin so you can now pass the dmmf like this:

```ts
import { Prisma, PrismaClient } from '@prisma/client';

prisma: {
    client: context => context.prisma,
    dmmf: Prisma.dmmf,
  },
```

This avoids needing to instantiate the prisma client outside of context and is a lot cleaner

**Comment by shtse8** [comment]
> Made a small change to the prisma plugin so you can now pass the dmmf like this:
> 
> ```ts
> import { Prisma, PrismaClient } from '@prisma/client';
> 
> prisma: {
>     client: context => context.prisma,
>     dmmf: Prisma.dmmf,
>   },
> ```
> 
> This avoids needing to instantiate the prisma client outside of context and is a lot cleaner

Cool, let me try.
