### ISSUE TITLE
@pothos/plugin-prisma: Unsupported cursor type bigint

### ISSUE THREAD

**Issue by ddl-mdidomenico** [hayes/pothos#486]
Is there a recommended way to handle cursors with bigints? Thanks!

**Comment by hayes** [comment]
I think you would need to add support here: https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/util/cursors.ts#L10

**Comment by hayes** [comment]
And here https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/util/cursors.ts#L46

**Comment by hayes** [comment]
Just pushed a fix to support BigInt cursors.  Should be published in a few minutes

**Comment by ddl-mdidomenico** [comment]
Thank you very much @hayes, will check it out soon!
