### ISSUE TITLE
[tracing] Cannot read property 'now' of undefined:

### ISSUE THREAD

**Issue by P4sca1** [hayes/pothos#488]
https://github.com/hayes/pothos/blob/9089822e1daa96fcdc92908efd31dc99551c49df/packages/plugin-tracing/src/util.ts#L150

**Comment by hayes** [comment]
Looks like performance global was added in Node 16 https://nodejs.org/api/globals.html#performance

**Comment by hayes** [comment]
In older versions, you can just do something like `global.performance = require('node:perf_hooks'). performance`

**Comment by P4sca1** [comment]
Thank you for the info!
