### ISSUE TITLE
[plugin-federation] compatibility with `plugin-errors`

### ISSUE THREAD

**Issue by mdavieselsevier** [hayes/pothos#491]
When attempting to combine the `plugin-federation` and `plugin-errors` there appears to no way of applying the error handling to any entities defined with the `asEntity` function.

The function does not accept `errors` amongst the options passed in, eg:

``` typescript
builder.asEntity(DemoProductType, {
    key: builder.selection<{ upc: string }>('upc'),
    errors: {}, // Compilation error here because `errors` is not a property of `options`
    resolveReference: (parent, context, info) =>
        demoProducts.find((demoProduct) => demoProduct.upc === parent.upc),
});
```

 nor can `asEntity` be called with a union reference if a union type for the response was created some other way, eg
``` typescript
const EntityQueryDemoProductResult = builder.unionType('EntityQueryDemoProductResult', {
    types: [DemoProductType, Error],
});

builder.asEntity(EntityQueryDemoProductResult, { // compiler error here becasue `asEntity` requires an `ObjectRef` not a `UnionRef`
    key: builder.selection<{ upc: string }>('upc'),
    resolveReference: (parent, context, info) =>
        demoProducts.find((demoProduct) => demoProduct.upc === parent.upc),
});
```

I see that I am able to add `errors: {}` to individual fields _within_ the entity, but obviously that becomes hopelessly messy and impractical very quickly on any reasonably large entity and I'm sure it is not what would be intended as a way of using this.

`plugin-errors` works perfectly for our ordinary queries; it would be great to be able to provide the same quality to our federated consumers for error cases. Is it something you would expect we are able to do?

Thanks

**Comment by hayes** [comment]
Can you elaborate on what you are hoping to achieve with this?  As far as I know this would not work with federation.  resolveReferrnce and asEntity don't really define a field in your schema that could be updated to return a union.  They just help describe how to load an entity for federation.

**Comment by hayes** [comment]
More specifically, can you show me what the expected change in the resulting schema might look like

**Comment by mdavieselsevier** [comment]
Thanks for your quick response to this. 👍 

There's every chance that this is a misunderstanding on my part, so forgive me if I am going down the wrong path here if it's not making sense to you.

Presumably a schema along these lines is no more sensible? Below, I've basically I've changed the SDL for the `_entities` query that is introduced with the `plugin-federation` to accommodate the union with an error type. (This is just to try to illustrate what I'm getting at rather than any request to produce this schema specifically).
```
type BaseError implements Error {
  message: String
}

type DemoProduct {
  name: String
  price: Float
  upc: String
  weight: Float
}

interface Error {
  message: String
}

type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
  topProducts(first: Int = 5): QueryTopProductsResult
}

union QueryTopProductsResult = BaseError | QueryTopProductsSuccess

type QueryTopProductsSuccess {
  data: [DemoProduct!]!
}

scalar _Any

union DemoProductEntityResult = DemoProduct | BaseError

union _Entity = DemoProductEntityResult
```

I guess, taking a step back from the specifics of the schema, I was thinking that when an entity is being resolved, either by a normal query or through federation, it could either return what is being requested or it could fail with an error for any reason. I would have thought that the federation case is just as likely to benefit from a deterministic response in the case of failure. But perhaps this is where my misunderstanding lies 😄

**Comment by hayes** [comment]
Federation is defined by a specification, and we can't just change the semantics of how things like `_Entity` work.  Federation schemas need to be compatible with schemas defined using things other than pothos, so this likely wouldn't work.


To go into a little more detail here, if you had a field in another schema that returns a `DemoProduct`, there is no way for the federation process to know that whole type needs to be replaced with a `DemoProductEntityResult`. 

`_entites` would never be queried directly by a client, the only thing using that query should be your federated schema, and would only be used when trying to load a `DemoProduct`.  If it gets back a `DemoProductEntityResult` when it asks for a `DemoProduct` it wouldn't know how to parse that result to get the requested details for whatever other field it was resolving.

**Comment by mdavieselsevier** [comment]
> `_entites` would never be queried directly by a client, the only thing using that query should be your federated schema

OK - that's the part I'd missed.

Thanks again for getting back to me on this - sorry for diverting your time away from the great stuff you're doing here 👍
