### ISSUE TITLE
Local plugin failing to reload in Next.js

### ISSUE THREAD

**Issue by feliskio** [hayes/pothos#494]
I'm currently migrating an API from Nexus to Pothos and am loving the experience so far. So firstly thank you for your great work and all the TS magic.

**Issue:**
To ease the transition I require some custom plugins which I'd like to locate inside of a subdirectory.
Now the problem I am facing is that whenever I make changes to anything linked to that API route causing it to rebuild OR I load my schema from another place such as a second GraphQL endpoint, an error stating _Recieved multiple implementations for plugin xyz_ is thrown:

<img width="479" alt="grafik" src="https://user-images.githubusercontent.com/33993147/182636194-fe36ec07-ca34-4b42-8cb2-fdd516413c62.png">

**Example:**
I've created a minimal example for that based on the example code provided in this repo:
https://github.com/feliskio/pothos-nextjs-error-reload
The problem is demonstrated using both Helix and Apollo.

**Solution idea:**
There seems to be a [variable in place](https://github.com/hayes/pothos/blob/731a5701fc717a28c6ca5a97f7b223a4dca16b34/packages/core/src/builder.ts#L79) that could [allow overwriting registered plugins](https://github.com/hayes/pothos/blob/731a5701fc717a28c6ca5a97f7b223a4dca16b34/packages/core/src/builder.ts#L113) but it looks like there is no way to modify that value. If that check could be disabled during development the problem would most likely be solved - although I'm not sure if that would cause other issues internally.

**Comment by hayes** [comment]
Is there a reason you can't just do `SchemaBuilder.allowPluginReRegistration = true`?

**Comment by feliskio** [comment]
That solves it and at least in my case there is no reason not to use that approach.

**Code I used to allow re-registration during development:**
```
if (process.env.NODE_ENV === 'development') {
  SchemaBuilder.allowPluginReRegistration = true;
}
```

**Comment by feliskio** [comment]
Maybe it makes sense to reference that property either inside the _Troubleshooting_ and/or the _Writing plugins_ guide.
Same with #49 although I am still struggling with that one.

Tell me what you think and I'll create a PR.

**Comment by hayes** [comment]
Some extra docs around this would probably be helpful.  Adding to the troubleshooting docs seems like a good place to start.
