### ISSUE TITLE
Error: Duplicate typename: Another type with name `Type` already exists.

### ISSUE THREAD

**Issue by sharmapukar217** [hayes/pothos#502]
Can't change the code while changing my code showing Error: Duplicate typename: Another type with name `Type` already exists. I'm using `vite` for development with `vite-plugin-node`

**Comment by hayes** [comment]
Can you try adding the following to your vite config?
```
ssr: {
   noExternal: ['@pothos/core']
}
```

**Comment by sharmapukar217** [comment]
> Can you try adding the following to your vite config?
> 
> ```
> ssr: {
>    noExternal: ['@pothos/core']
> }
> ```

that didn't work either. But i did managed to do so. I imported all my types to a file, then i imported that file in my schema.ts as normal import "./imports" but also added an import("./imports") to my builder.ts file and that worked for me. :-)

**Comment by hayes** [comment]
This workaround might also help: https://github.com/hayes/pothos/issues/49#issuecomment-836056530

Need to write some docs on how to set up vite, I don't have much personal experience with that yet.

**Comment by sharmapukar217** [comment]
> 

thank you 😄  but i managed to fix my problems.

**Comment by hayes** [comment]
> that didn't work either. But i did managed to do so. I imported all my types to a file, then i imported that file in my schema.ts as normal import "./imports" but also added an import("./imports") to my builder.ts file and that worked for me. :-)

That makes sense, I think the solution I linked to above is effectively the same thing.  Glad its working for you!
