### ISSUE TITLE
Incorrect root type on mixing prismaNode and prismaField and select

### ISSUE THREAD

**Issue by shtse8** [hayes/pothos#503]
Sorry for my lazy report. I don't know how to explain this issue in simple way because I am still not really clear what's happening but somethings should be wrong but everything works.

Check this image
<img width="900" alt="image" src="https://user-images.githubusercontent.com/8020099/183442294-2084f78a-54ee-441d-b89f-2cb3f1b76d1f.png">

the root is missing `articleTags` returned.
but in runtime, it does return and everything is working fine except the type error. I believe there should be something wrong with the type.

**Comment by hayes** [comment]
Thanks for reporting this.  Just pushed a fix, should be released in the next few minutes.
