### ISSUE TITLE
Add Deno support in Relay Plugin

### ISSUE THREAD

**Issue by seanaye** [hayes/pothos#533]
The relay plugin currently does not support Deno due to the usage of the `Buffer` global.

see example https://github.com/hayes/pothos/blob/8ca9b66cf7c9bb63c5d100757ffad65c17861f9d/packages/deno/packages/plugin-relay/utils/connections.ts#L100

Fortunately Buffer has an implementation in the deno std lib https://deno.land/std@0.152.0/node/buffer.ts?s=Buffer

I'm happy to open a PR to dynamically import the class if it does not exist. I think a static import would be better but I took a look at the build script and I don't see a clean way of doing it

**Comment by hayes** [comment]
Whoops, thats a good point.   It's just used for base64 encoding, should be easy to make this work in any environment.  I'll have to check if it's supported in all node versions, but just using atob and btoa would probably work well, if prefer to not use deno stdlib unless it's needed so this also works in browsers

**Comment by seanaye** [comment]
I think if atob and btoa are available then using that is the easiest, although Deno std lib should work in browser provided that its transpiled from typescript first. Could do somthing like 
```
const b64 = typeof btoa === "undefined" ? (s) => Buffer.from(cursor, "base64").toString() : btoa
```

**Comment by hayes** [comment]
published a new version that should fix this
