### ISSUE TITLE
How to keep fields definition order in printed schema

### ISSUE THREAD

**Issue by eugmakhnev** [hayes/pothos#536]
Hi! Thank you for such a great lib :) 

At the same time, I have some trouble trying to use generated schema in a self-documenting way. My primary concern is about losing fields' natural definition order in the generated output. It bothers me cause keeping this order is important when someone trying to explore API. It's really helpful to keep the most important ones (example: "id", "createdAt") at the top and semantically close ones (example: "firstName", "lastName") nearby.

I've tried to find out a workaround to keep order, but I can't. No in documentation, no in source code. It looks like it is losing deeply inside the builder not on the last mile while printing schema. 

I don't know if is it a bug or not, but it would be great if you help me to find out a solution.

**Comment by hayes** [comment]
Pothos explicitly sorts the schema here: https://github.com/hayes/pothos/blob/main/packages/core/src/builder.ts#L570

We could probably add a new `sortSchema: boolean` option here: https://github.com/hayes/pothos/blob/main/packages/core/src/types/global/schema-types.ts#L24 (`builder.toSchema({ sortSchema: false })` that could bypass this step.

Order for things in a code first schema can be pretty tricky.  For fields, for the most part would probably work as expected, but it would be more of a coincidence than explicitly attempting to preserve order.  If you use methods like builder.objectFields or builder.queryFields to extend objects with types, the ordering of fields may change depending on imports.  In some environments this may not even be deterministic.

I don't want to make guarantees about the order of things in the schema, but I would be happy to support disabling the explicit sorting, which would probably give you a result closer to what you are hoping for.

**Comment by hayes** [comment]
added a new option on toSchema to disable sorting, hope that helps!
