### ISSUE TITLE
missing cursor field in type on `prismaConnection` `query`

### ISSUE THREAD

**Issue by shtse8** [hayes/pothos#549]
Please check this image. I think we can do better by providing the type of cursor with `cursor? : { id: number }`

![image](https://user-images.githubusercontent.com/8020099/185802159-b3f99ce4-d044-44cf-bbfb-a2499115f4bd.png)

For now, the type is missing so I need to cast it in my code.
```
const cursor = query.cursor as { id: number }
```

**Comment by hayes** [comment]
Just published a new version that has a better cursor type.  The type is now the type prisma expects for the cursor.  This means you should be able to access the prop without a cast, but won't be specifically limited to to the field you define as a cusor. Hope that works for you ..
