### ISSUE TITLE
`fullTextSearch` breaks types

### ISSUE THREAD

**Issue by GauBen** [hayes/pothos#553]
Hello!

Using [`full-text search`](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#enabling-full-text-search) like this:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}
```

Breaks generated types:

![image](https://user-images.githubusercontent.com/48261497/186032990-e68466fb-424a-419d-9c38-cfa26e3298a1.png)

This is because the full-text search feature creates types with different names:

https://github.com/prisma/prisma-engines/blob/6be410e82fb9c9de89d9348ecd3d2d2359cc8aad/query-engine/schema-builder/src/input_types/objects/order_by_objects.rs#L24-L35

I'll submit a pull request offering a workaround in a few minutes

**Comment by hayes** [comment]
Thanks again for the PR to fix this! I'll get this released in the next few minutes

**Comment by hayes** [comment]
Release with a fix should be available now

**Comment by haleksandre** [comment]
If `fullTextSearch` is enabled you should also be allowed to pass `'search'` as an `ops` to `prismaFilter`

```ts
builder.prismaFilter("String", {
 ops: ['search']
})
```

On a side note `AND`. `OR`, `NOT` seems to not be accepted as well?

**Comment by hayes** [comment]
just pushed support for `search`.  `AND`, `OR`, and `NOT` are now supported on `prismaWhere`, but not valid for `prismaFilter` this aligns with what the prisma client accepts. 

To filter by `OR` on something like a users name you would need to something like:

```
user: {
  OR: [{
    name:  { eg: "name1" }
  }, {
    name:  { eg: "name1" }
  }]
}
```
