### ISSUE TITLE
How can I add a field to a connection type without providing a resolver?

### ISSUE THREAD

**Issue by knpwrs** [hayes/pothos#561]
I have the following connection object:

```ts
export const SearchConnection = builder.connectionObject({
  name: 'SearchConnection',
  type: ISearchHit, // builder.simpleInterface
  fields: (t) => ({
    aggs: t.field({
      type: SearchAggs, // builder.simpleObject
      resolve: (root) => root.aggs,
    }),
  }),
});
```

And the following field in my query type:

```ts
    search: t.field({
      type: SearchConnection,
      args: {
        query: t.arg.string({ required: true }),
        ...t.arg.connectionArgs(),
      },
      resolve: async (_root, args, _ctx) => {
        const res = await resolveOffsetConnection(
          { args },
          ({ offset, limit }) => {
            return [];
          },
        );

        return {
          ...res,
          totalCount: 31,
          aggs: {
            agg1: 31,
            agg2: 32,
            agg3: 33,
          },
        };
      },
    }),

```

This works, and the proper `aggs` object is attached as a property on the connection object, but I cannot figure out how to fix this type error:

> Property 'aggs' does not exist on type '{ pageInfo: PageInfoShape; edges: { cursor: string; node: { title: string; } | null | undefined; }[]; }

Is there a way to either skip defining `resolve` (since `aggs` is resolved in the parent anyway) or provide some generic parameter to `connectionObject` so it knows how to type `root`?

**Comment by knpwrs** [comment]
As you can see, I'm using `simpleObject` and `simpleInterface`. What I feel like I'm looking for is a `simpleConnectionObject` so I don't need to provide a resolver (since `aggs` is resolved in the parent) but I'm open to other options as well.

**Comment by hayes** [comment]
Maybe this discussion can help: https://github.com/hayes/pothos/discussions/497

It's not exactly the same, but it's very similar and the same approach should work here

**Comment by hayes** [comment]
Let me know if that doesn't work, or doesn't make sense to you

**Comment by knpwrs** [comment]
I got it working with `t.connection`! For some reason I thought I had already tried that but I must have had some paths crossed. Thank you!
