### ISSUE TITLE
Global config for with-input and error type names

### ISSUE THREAD

**Issue by glennreyes** [hayes/pothos#566]
Hey @hayes first of all thank you for this project, been enjoying exploring it so far a lot! 👏 

I was wondering if there was a way to customize with-input or error type name templates (by the with-input or errors plugin), not on a per field, but on a global basis. I could imagine to have something like this on the builder config plugin option:

```ts
typeOptions: {
  name: ({ name, typename }) => `${capitalize(name)}Input`,
},
```

Note that I am omitting the prefixed `typename` here such as `Mutation` or `Query`. If that is currently not possible, would there be any reasonable objectives to not get something like this implemented?

Thanks!

**Comment by hayes** [comment]
This doesn't exist yet, but could definitely be added in the future

**Comment by TheMightyPenguin** [comment]
@hayes gonna give this one a shot

**Comment by hayes** [comment]
This feature was just implemented for the errors plugin by @TheMightyPenguin, but we still need to add the same functionality to the with-input plugin

**Comment by hayes** [comment]
just pushed a similar update for the with-input plugin, should be published in a couple minutes
