### ISSUE TITLE
When using Turborepo, @pothos/plugin-prisma generated types stored in wrong location by default

### ISSUE THREAD

**Issue by 5t111111** [hayes/pothos#575]
When using Turborepo, @pothos/plugin-prisma generated types will be stored in wrong location by default.

## Detail

When you use @pothos/plugin-prisma in Turborepo monorepo app, auto-generated types will be stored in a wrong location.

Since Tuborepo downloads NPM packages into workspace root's `node_modules`, `@pothos/plugin-prisma` package is also stored in that path, but when you `npx generate` in individual app directory where `schema.prisma` exists, generated types are stored in the app's `node_modules`. This causes an error when you try to import them from the default location at runtime.

<img width="2439" alt="Gamma_and_Gamma" src="https://user-images.githubusercontent.com/333180/187734102-a934e05b-ea70-4a9c-a8f9-889ccbb188d6.png">

Actually it is not such critical problem as there is nice workaround solution. You can configure `output` option of `generator pothos` in `schema.prisma` or you can change import path as well. However, because Prisma client is stored intended location, ideally a plugin-prisma generated types should also be stored in there too.

## Steps to reproduce

1. `npx create-turbo@latest` and select NPM as package manager
2. In boilerplate `apps/web`, Setup GraphQL server along with Prisma, Pothos and @pothos/plugin-prisma 
3. `npx prisma generate` in `apps/web`
3. `npm run dev` and you will find there an error occurs

**Comment by abakucz** [comment]
Similar thing happened to me with (not with Turborepo).

I'd guess that Pothos assumes that `schema.prisma` is located in located in projects projects root and creates `node_modules\@pothos\plugin-prisma\generated.ts` there by default. E.g. my schema is located in `prisma/schema.prisma` ([specified in package.json](https://www.prisma.io/docs/concepts/components/prisma-schema#prisma-schema-file-location)) and the result of `npx prisma generate` is:
```
```

**Comment by 5t111111** [comment]
> I'd guess that Pothos assumes that schema.prisma is located in project's root and creates node_modules\@pothos\plugin-prisma\generated.ts there by default.

The default output path of Pothos is `node_modules/@pothos/plugin-prisma/generated.ts`, when running `prisma generate` the base path likely is set to the location where `schema.prisma` lives.

https://github.com/hayes/pothos/blob/6f23f55e8dea15aee3e346e28af6983bbb13b898/packages/plugin-prisma/src/generator.ts#L30

https://github.com/hayes/pothos/blob/6f23f55e8dea15aee3e346e28af6983bbb13b898/packages/plugin-prisma/src/generator.ts#L227-L245

On the other hand, taking a look at the generator implementation of `nexus-prisma`, it looks setting the output path to the relative parent path from the running script itself. I'd say maybe the same approach as `nexus-prisma` would fix both output path issues.

https://github.com/prisma/nexus-prisma/blob/f8313694b366145d2549a052a3f8ba473f75abc6/src/generator/generate.ts#L11

**Comment by hayes** [comment]
Should be available in the latest version, let me know if you are still seeing this after upgrading
