### ISSUE TITLE
type parameters should accept "readonly" arrays

### ISSUE THREAD

**Issue by hayes** [hayes/pothos#592]
Some places where pothos accepts arrays in options (eg `type` for list types) don't work with `readonly` arrays.  This can cause problems when using `as const` to create options compatible objects.

**Comment by hayes** [comment]
This would technically be a breaking change because all plugins that extend various interfaces accepting type parameters would need to be updated.

**Comment by minhlucvan** [comment]
That means we can not use this pattern right?
```ts
type Payload = {
    readonly items: Item[]
}

PaginatedDeliveries.implement({
	description: "paginated deliveries",
	fields: (t) => ({
		items: t.expose("items", { type: [Item] }),
	}),
});

```

**Comment by hayes** [comment]
no, this is would be uneralted.

As far as I can tell, that should work just fine

**Comment by hayes** [comment]
The thing that this is referring to would be something like:

```ts
const itemsType = [Item] as const;

const PaginatedDeliveries = builder.objectRef<Payload>('PaginatedDeliveries');
PaginatedDeliveries.implement({
  description: 'paginated deliveries',

  fields: (t) => ({
    items: t.expose('items', { type: itemsType }),
  }),
});
```

This shouldn't be something most people run into, but it can come up when trying to build helpers that generate fields for you.

**Comment by minhlucvan** [comment]
thanks for the response, my case actually like this

```ts
export type PaginatedDeliveriesShape = {
	readonly items: readonly Delivery[];
	readonly page: number;
	readonly totalPage: number;
};
export const PaginatedDeliveries = graphql.objectRef<PaginatedDeliveriesShape>("PaginatedDeliveries");

PaginatedDeliveries.implement({
	description: "paginated deliveries",
	fields: (t) => ({
		items: t.expose("items", { type: [delivery] }),
	}),
});

```

then the eslint error thrown

![image](https://user-images.githubusercontent.com/11575076/208805029-d4b5115b-373f-4491-bac4-dd95c4e426c3.png)

I think it's related

**Comment by hayes** [comment]
Ah, I see, yeah.  Similar issue, but not specifically this issue was about.  This should be easier to fix though

**Comment by hayes** [comment]
@minhlucvan this should be fixed in the latest release

**Comment by hayes** [comment]
This ended up being too big a breaking change to add into the 4.0 release, and hasn't really come up again, so closing this out for now
