### ISSUE TITLE
Allow defaultValue for input fields to accept null

### ISSUE THREAD

**Issue by mmahalwy** [hayes/pothos#596]
With input field:

```ts
employerLiabilityBodilyInjuryByAccidentEachAccident: t.float({
        required: false,
        defaultValue: null,
      }),
```

<img width="659" alt="image" src="https://user-images.githubusercontent.com/3749095/189246832-e794ada0-4a11-4b20-a381-c0bb954e5f23.png">

While `undefined` can be used, this wouldn't work when used with Prisma as Prisma handles `undefined` and `null` differently

**Comment by hayes** [comment]
Just pushed a fix for this, thanks for the report!

**Comment by mmahalwy** [comment]
thank you @hayes
