### ISSUE TITLE
@pothos/plugin-prisma incorrect typing for @typescript-eslint

### ISSUE THREAD

**Issue by abakucz** [hayes/pothos#599]
I and using `@pothos/plugin-prisma` and whenever I generate Prisma schema `pothos-types.ts` is generated.

In `pothos-types.ts` file, for all models without relations following typing is used:
```ts
Relations: {};
```

But this is [considered to be very unsafe typing](https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492). And linting with ESLint actually fails on this with following error:
```
Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead  @typescript-eslint/ban-types
```

Would it be possible to change the typing in case there are no relations for given model?

**Comment by alexkunin** [comment]
Maybe it will be better to avoid linting generated code? You're not in control of that code, and you are not supposed to directly change it, so, linting it seems to be a waste of CPU cycles. Linting is subjective by definition (it does stylistic errors detection etc.), and code generator won't be able to satisfy all possible linting rules defined in every project that uses this library.

**Comment by hayes** [comment]
Hey, I think the above advise to not lint generated code is probably the best path forward.

I appreciate the concern around using good typescript patterns in the generated code, but In this case, this lint rule doesn't make any sense for these generated types.  The generated types are used very specific ways, and have specific semantics they need to follow for everything to work correctly.  Lint rules that make sense in application code, don't always make sense in library code.  I think one thing we could do is emit a comment at the top of the file to disable eslint.  The way empty objects are being used here is perfectly safe for the way these types are used.  The issue with a lot of lint rules like this is that they don't always apply to every situation.
