### ISSUE TITLE
Allow defaultValue to be a function that returns a value

### ISSUE THREAD

**Issue by mmahalwy** [hayes/pothos#630]
This wont pass TS:
```ts
args: {
      effectiveDate: t.arg({ type: 'Date', required: false, defaultValue: () => new Date() }),
    },
```

Error:
```
Type '() => Date' is not assignable to type 'Date'.ts(2322)
```

**Comment by hayes** [comment]
`defaultValue` corresponds to graphql-js default value, and default values are serialized and printed as part of the schema, and exposed in graphiql.  Using a function that dynamically generates the default function would not work in these situations.  It would be possible write a plugin that does something like this, potentially adding it a new option (maybe just `default`), but in core, `defaultValue` needs to align with how this works in graphql-js.

**Comment by hayes** [comment]
I think in this case, what I would do is destructure the args arg with a default value for date.  That will get evaluated when the resolver runs

**Comment by mmahalwy** [comment]
makes sense. thanks for the quick reply! closing
