### ISSUE TITLE
Typing issues when code splitting

### ISSUE THREAD

**Issue by viict** [hayes/pothos#632]
Hello,

First of all, thanks for doing this package, out on the market this is the most updated package right now and we are moving towards implementing a big graph with this.

Second, I don't think this is really an issue, but rather an advice request.

We are building about 10 subgraphs and our main plan is to abstract our schema across classes to create an abstraction over all the schema definitions. This is because we want to share pieces between all the subgraphs, thus we have a shared package where the bootstraping is done. This is working fine for most of the things but typings are wild and sometimes builds works sometimes not, specifically regarding the extension being done for the shield and args as an example.

Are we moving towards a really wrong solutions here or is there a better way for handling this scenario?

**Comment by hayes** [comment]
There are a lot of different ways someoje can set up something like this.   Without more context it's really hard to know what the typing issue is.  Depending on how you are setting up your shared abstraction, something I've seen in the past is that plugin types get omitted when compiling the shared package.  In some cases you may need to import any plugins into each package that uses your shared abstraction.  Plugins add types to a shared scope, and just importing them *may* fix some type issues.  For anything more specific, I'd need to know a lot more about how you are setting things up

**Comment by viict** [comment]
With a lot of trial and error I was able to move forward with our current approach, having a separate file to place all the custo m global-types on our package and actually turning it into a importable file made it all work, which brings me to my next question:

Wouldn't things be easier for everyone if `@pothos/core` had exposed typings, so we can actually import them from our app?

**Comment by hayes** [comment]
> Wouldn't things be easier for everyone if @pothos/core had exposed typings, so we can actually import them from our app?

Sorry, not sure what you mean by this.

Glad you found a path forward.  I'm not home this week, and haven't had much time to look at the above, but I am very surprised making things async would change how types work

**Comment by viict** [comment]
@hayes I'd like to excuse myself for the dumbness 😂 

We ended up finding what was causing all the issue and it was a badly configured tsconfig. Things seem to be working just fine.
