### ISSUE TITLE
prismaConnection with nullable: true does not allow returning nulls

### ISSUE THREAD

**Issue by villesau** [hayes/pothos#638]
Hi,

following returns a type error:

```
builder.queryField("projects", (t) =>
  t.prismaConnection({
    cursor: "id",
    type: ProjectObject,
    nullable: true,
    resolve: () => null
  })
);
```

I think it should not give type error since `nullable` is set to true.

**Comment by hayes** [comment]
Looks like this should be straight forward to fix, the definition for the resolver return type is here: https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/types.ts#L563

Should probably use the PrimsaResolver type used for the normal Prisma fields which correctly handles the nullable option.

**Comment by hayes** [comment]
This should be fixed now

**Comment by villesau** [comment]
Wow, that's fast. Thank you a lot!
