### ISSUE TITLE
docs: Need to set syntax highlighting for prisma codes

### ISSUE THREAD

**Issue by unknowingknow** [hayes/pothos#653]
It doesn't show code blocks correctly in documentation when the markdown syntax highlighting is not set.

> ![capture](https://user-images.githubusercontent.com/52380214/199854790-4550d1b0-2ad6-487d-a83d-e13bcf38e383.PNG)
https://pothos-graphql.dev/docs/migrations/giraphql-pothos#prisma-plugin

The [Prisma plugin](https://pothos-graphql.dev/docs/plugins/prisma) page is also the same.

FYI
`highlight.js` haven't supported the `prisma` syntax yet.
- https://github.com/prisma/prisma/issues/2337
- https://highlightjs.readthedocs.io/en/latest/supported-languages.html

The `prisma` documentation seems to have it as a custom syntax highlighting.
- https://github.com/prisma/docs/blob/c8886b7e89e11a6cf67f3512e9596a31bec969ba/src/components/shortcodes/prism/prism-prisma.js

**Comment by hayes** [comment]
Interesting.  Seems to be an issue with the light theme, not sure what's going on.   Thanks for reporting!

It's not a good solution, but if you enable dark mode, it becomes readble

**Comment by hayes** [comment]
should be fixed now
