### ISSUE TITLE
Custom resolver for node/nodes in @pothos/relay

### ISSUE THREAD

**Issue by JipSterk** [hayes/pothos#664]
So its been awhile since [this](https://github.com/hayes/pothos/issues/340#issuecomment-1094509662) issue. But i think it might be possible to provide (some) support of relay and federation in pothos. Since the implementation of the `@sharable` decorator its now possible to resolve fields on multiple services (but im not really sure if it wil stay this way [source](https://github.com/apollographql/federation/issues/1917#issuecomment-1161463975)). None the less i am willing to work up a draft pr where it possible to add a custom `node/nodes` resolver in the `relayOptions` in `@pothos/plugin-relay`.

With custom resolving of (node/nodes) you would be able to decode a global id and resolve to the correct model and load it from the database.
Consider the following 2 schemas:

user-service:
```graphql
directive @inaccessible on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

directive @link(import: [link__Import], url: String!) on SCHEMA

directive @override(from: String!) on FIELD_DEFINITION

directive @shareable on FIELD_DEFINITION | OBJECT

interface Node {
  id: ID!
}

type Query {
  node(id: ID!): Node @shareable
  nodes(ids: [ID!]!): [Node]! @shareable
}

type User implements Node @key(fields: "id")
{
  id: ID!
  username: String!
  email: String!
}
 
scalar link__Import
```

reviews-service:
```graphql
directive @inaccessible on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

directive @link(import: [link__Import], url: String!) on SCHEMA

directive @override(from: String!) on FIELD_DEFINITION

directive @shareable on FIELD_DEFINITION | OBJECT

interface Node {
  id: ID!
}

type Query {
  node(id: ID!): Node @shareable
  nodes(ids: [ID!]!): [Node]! @shareable
}

type Review implements Node @key(fields: "id")
{
  id: ID!
  body: String!
  author: User! @provides("username")
}

type User implements Node @key(fields: "id")
{
  id: ID! @external
  reviews: [Review!]
}
  
scalar link__Import
```

the custom resolver could be like the following:
```ts
function node(id: string) {
  const { type, id } = decodeGlobalID(args.id); //this is already exported from `@pothos/relay`

  const toModel = (typename: string): "user" => { // probably only want to limit this to available prisma models it would be nice to infer this through the type system pothos provides
    if (typename === "User") {
      return "user";
    }
    throw new Error("node type cannot be resolved"); 
  };
  
  return db[toModel(typename)].findFirst({
    where: {
      id,
    },
  });
}

new SchemaBuilder<{
  PrismaTypes: PrismaTypes;
}>({
  relayOptions: {
    node,
    nodes: (ids: string) => {
      return ids.map(id => node(id))
    }
});
```

in this case you could run a query like this and it would resolve throughout all subgraph services:
```graphql
query UserWithReviews {
  node(id: 'VXNlcjpiYjQ2M2I4Yi1iNzZjLTRmNmEtOTcyNi02NWFiNTczMGI2OWI=') {
    __typename
    id
    ... on User {
      username
      reviews {
        id
        body
      }
    }
  }
}
```

as stated above i would like to attempt at such a draft pr but i have no idea where to start on implementing such a feature. I have looked at some source code for `@pothos/plugin-relay` but didn't know where to start. if you could give me a few pointers at how to implement this it would be greatly appreciated.

**Comment by hayes** [comment]
there is already a place for options for the node/nodes queries here: https://github.com/hayes/pothos/blob/main/packages/plugin-relay/src/types.ts#L46-L65  currently this omits the `resolve` option, since it can't be typed correctly.  

the fields are defined here: https://github.com/hayes/pothos/blob/main/packages/plugin-relay/src/schema-builder.ts#L148-L179

hopefully that gives some idea on where to start looking for a way to add in a way to define a custom resolver

**Comment by tslater** [comment]
Does this proposal also include custom resolvers for the prisma extension nodes?

**Comment by hayes** [comment]
> Does this proposal also include custom resolvers for the prisma extension nodes?

Not sure if I understand, but the proposed change would work for all nodes, including ones defined by the prisma plugin
