### ISSUE TITLE
Arguments with default values are nullable in resolvers

### ISSUE THREAD

**Issue by Emilios1995** [hayes/pothos#686]
When assigning a default value to a field's arg, I would expect the arg in the resolver to have a Typescript type that doesn't include `null` and `undefined`.

However, the opposite was the case. The value was nullable even though with the default value that should not happen. 

See the following code sample:

```
builder.objectRef<ProfilePhoto>('ProfilePhoto').implement({
  fields: t => ({
    url: t.field({
      type: 'String',
      args: {
        width: t.arg({ type: 'Int', defaultValue: 60 }),
      },
      resolve: ({ key }, { width }) => {
        // The type of `width` is `string | null | undefined`. I expected it to be just `string`
       // ...
      },
    }),
  }),
})
```

Of course, I can make the argument `required` and only then is the TS type correct. (GraphQL allows for required args with default values, but I think this should work without having to resort to that.)

Please let me know if I'm missing something and this is expected behaviour. If this is indeed a bug and you don't expect the fix to be too complex, I can look into submitting a PR.

**Comment by hayes** [comment]
default arguments in GraphQL are a little un-intuitive in how they work:

When you provide a default value for an argument, that value will be used when no value is explicitly provided.  If you have a nullable argument with a default value, you can still explicitly provide null as a value in the query, which will not be overwritten by the default value.

Making an argument non-nullable (required in pothos), specifying a default value means that you will not need to provide that value as part of the query.  

So if your goal is to have an argument with a default value, that doesn't need to be provided in a query, but always has a value in the resolver, the correct way to do this is to make it non-null with a default.

Hope that helps, let me know if you have any other questions!

**Comment by Emilios1995** [comment]
Got it, thanks for the clarification!
