### ISSUE TITLE
Issue for generated types

### ISSUE THREAD

**Issue by yovanoc** [hayes/pothos#706]
If I put this in the schema.prisma

```
clientOutput = "@project/database"
```

Pothos generates me ` from "@project/database/index.js";`

that's really not what I want. I just want what I wrote in the clientOutput, because I really don't want the index.js things I already define the exports field in my package.json of this package.

But I really think is something more than that, we can't use @project/database too because its in a node_module folder.. I have no choice to set a thing like that:

```
  output       = "../../../apps/api/src/pothos-types.ts"
```

**Comment by hayes** [comment]
> But I really think is something more than than, we can't use @project/database too because its in a node_module folder.. I have no choice to set a thing like that:

Can you elaborate on this?  Are you saying that you are generating Pothos types into node_modules so that even if the import for the generated file was `@project/database` it wouldn't work?

A more complete example of what your setup is would be helpful (where are you generating the Prisma client, where are you generating Pothos types, what are the exports you are defining that you are trying to use.

**Comment by yovanoc** [comment]
I'm in a turborepo with all my apps and packages in esm. So my package.json looks like this:

```json
"exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js",
      "require": "./dist/index.cjs"
    },
    "./dist/*": {
      "types": "./dist/*.d.ts",
      "import": "./dist/*.js",
      "require": "./dist/*.cjs"
    }
  },
  "main": "./dist/index.cjs",
  "module": "./dist/index.js",
  "types": "./dist/index.d.ts",
```

It means that other packages/apps don't need the .js thing. Only in the same package.

The `clientOutput = "@project/database"` thing actually add a `index.js` so it's wrong. Then even if it write exactly what I put in the clientOuput field it doesn't work too because it's generated in:

`/node_modules/.pnpm/@pothos+plugin-prisma@3.38.1_pnd2xa23n5s4d3hd6qivcnofum/node_modules/@pothos/plugin-prisma/esm/generated.ts`

and it can't resolve `@project/database`

**Comment by hayes** [comment]
I'm not sure that second part is something I can really solve for you.  What I would recommend instead is that you generate the pothos types into the package as the prisma client (into the @project/database package), you still would use a relative path for the clientPath, but it would be relatively short/simple

**Comment by yovanoc** [comment]
Yes I think I will do that, then I could import it with @project/database/dist/pothos-types

**Comment by hayes** [comment]
currently I think trying to detect package names and treat them differently (by not appending index.js) may be a breaking change, and I'm not sure it's actually a good idea to try to support this.  I'm going to close this for now, but happy to talk more about it if you feel it's important
