### ISSUE TITLE
Order of plugins: PothosRelayPlugin + ScopeAuthPlugin, changes globalId type

### ISSUE THREAD

**Issue by aantthony** [hayes/pothos#708]
The docs say the ScopeAuthPlugin should be first, but it seems like having auth first creates type issues when using GlobalIds.

Example:

```ts
import builder from './builder';

builder.relayMutationField(
  'test',
  {
    inputFields: t => ({
      orgId: t.globalID({ required: true }),
    }),
  },
  {
    authScopes: (root, args) => {
      console.log('authScopes', args.input.orgId);

      args.input.orgId.typename; // typescript validates

      return true;
    },
    async resolve(root, args, ctx) {
      console.log('resolve', args.input.orgId);

      args.input.orgId.typename; // typescript validates

      return true;
    },
  },
  {
    outputFields: t => ({
      ok: t.boolean({ resolve: () => true }),
    }),
  },
);

```

Output with Relay first (matches TS types correctly):
```
authScopes { typename: 'Org', id: '123' }
resolve { typename: 'Org', id: '123' }
```

Output with Auth first (wrong):
```
authScopes T3JnOjEyMw==
resolve { typename: 'Org', id: '123' }

```

**Comment by hayes** [comment]
Sorry, had intended to reply sooner.   The docs here could probably be updated a bit to add more context.  For this case, it should generally be safe to move the relay plugin ahead of the auth plugin.  The only logic the relay plugin has in it's resolver wrapping is the globalID parsing.  I have a couple relay APIs in production that do this.
