### ISSUE TITLE
how to use edge as output field in relay mutation

### ISSUE THREAD

**Issue by MaxAst** [hayes/pothos#727]
I'm using the prisma plugin together with the relay plugin and I have the following mutation to add a city to a list of cities:

```
builder.relayMutationField(
      "createCity",
      {
        inputFields: (t) => ({
          name: t.string({ required: true }),
        }),
      },
      {
        resolve: async (parent, args) => {
          return prisma.city.create({
            data: {
              name: args.input.name,
            },
          });
        },
      },
      {
        outputFields: (t) => ({
          activity: t.prismaField({
            type: "City",
            resolve: (_, parent) => parent,
          }),
        }),
      }
);
```

Instead of returning the prisma object, I'd rather return an edge so that I can make use relay's declarative way of adding an edge to a connection, as [described here](https://relay.dev/docs/guided-tour/list-data/updating-connections/#appendedge--prependedge).

From my understanding, this is currently not possible yet, given that their is no API for the edge encoding, right? I could imagine an API like `t.prismaEdge`, where the edge is created for you, like it's done for `t.prismaConnection`. WDYT?

**Comment by hayes** [comment]
You can create edge re-usable edge objects using the API documented here: https://pothos-graphql.dev/docs/plugins/relay#reusing-edge-objects

To be able to get the selection for a query, you could use the (undocumented) queryFromInfo method here: https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/util/map-query.ts#L325

```ts
builder.relayMutationField(
      "createCity",
      {
        inputFields: (t) => ({
          name: t.string({ required: true }),
        }),
      },
      {
        resolve: async (parent, args, context, info) => {
          return prisma.city.create({
            ...queryFromInfo({context, info, path: ['activity', 'node']}),
            data: {
              name: args.input.name,
            },
          });
        },
      },
      {
        outputFields: (t) => ({
          activity: t.field({
            type: CityEdge,
            resolve: (parent) => ({ node: parent, cursor: somehowGetCityCursor(parent) }),
          }),
        }),
      }
);

```

**Comment by hayes** [comment]
To get the cursor you can look at how cursors are encoded for prisma connections here: https://github.com/hayes/pothos/blob/f64a25914531eecf8eefe98701a8dc296dc09946/packages/plugin-prisma/src/util/cursors.ts#L9-L35

The exact encoding depends on what you use for the connection cursor.  A lot of the complexity there is to support multi-column indexes.

If you don't want to wrap things in a result object, you can just use the builder.mutationField method instead, and remove the `activity` from the path, and also update the resolver to return an object with node/cursor

**Comment by MaxAst** [comment]
got it, thanks a lot @hayes! I actually came across the `formatCursorChunk` function while digging, but was a bit wary to 
write a function that does the same thing for my use case. In case the underlying edge encoding logic ever changes in pothos, I'd end up with different base64 encoded values, no? FYI I use the prisma `id` as a cursor.

**Comment by MaxAst** [comment]
got it, thanks @hayes! would it make sense to export `getCursorFormatter` from the prisma plugin? Just thought that if I replicate this encoding logic for my mutation output field, and the underlying encoding logic ever changes in pothos, there could be issues when decoding the cursor, no?

**Comment by hayes** [comment]
Yeah, I think exporting that should be fine

**Comment by hayes** [comment]
published a new version that exports helpers for parsing/formatting prisma cursors

**Comment by MaxAst** [comment]
Amazing, thank you!
