### ISSUE TITLE
Prisma Plugin - How to expose "decimal" or other DB types?

### ISSUE THREAD

**Issue by hueter** [hayes/pothos#730]
Hello,

I have this type of prisma schema that features a `Decimal?` (PostgreSQL decimal type):

![Screenshot 2023-01-02 at 12 12 47 PM](https://user-images.githubusercontent.com/13444851/210261862-63f1c723-bfba-4fd4-8f5d-5a4684f58fe0.png)

I can't seem to get the decimal type to pass type checking:

![Screenshot 2023-01-02 at 12 07 58 PM](https://user-images.githubusercontent.com/13444851/210261938-f1fa1f68-67c8-4b89-b9a2-36b8cc3939d1.png)

I'd like to map it either to a float or ideally a string (since the JSON `number` type has precision issues sometimes), but is that possible to do with the `prismaObject` API or do I need to define the mapping elsewhere?

I also tried defining a custom Decimal type here:

```ts
export const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes;
  Context: SchemaContext;
  Scalars: {
    ID: {
      Output: number | string;
      Input: string;
    };
    DateTime: {
      Output: Date;
      Input: Date;
    };
    /** here **/
    Decimal: {
      Output: number;
      Input: number;
    }
  };
}>({
  plugins: [PrismaPlugin],
  prisma: {
    client: db,
  },
});
```

but still had the same issue:

![Screenshot 2023-01-02 at 12 19 15 PM](https://user-images.githubusercontent.com/13444851/210262395-cb1e0cba-f503-44e6-bf94-2a120f74f28f.png)

Any tips are appreciated, thanks!

**Comment by thuperthecret2** [comment]
Not sure if this helps, but I just use `t.exposeFloat()` and deal with formatting on the front end.
I have an hourly wage 'rate' which I want only two decimal places on.
I then deal with it solely on the frontend app to get my formatting, like this:
```
rateOrNull() {
      var result = Number(parseFloat(this.rate).toFixed(2))
      return !isNaN(result) ? +result : null
    },
```

**Comment by hayes** [comment]
The issue here is that the types you are defining for decimal (number) is not actually what prisma is returning.  You need to implement a scalar that actually expects a decimal type.

I just added a very simple test case here you can look at that may help: https://github.com/hayes/pothos/commit/5abbd9fc5df4d34a1a019296fb0a636d63d6e4bb

**Comment by hueter** [comment]
> Not sure if this helps, but I just use `t.exposeFloat()` which ends up as `double` in the db, and I deal with formatting on the front end. I have an hourly wage 'rate' which I want only two decimal places on. I then deal with it solely on the frontend app to get my formatting, like this:
> 
> ```
> rateOrNull() {
>       var result = Number(parseFloat(this.rate).toFixed(2))
>       return !isNaN(result) ? +result : null
>     },
> ```

Thanks for the reply. I declared the type as `Decimal(5,4)` in the model so I can ensure that percentages are somewhat structured, e.g. `55.66%` would be `0.5566` in the database with this column type. I could change it to a float/double by changing my model but I guess I was just wondering if the Prisma [Decimal](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#decimal) data type was mappable w/o migrating

**Comment by hueter** [comment]
> The issue here is that the types you are defining for decimal (number) is not actually what prisma is returning. You need to implement a scalar that actually expects a decimal type.
> 
> I just added a very simple test case here you can look at that may help: [5abbd9f](https://github.com/hayes/pothos/commit/5abbd9fc5df4d34a1a019296fb0a636d63d6e4bb)

Ah this works great, thank you! Didn't realize the prisma client exposed a `Decimal` class / type 💯

**Comment by kevinmmarlow** [comment]
@hayes I believe your test case is incomplete. It works well for exposing Decimal values, but Prisma seems to type the Decimal value as number. The input is then a number, but that will fail inside of your `scalarType` code for the Input type.

I _think_ it would be best to expose as a string, since that is what the `scalarType` expects.

```ts
const builder = new SchemaBuilder<{
  Scalars: {
    Decimal: {
      Input: string; // This is the change
      Output: string; // This is the change
    };
  };
  ...
});

builder.scalarType('Decimal', {
  serialize: (value) => value.toString(),
  parseValue: (value) => {
    if (typeof value !== 'string') {
      throw new TypeError('Decimal must be a string');
    }
    return new Decimal(value);
  },
});
```

**Comment by hayes** [comment]
Yeah, I think that seems like a reasonable way to implement the Decimal scalar
