### ISSUE TITLE
Can't use objectType with a generic class

### ISSUE THREAD

**Issue by jksaunders** [hayes/pothos#743]
Hi!

I'm getting a long Typescript error trying to use a generic class as the first argument of `objectType`. I've attached a Codesandbox link but here's the gist of it:

```
  class ResultSet<T> {
    constructor(public metadata: ResultSetMetadata, public data: T[]) {}
  }

  const resultSet = builder.objectType(ResultSet<ORef>, { // ORef extends ObjectRef<unknown>
    name: `${name}ResultSet`,
    description: `Result set for ${name}`,
    fields: (t) => ({
      data: t.field({
        resolve: (parent) => parent.data, // Error here!
        type: [resultType], // resultType: ORef;
      }),
      metadata: t.field({
        resolve: (parent) => parent.metadata,
        type: ResultSetMetadata,
      }),
    }),
  });
```

So `ResultSet<T>` is simply a class with data (an array of `T`) and metadata. In the above `objectType` call, the `parent.data` attribute is for sure the correct data type to match the return type. Replacing the generic class with a specific class has no errors, demonstrated in the Codesandbox link as well.

The full error is this:
```
Type 'ORef[]' is not assignable to type '[ShapeFromTypeParam<ExtendDefaultTypes<{ Context: AppContext; Scalars: { Date: { Input: Date; Output: Date; }; }; }>, [ORef], false>] extends [...] ? null extends (readonly Item[] | ... 1 more ... | undefined) & ShapeFromTypeParam<...> ? ORef[] extends MaybePromise<...> ? MaybePromise<...> & ORef[] : (null & ShapeFr...'.ts(2322)
builder-options.d.ts(10, 79): The expected type comes from the return type of this signature.
```

The use case is for creating a snippet for creating a "search query" generation function, creating a few object types given the result of another `objectType` call, eg. `const UserORef = builder.objectType(...)`, `buildSearch(UserORef)`.

Codesandbox link: https://codesandbox.io/s/happy-voice-wprsj2?file=/src/index.ts

It seems like this usage should work, but if it's meant not to for any reason let me know!

**Comment by jksaunders** [comment]
Oh wow thank you! My bad on that typing, that was 100% it 🙏 

Using this for a bunch of clients, appreciate your hard work here!

**Comment by hayes** [comment]
no problem!
