### ISSUE TITLE
Hardcoded path does not exist

### ISSUE THREAD

**Issue by liftyourgame** [hayes/pothos#747]
Getting this error:

TS2307: Cannot find module '/Users/michaelhayes/code/prismaday-talk/node_modules/@prisma/client' or its corresponding type declarations.

generated.ts has:

import type { Prisma, User, Post, Comment } from "/Users/michaelhayes/code/prismaday-talk/node_modules/@prisma/client";

Why the hard coded path michaelhayes?

**Comment by hayes** [comment]
This file should never have been checked in, I think what happened was this got created while I had Pothos linked into another project while trying to reproduce another issue, and didn't notice this file got added.  Running prisma generate should overwrite this file with a generated file based on your schema.  This file should contain a message letting you know that you need to run the generator. I'll try to update it today

**Comment by hayes** [comment]
this should be fixed in the latest release!
