### ISSUE TITLE
[bug] Pothos Subscriptions with Apollo v4

### ISSUE THREAD

**Issue by Cauen** [hayes/pothos#748]
Hi @hayes 

I couldn't make Pothos work with the new **Apollo v4** Subscriptions. ❌
https://github.com/Cauen/apollo-subscriptions-pothos/tree/dev

I tested it with another Schema (ok), and when I switch to Schema with Pothos, it gives an error
`"Cannot read properties of undefined (reading 'Symbol(Pothos.contextCache)')"`

In **Apollo v2**, it works fine 💹
https://github.com/Cauen/apollo-subscriptions-pothos/tree/old-version-apollo

---

Spent a bunch of hours testing and debugging but cannot find the problem

I think there is a bug with new Apollo v4 integration

Any ideas on this?

**Comment by hayes** [comment]
This looks like you need to create a context object for the subscription

**Comment by Cauen** [comment]
Thanks
That was the case

https://stackoverflow.com/a/68773681/6638583
https://www.apollographql.com/docs/apollo-server/data/subscriptions/#operation-context

![image](https://user-images.githubusercontent.com/8796757/212981737-067248ad-9515-4df4-94cb-2eb2eae93bed.png)
