### ISSUE TITLE
`relationCount` errors. on null returned for non-nullable field

### ISSUE THREAD

**Issue by ryanmt** [hayes/pothos#750]
Hi! I'm not sure if there's some versioning mismatches or something else amiss here but I noticed over the last few weeks that `relationCount` seems to be consistently broken for me.

I've looked over the PR introducing filtering but didn't see anything clearly amiss there.

Given:
```
model Thing {
  id: string
  reports: ThingReport[]
}

model ThingReport {
  thingId: string 
  thing @relation(fields: [thingId], references: id)
}
```
and 
```
builder.prismaObject("Thing", {
  fields: (t) => {
    reportCount: t.relationCount("reports")
  }
}
```  

I'm seeing that if I use `relationCount` in my pothos `prismaObject` definition, it will return an error about the typing.

`"Cannot return null for non-nullable field Thing.reportCount"`.  I've gone ahead and substituted explicit `t.int(...)` in lieu of `relationCount` but if this isn't readily reproducible, I'm hoping at least someone out there has an idea of why this would explode for me.

This is happening on records which have a `non-null` response to my explicit query as well as things which don't so I don't believe this relates to data.

**Comment by hayes** [comment]
The most likely issue here is that you are not spreading the query property into the parent field, without seeing more it's hard to confirm that's the issue, but that would be the first place I'd check

**Comment by hayes** [comment]
If this isn't the issue, logging the query being sent to Prisma, and the returned data in the root resolver would be helpful in debugging where things might be going wrong.

**Comment by hayes** [comment]
haven't hear back here, so I'm going to close this, but let me know if you have any questions.

**Comment by kelly-ry4n** [comment]
Amazing, I'll make sure to do that everywhere, don't know how missed it.

Thanks so much for the help @hayes !

Fix was:

```
builder.queryField('projectDataset', t =>
  t.prismaFieldWithInput({
    input: {
      projectDataSetId: t.input.string({ required: true }),
    },
    type: 'ProjectDataset',
-    resolve: async (_query, _parent, args, context, _info) => {
+    resolve: async (query, _parent, args, context, _info) => {
      return await prisma.projectDataset.findFirstOrThrow({
+          ...query
          where: {id: args.input.projectDatasetId}
      })
    },
  }),
);
```
