### ISSUE TITLE
Feat: [GraphQL Yoga] Request for access to edge environmental values (Cloudflare KV Namespaces, Vercel Edge Config, etc)

### ISSUE THREAD

**Issue by IamManchanda** [hayes/pothos#758]
Hello Great Open Source Project, I would like to have access to edge environmental values ... Is that possible with Pothos along with GraphQL Yoga Server? 
If yes then please document same, if not then please consider this as a feature request

=> https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-cloudflare-workers#access-to-environmental-values-kv-namespaces-etc

**Comment by hayes** [comment]
If you are using yoga, the context object will be the same as documented there.  To get types correct for the context object you will need to add the environment variables to the context type as described here: https://pothos-graphql.dev/docs/guide/context

**Comment by IamManchanda** [comment]
Thanks @hayes :)
