### ISSUE TITLE
Change the Next.js example to use Yoga?

### ISSUE THREAD

**Issue by neongreen** [hayes/pothos#761]
Helix seems to be on track for deprecation: https://github.com/dotansimha/graphql-yoga/issues/1351, https://github.com/contra/graphql-helix/issues/251.

I used the Next.js example to start my own project, and only later found out about the Yoga vs Helix situation. Should I make a PR migrating the Next.js example to Yoga?

**Comment by hayes** [comment]
Sure, PR for that would be more than welcome!
