### ISSUE TITLE
Trying to pass Options to errorOptions on the Error plugin for Pothos but getting error ``` TypeError: Ref ({ parentTypeName , fieldName  })=>`${parentTypeName}${fieldName}` has not been implemented``` when trying to generate schema.

### ISSUE THREAD

**Issue by zbarakzai** [hayes/pothos#763]
I am trying to use Error plugin same as documentation mentions here https://pothos-graphql.dev/docs/plugins/errors#builder-options.

I want to change the default generated union type name for the query and mutation, for example currently I am getting result in my generated Graphql schema something similar to this 

``` union MutationCreateProductWithErrorResult = ErrorWithCode | MutationCreateProductWithErrorSuccess```

but I want something like this 

```union CreateProduct = ErrorWithCode | CreateProduct``` 

the problem is when generate the schema  I am getting this error  

``` TypeError: Ref ({ parentTypeName , fieldName  })=>`${parentTypeName}${fieldName}` has not been implemented``` 

when trying to generate schema.

also typescript error on schema level as below image 

<img width="1167" alt="Screenshot 2023-01-22 at 11 46 37 PM" src="https://user-images.githubusercontent.com/54102898/213939572-f85d3bb9-3d87-424d-888b-2c7552a61ef4.png">

**Comment by hayes** [comment]
Can you double check you are on the latest version of the plugin? This was a recently added feature, and what you are describing looks like what would have happened before the feature was added.

**Comment by zbarakzai** [comment]
I am using ```  "@pothos/core": "^3.23.0"``` and ```"@pothos/plugin-errors": "^3.9.0",``` in a Turbo repo.

**Comment by hayes** [comment]
Looks like you need to update the errors plugin: https://github.com/hayes/pothos/blob/main/packages/plugin-errors/CHANGELOG.md
