### ISSUE TITLE
`resolveArrayConnection` returns nullable `ConnectionShape`

### ISSUE THREAD

**Issue by paulrosania** [hayes/pothos#764]
This had me scratching my head today. :)

I believe this type should be `false`, as `resolveArrayConnection` always returns a connection object:
https://github.com/hayes/pothos/blob/f3df85be74fb5d5b5478178a6e0469313223762f/packages/plugin-relay/src/utils/connections.ts#L140

Am I understanding correctly? I'm happy to open a PR if so.

**Comment by hayes** [comment]
Yup, that sounds accurate to me, PR would be more than welcome!

**Comment by paulrosania** [comment]
Easy peasy! The build tools copied my change over to the deno plugin. I didn't want to cause drift so I included it, but if that's not desired LMK.
