### ISSUE TITLE
Integrating Apollo cacheControl feature into schema not easily possible

### ISSUE THREAD

**Issue by ChristianIvicevic** [hayes/pothos#782]
I was looking into integrating the automatic caching of Apollo which I use as a server into my schema and there are two approaches. Either [declaring a directive](https://www.apollographql.com/docs/apollo-server/performance/caching/#in-your-schema-static) or [setting it dynamically](https://www.apollographql.com/docs/apollo-server/performance/caching/#in-your-resolvers-dynamic). Unfortunately there are two issues:

1. The directive that I tried to add via the directive plugin is not appearing in the schema at all. Thus it has no effect when declaring it for certain fields. I guess I need a transformer but there is none that exists for that as far as I can tell.
2. Setting the `cacheControl` dynamically works, but is not part of the `info` object according to TypeScript.

```ts
schemaBuilder.queryField('cachedData', (t) =>
  t.field({
    type: 'String',
    resolve: (_1, _2, _3, info) => {
      // @ts-expect-error
      info.cacheControl.setCacheHint({ maxAge: 30 });
      console.log('heavy computation');
      return 'result';
    }
  })
);
```

Do you have suggestions on how to support this within Pothos? Either option would be nice, the former slightly more as it clearly documents the behavior for consumers within the schema.

**Comment by hayes** [comment]
You could do something like this to add the cacheControl types to the info object

```ts
declare module 'graphql' {
  export interface GraphQLResolveInfo {
    cacheControl: {
      setCacheHint: (hint: { maxAge: number }) => void;
    };
  }
}
```
This can either be added to a declaration file that ts automatically imports, or add or import this from the file that defines the builder to ensure that the definition is always imported.

For the directives plugin, to get the directives in the schema, you need to use something like graphQL tools to print the schema with directives.  Unfortunately the printSchema method from `graphql` does not have a way to print directives

**Comment by ChristianIvicevic** [comment]
Yeah I was also considering to go for module augmentation as this is one of the _very_ rare occasions where it's actually less detrimental and unexpected. I'll just use that for now even though the DX of explicitly calling it over adding a directive is less convenient. Will research at some point how to print the directives as you proposed.

Thanks once again.
