### ISSUE TITLE
Outdated docs for Sentry envelop usage

### ISSUE THREAD

**Issue by RIP21** [hayes/pothos#788]
In the current API of `useSentry` envelop plugin I see no `trackResolvers` option to be available. 

Some guidance on how to proceed with it right now?

Here is the fresh docs for reference: https://github.com/n1ru4l/envelop/tree/main/packages/plugins/sentry

Thanks.

**Comment by hayes** [comment]
Looks like this entire feature was removed: https://github.com/n1ru4l/envelop/blob/main/packages/plugins/sentry/CHANGELOG.md#major-changes

This should mean that everything should work as expected without that option.

**Comment by hayes** [comment]
docs should be updated now, thanks for reporting this!
