### ISSUE TITLE
totalCount runtime error occured

### ISSUE THREAD

**Issue by sg45000** [hayes/pothos#796]
I have defined totalCount globally and implemented the totalCount function in the prismaConnection field.

```typescript
builder.prismaObject('User', {
  fields: (t) => ({
    posts: t.prismaConnection(
      {
        type: 'Post',
        cursor: 'id',
        totalCount: () => 1,
        resolve() {
          return []
        },
      },
      PostConnection
    ),
  }),
})
```

But when I requested the graphql query, I got a runtime error.

The stack trace is as follows
```
GraphQLError: Int cannot represent non-integer value: [function]
  at GraphQLScalarType.serialize (node_modules/graphql/type/scalars.js:61:13)
```

Maybe The totalCount function is not be executed correctly at the destination passed as an argument.

Package versions:
```
@pothos/core 3.26.0
@pothos/plugin-prisma 3.41.0
@pothos/plugin-relay 3.35.0
graphql 16.6.0
```

**Comment by hayes** [comment]
Can you share how you define totalCount globally? I suspect it's not compatible with what Prisma is doing.  Prisma connection totalCount field does not depend on any global setup, so there may be some kind of conflict here

**Comment by sg45000** [comment]
Thanks for the response.

My repository is here. https://github.com/sg45000/pothos-sample

I defined totalCount globally here.
https://github.com/sg45000/pothos-sample/blob/master/src/schema/builder.ts#L22

**Comment by hayes** [comment]
if you remove the global totalCount field, does it work as expected?

**Comment by sg45000** [comment]
No.

I removed the global totalCount field, and execute graphql query.
```json
{
  "errors": [
    {
      "message": "Cannot query field \"totalCount\" on type \"PostConnection\".",
      "locations": [
        {
          "line": 10,
          "column": 7
        }
      ]
    }
  ]
}
```

**Comment by hayes** [comment]
Ah, I think I understand the issue now.  The Prisma totalCount option doesn't work when you pass in a ref for the connection object.  This is an interesting case I'll have to think about.   totalCount by default defines a field on the connection object, but this only makes sense when the connection object is owned by the field (not passed in).  I think for now you would need to manually define the totalCount as you would for any other connection.  Not sure how this should be handled in Pothos

**Comment by sg45000** [comment]
I tried it and it works.
Thanks. 

Is this a workaround? Or will it be modified or documented in the future?

**Comment by hayes** [comment]
I'll probably end up documenting this in some format, it's not likely to change.

**Comment by berekuk** [comment]
> The Prisma totalCount option doesn't work when you pass in a ref for the connection object.

Can this be patched in `relatedConnection` types as well?

When I added `totalCount: true` and it did nothing, I was very confused until I found this issue.

**Comment by hayes** [comment]
I've added a section to the prisma plugin docs that describes how to add totalCount fields to shared connection objects
