### ISSUE TITLE
`.prismaNode` not honoring `name`

### ISSUE THREAD

**Issue by tmilewski** [hayes/pothos#802]
I've been loving Pothos, and thank you for all of your hard work!

I'm dealing a codebase which, unfortunately, contains a Prisma model with the name `Subscription`. I'm unable to change this, so I need to set the name within Pothos.

This case works:

```ts
export const SubscriptionObject = builder.prismaObject('Subscription', {
  // id: { field: 'id' },
  name: 'SubscriptionTest',
  fields: (t) => ({
```

while this case doesn't:

```ts
export const SubscriptionObject = builder.prismaNode('Subscription', {
  id: { field: 'id' },
  name: 'SubscriptionTest',
  fields: (t) => ({
```

... and throws `Invalid object name Subscription use .createSubscriptionType() instead`.

Maybe I'm doing something incorrectly, but I don't see anything in the docs or code around `.create*Type()`.

Thanks again!

**Comment by hayes** [comment]
this should be fixed now
