### ISSUE TITLE
[Question] How to get field argument types outside resolvers ?

### ISSUE THREAD

**Issue by hrasoa** [hayes/pothos#814]
Let's say I have this mutation:

```ts
builder.mutationFields(function fields(t) {
  return {
    myMutation: t.field({
      args: {
        input: t.arg(...),
      },
      async resolve(root, args) {
        await createItem(args);
      },
    }),
});
```

How can I type the argument of ```createItem``` ? I would like to separate all the functions to interact with my db outside the resolvers.

**Comment by hayes** [comment]
@hrasoa sorry I hadn't gotten around to providing an answer here yet.  Did you end up getting this figured out?

My general advise here is to avoid doing this.  Instead just type your business logic functions with the data/arguments they need and then do any required conversation in the resolver.  

There are ways to get the types for args, it's just not as easy.  I can provide some examples of needed, I just have been traveling, and it's not easy to type out on a phone.

**Comment by hrasoa** [comment]
@hayes  yes I finally typed manually my functions as I have simple inputs. If you have an example I'm interested.

**Comment by hayes** [comment]
```ts
const someArgs = builder.args((t) => ({
  arg1: t.string({ required: true }),
  arg2: t.string({ required: true }),
}));

type ArgsType = InputShapeFromFields<typeof someArgs>;

function createItem(args: ArgsType) {
  // do something with args
  return true;
}

builder.mutationFields((t) => ({
  myMutation: t.boolean({
    args: someArgs,
    resolve: (root, args) => createItem(args),
  }),
}));
```

**Comment by hrasoa** [comment]
That's what I was looking for, Thanks !

**Comment by hrasoa** [comment]
Now I don't need to maintain two types anymore,  all my args are in ```myMutation.input.ts``` which is the source of truth. 👍
