### ISSUE TITLE
[ Question ] How can I bubble errors to the server instead of surfacing them to the errors object?

### ISSUE THREAD

**Issue by kelly-lv-labs** [hayes/pothos#821]
Hi,

I'd like to not send errors to the client unless I explicitly decide to, and instead have them bubble up uncaught in the server.

For example:

```javascript
builder.queryField('failedInt', t =>
  t.int({
    resolve: () => 1.4444,
  }),
);
```

Does not log an error in the server console, but instead returns 

```
{
  "errors": [
    {
      "message": "Int cannot represent non-integer value: 1.4444",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "failedInt"
      ]
    }
  ],
  "data": null
}
```

to the client.

Can I adjust this behaviour?

**Comment by hayes** [comment]
Pothos doesn't really know anything about your server, it's fundamentally just building a schema and setting up resolvers.  Error handling is very dependent on the server implementation you are using.  Most servers have some sort of hook for formatting errors, which can be used to log the errors, but you'd need to lookup the exact configuration options for whatever server you are using

**Comment by kelly-lv-labs** [comment]
Your response set me on the right route I think!

I'm now trying to figure this out on the Yoga side

I'm pretty sure my problem is    `resolve: () => 1.4444` is throwing a `GraphQLError` which is being caught by Yoga's default  `ErrorMaskingPlugin` and relayed to the client instead of bubbled to the server console / sentry / whatever.

I think I have 2 options - I can write a different `ErrorMaskingPlugin` which handles that error type differently, or I can somehow change the error type thrown when there is a problem like the one I listed.

Do you have any thoughts on the better approach? I'm not sure if it's Pothos throwing the error in question, or another package further down the stack.

Thank you for the help, I'm learning a lot about how all of this is put together and really enjoying Pothos!

**Comment by hayes** [comment]
It's probably not Pothos throwing the error, Pothos will throw very few runtime errors (Mostly just things from plugins like authorization and validation, etc).

I have found in most sufficiently complex GraphQL APIs you end up writing your own error processing logic (maybe as a plugin) that knows how to handle different types of errors your API might throw.  Changing the error type may be possible, but I think going down the road of writing your own error handling logic is likely a more sustainable approach (but may be more work).

**Comment by kelly-lv-labs** [comment]
If anyone finds this via search with a similar problem, this is how I resolved and it is working well now! As hayes pointed out, not really related to Pothos at all.

```javascript

const yoga = createYoga({
  schema: schema,
  plugins: [
    useMaskedErrors({
      // @ts-ignore types for this just seem wrong - this seems
      // to do what we want
      maskError: (gqlError: GraphQLError, _message: string) => {

        console.error(gqlError);
        Sentry.captureException(gqlError);

        const err = gqlError.originalError as Error;
        if (err instanceof ClientFacingError) {
          throw new GraphQLError(err.message);
        }
        throw new GraphQLError('Something went wrong.');
      },
    }),
  ],
  maskedErrors: false,
});

```

And with this error class I can explicitly forward what I want to the client.

```javascript
export class ClientFacingError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ClientFacingError';
  }
}

```
