### ISSUE TITLE
GraphQL Shield and Relay Plugins

### ISSUE THREAD

**Issue by matthawk60** [hayes/pothos#826]
When using these two plugins together I get a type error on relayOptions

```Type '{ clientMutationId: "omit"; cursorType: "ID"; }' is missing the following properties from type '{ idFieldName?: string; idFieldOptions?: Partial<Omit<ObjectFieldOptions<ExtendDefaultTypes<{ Scalars: { DateTime: { Input: Date; Output: Date; }; ID: { Output: string | number; Input: string; }; }; PrismaTypes: PrismaTypes; }>, ... 4 more ..., PageInfoShape>, "args" | ... 2 more ... | "nullable">>; ... 29 more ...;...': nodeQueryOptions, nodesQueryOptionsts(2739)```

Using @ts-ignore allows it to function correctly.  The error goes away when I remove the GraphQL Shield plugin.  I copied the plugin exactly as in your example.

**Comment by hayes** [comment]
The plugin as written makes the shield option required for query and mutation fields.  You can either update the plugin to make these options, or you can define the required options for the node/nodes fields by adding node(s)QueryOptions to relayOptions

**Comment by matthawk60** [comment]
Thanks that worked great.
