### ISSUE TITLE
[ Help ] plugin-federation and plugin-scope-auth example or sample please?

### ISSUE THREAD

**Issue by chrisgate** [hayes/pothos#829]
I am currently banging my head on the wall on plugin-federation and plugin-scope-auth.

I will appreciate any sample on integrating plugin-federation with other plugins like the plugin-scope-auth validation plugin below did not do the justice like that.
https://github.com/hayes/pothos/blob/main/examples/prisma-federation/src/gateway.ts
https://github.com/hayes/pothos/blob/main/packages/plugin-federation/tests/example/gateway.ts

Thanks and Cheers

**Comment by hayes** [comment]
The federation plugin doesn't have any special integration with other plugins, and features of other plugins should just work as described in their documentation.

There are some details of how subgraphs are queried and executed that may not work well with all plugins (eg the relay node pattern can be much more complicated to set up)

resolveReference resolvers don't have any special integration with the scope auth plugin, but type and field level checks for those entities should work as expected.

Do you have more details on what specifically you are trying to do?

**Comment by chrisgate** [comment]
Thank you for this great library and reply.
I don't know how to explain it but I am having feelings I am over configuring everything. Below are my server, servers, gateway and service configuration
Service: same with every services;
`export const builder = new SchemaBuilder<{
  Context: Context;
  Objects: Objects;
  AuthScopes: {
    public: boolean;
    isAuthorised: boolean;
    employee: boolean;
    deferredScope: boolean;
    accessPermission: AccessPermission;
  };
  PrismaTypes: PrismaTypes;
  Scalars: {
    ID: { Input: string; Output: string | number };
  };
}>({
  scopeAuthOptions: {
    treatErrorsAsUnauthorized: true,
    unauthorizedError: (parent, context, info, result) =>
      new GraphQLError(`Not authorized`),
  },
  plugins: [ScopeAuthPlugin, DirectivesPlugin, PrismaPlugin, FederationPlugin],
  authScopes: (context) => ({
    public: !context?.token,
    isAuthorised: !!context?.token.userId,
    // eagerly evaluated scope
    employee: !!context?.token.company,
    // evaluated when used
    deferredScope: () => !!context?.token.company,
    // scope loader with argument
    accessPermission: (perm) => context.token.permissions.includes(perm),
  }),
  prisma: {
    client: db,
  },
});`
servers.ts ;
`
export async function startServers() {
  return Promise.all(
    servers.map(async ({ server, name }) => {
      const { url } = await startStandaloneServer<Context>(server, {
        listen: { port: 0 },
        context: async ({ req}) => {
          const token = req.headers.authorization ?? "";
          const jwtData = decodeJWT(token) as PayloadType;
          console.log("Servers: retrieved token " , jwtData);
          console.log("Servers: retrieved headers",req.headers);
          return { token: jwtData,db:db };
          // return { prisma, accountId, accountType, pubsub };
        },
        // Your async context function should async and
        // return an object
        // context: async ({ req, res }) => {
        //   const token = req.headers.authorization ?? "";
        //   const jwtData = decodeJWT(token) as PayloadType;

        //   return { ...jwtData };
        //   // return { prisma, accountId, accountType, pubsub };
        // },
      });

      console.log(name, url);

      return { name, url, server };
    })
  );
}

`
gateway.ts ;
`export function createGateway(configs: { name: string; url: string }[]) {
  return new ApolloServer<Context>({

    plugins: [ApolloServerPluginInlineTraceDisabled()],
    gateway: new ApolloGateway({
      // serviceList: configs,
      supergraphSdl: new IntrospectAndCompose({
        subgraphs: configs,
      }),
      buildService: ({ url }) =>
        new AuthenticatedDataSource({
          apq: true,
          url,
        }),
      debug: isProd ? false : true,
    }),
  });
}`
latsly serve.ts the entry point;

`startServers()
  .then(async (configs) => {
    const server = createGateway(configs);

    const { url } = await startStandaloneServer<Context>(server, {
      listen: {
        port: Number(gatewayPort),
      },
      context: async ({ req, res }) => {
        const token = req.headers.authorization ?? "";
        const jwtData = decodeJWT(token) as PayloadType;
        console.log("startStandaloneServer: retrieved token ", token);
        console.log("startStandaloneServer: retrieved headers ", req.headers);
        return { token: jwtData, db: db };
        // return { prisma, accountId, accountType, pubsub };
      },
    });

    console.log(`🚀 Server ready at ${url}`);
  })
  .catch((error) => {
    throw error;
  });`

@hayes  i am thinking i am over doing this context configurations.

Thanks

**Comment by chrisgate** [comment]
lastly, before I go on rat hole......Subscription won't work with Federation, right?

**Comment by hayes** [comment]
Looks like your auth scopes setup is just copying all the examples from the docs, you probably want to define scopes that actually make sense for you app. 

Nothing else in here looks overly complicated

**Comment by chrisgate** [comment]
you are right.............
this is my example app and I always love to stay close to docs and when it works then start changing it to mean my application needs.

I love to know if @pothos/plugin-smart-subscriptions will work with federation though.

**Comment by hayes** [comment]
Unfortunately Smart subscriptions will not work with federation

**Comment by chrisgate** [comment]
It is working now thank you.....

It is not only working I could use your solution here https://github.com/hayes/pothos/issues/103 to integrate CASL with it and everything is working together.

Cheers @hayes  and Thank you
