### ISSUE TITLE
`totalCount` on `relatedConnection` doesn't apply the `where` filter

### ISSUE THREAD

**Issue by figitaki** [hayes/pothos#831]
I am trying to use the `totalCount` field on a `relatedConnection` with the `pothos-prisma` and `pothos-relay` plugins. I am setting both `totalCount: true` and using the `query` option to provide a `where` filter to the prisma query. Here's a simplified example:

```typescript
builder.prismaNode('User', {
  id: { field: 'id' },
  fields: t => ({
    posts: t.relatedConnection('posts', {
      cursor: 'id',
      args: { draft: t.arg.boolean({ required: false }) },
      totalCount: true, // I expect the total count to also apply the where clause returned by query below
      query: ({ draft }) => ({
        // Maybe this hack has something to do with it?
        where: { draft: typeof draft === 'boolean' ? draft : undefined  }
      })
    })
  })
})
```

Let's assume we have an example database.
* 1 `User`
* 4 `Post` objects
  * 2 with `draft: true`
  * 2 with `draft: false`
 
When I pass the following query:
```graphql
query DraftPosts {
  user {
    posts(draft: true) {
      totalCount
    }
  }
}
```

I would expect to get the following result:
```js
{ data: { user: { posts: { totalCount: 2 } } } }
```

Instead, I get the following result:
```js
{ data: { user: { posts: { totalCount: 4 } } } }
```

This leads me to believe there's an issue with the application of the `query.where` to the aggregation query used to resolve the `totalCount` field on `relatedConnection`.

**Comment by hayes** [comment]
you can set `filterConnectionTotalCount: true` in in the prisma options when setting up the builder.  Prisma did not support this at the time this plugin was released, and changing the existing behavior would be a breaking change, which is why it's behind a flag.  This will become the default in the next major version.

**Comment by figitaki** [comment]
Amazing, thanks for the quick response. In case anyone else ends up with this issue, I also had to [enable the `filteredRelationCount` preview feature](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#filter-the-relation-count) in my `schema.prisma`. 

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["filteredRelationCount"]
}
```

Then by passing the above option to the `SchemaBuilder` constructor everything worked like a charm!

```js
const builder = new SchemaBuilder<...>({
  plugins: [PrismaPlugin, RelayPlugin],
  prisma: {
    client,
    filterConnectionTotalCount: true
  }
})
```
