### ISSUE TITLE
Prisma Pothos: prismaObject creates type that exceeds maximum length compiler will serialize

### ISSUE THREAD

**Issue by kingston** [hayes/pothos#838]
First off, thanks for a great project. Switched over from Nexus to Pothos and it's been cool to see types work instantly.

I recently was extended my schema and I encountered a new Typescript error on two of my existing Prisma object types.

> The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

```
// error happens on objectType
export const objectType = builder.prismaObject(...)
```

It appears the inferred type from prismaObject exceeded the maximum length of the inferred type Typescript would support. I tried digging in further and I was able to discover that it appears related to the Relations field in the PrismaTypes generated typing. If I remove one of the relations on the prisma object from the generated code, the error goes away.

I looked into the inferred type on VSCode and I saw (using example data here):
```
PrismaObjectRef<PrismaModelTypes & {
    Name: "SocialMediaSite";
    Shape: SocialMediaSite;
    Include: Prisma.SocialMediaSiteInclude;
    Select: Prisma.SocialMediaSiteSelect;
    OrderBy: Prisma.SocialMediaSiteOrderByWithRelationInput;
    WhereUnique: Prisma.SocialMediaSiteWhereUniqueInput;
    Where: Prisma.SocialMediaSiteWhereInput;
    RelationName: "pages" | "handles" | "image";
    ListRelations: never;
    Relations: {
        Pages: {
            Shape: SocialMediaSitePage | null;
            Types: {
                Name: "SocialMediaSitePage";
                Shape: SocialMediaSitePage;
                Include: Prisma.SocialMediaSitePageInclude;
                Select: Prisma.SocialMediaSitePageSelect;
                OrderBy: Prisma.SocialMediaSitePageOrderByWithRelationInput;
                WhereUnique: Prisma.SocialMediaSitePageWhereUniqueInput;
                Where: Prisma.SocialMediaSitePageWhereInput;
                RelationName: "site" | "subscription" | "urls";
                ListRelations: never;
                Relations: {
                    site: {
                        Shape: SocialMediaSite | null;
                        Types: any;
                    };
                    subscription: {
                        Shape: SocialMediaSubscription;
                        Types: {
                            Name: "SocialMediaSubscription";
                            Shape: SocialMediaSubscription;
```

It looks like it's including the entire relationship tree into the type which is probably causing it to exceed the maximum length I'm guessing?

Is there a way to simplify the type on the ObjectRef so that it doesn't overload the Typescript type inference system?

**Comment by hayes** [comment]
Hey, sorry you are running into this issue.

I haven't seen this specific issue before, so I don't have a good known solution.  If you could provide a reproduction (not sure how hard it would be to extract/anonymize the relevant part of your prisma schema) that could be helpful.

I have used schemas with a large number of relations without issue, so I'm curious if there is a specific pattern that is causing this issue.  Unfortunately without a way to reproduce the issue I probably can't do much other than speculate.  It would definitely be possible to provide a way to exclude certain relationships from the generated output, but that doesn't feel like a satisfying answer, and figuring out which relations are causing problems would probably be pretty complex.

Without digging further, I would suspect that the solution may be removing the `Types` part from the relations map, and including a `Name` instead that can be used to dynamically load the rest of the types.  But this will be a fairly complex change, and I wouldn't want to try it without having a good way to verify it resolves the underlying issue.

**Comment by hayes** [comment]
@kingston can you try out the snapshot version published in the PR description of https://github.com/hayes/pothos/pull/839?

I'm not sure if this would actually help, this could also easily make the issue worse, but worth testing out

**Comment by kingston** [comment]
Hi! Thanks for the super fast response. I really appreciate you looking into it. I checked out that branch and it actually worked perfectly once I built it locally. The inferred type now fits inside the VSCode preview instead of getting truncated.

Would you still need an anonymized reproduction case? I might be able to pull something together but anonymizing the Prisma schema may be a bit tricky since I suppose it's by the size of the schema.

**Comment by hayes** [comment]
I may be able to release this without a reproduction.  It's seems pretty simple, but this is actually a fairly complex change, and I'll need to do a lot of testing to ensure this won't break anything else.  I'll probably need a couple days to check a few things out, and see if there is a cleaner way to get the same effect.  A reproduction would be nice, but not required.

**Comment by kingston** [comment]
Thanks - I'm working on building a repro case that can be anonymized. It's a bit tricky since I don't know of a good way to rename all the models/field names quickly, but I was able to figure out that setting `declaration: true` in tsconfig.json was causing the error to occur so maybe adding that to a complex model will also cause it to recur.

**Comment by hayes** [comment]
just published a new version that should have this fix, let me know if you still have issues after upgrading

**Comment by kingston** [comment]
Yup this version works perfectly. Thank you very much!
