### ISSUE TITLE
exposeID("id") gives error: Argument of type '"id"' is not assignable to parameter of type 'undefined'.

### ISSUE THREAD

**Issue by dfunklove** [hayes/pothos#841]
This is similar to the issue I opened recently, but slightly different.  I'm using the prisma plugin.

Here's my npm list:
├── @pothos/core@3.28.0
├── @pothos/plugin-prisma@3.43.0
├── @prisma/client@4.11.0
├── @types/node@18.15.3
├── apollo-server@3.12.0
├── graphql-scalars@1.20.4
├── graphql@16.6.0
├── prisma@4.11.0
├── ts-node-dev@2.0.0
└── typescript@4.9.5

My prisma schema:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator gen {
  provider = "prisma-client-js"
}

generator pothos {
  provider = "prisma-pothos-types"
}

model lessons {
  id         BigInt    @id @default(autoincrement())
  notes              String?
}
```

My pothos schema:
```
import SchemaBuilder from "@pothos/core";
import { DateTimeResolver } from "graphql-scalars";
import PrismaPlugin from "@pothos/plugin-prisma";
import type PrismaTypes from "@pothos/plugin-prisma/generated";
import { prisma } from "./db";

export const builder = new SchemaBuilder<{
  Scalars: {
    DateTime: { Input: Date; Output: Date };
  };
  PrismaTypes: PrismaTypes;
}>({
  plugins: [PrismaPlugin],
  prisma: {
    client: prisma,
  },
});

builder.addScalarType("DateTime", DateTimeResolver, {});

builder.prismaObject("lessons", {
  fields: t => ({
      id: t.exposeID("id"),
      notes: t.exposeString("notes", {nullable: true}),
      time_in: t.expose("time_in", {type: "DateTime"}),
      time_out: t.expose("time_out", {type: "DateTime", nullable: true}),
  })
})

builder.queryType({
  fields: t => ({
    lessons: t.prismaField({
      type: ['lessons'],
      resolve: async (query, root, args, ctx, info) => {
        return prisma.lessons.findMany({ ...query });
      }
    })
  })
})

export const schema = builder.toSchema({});
```

My query:
```
query lessons {
  lessons {
    id
    notes
    time_in
    time_out
  }
}
```

There is only one row in the DB and it has an ID.

I run "npx prisma generate" before getting the error.

**Comment by hayes** [comment]
Again, id: t.exposeID() doesn't specify what column you are exposing, you want to use `id: t.exposeID('id')`

**Comment by hayes** [comment]
Oh, actually, since your column is a BigInt, you either need to update the supported types for your ID scalar, or use:

`id: t.id({ resolve: lesson => lesson.id.toString() })`

**Comment by dfunklove** [comment]
Sorry, I didn't update my code to reflect the new usage of exposeID('id') when I copy-pasted it.

Is this how to update the supported types for the ID scalar?

```
export const builder = new SchemaBuilder<{
  Scalars: {
    DateTime: { Input: Date; Output: Date };
    ID: { Input: BigInt; Output: BigInt };
  };
  PrismaTypes: PrismaTypes;
}>({
  plugins: [PrismaPlugin],
  prisma: {
    client: prisma,
  },
});

builder.addScalarType("DateTime", DateTimeResolver, {});
builder.addScalarType("ID", BigIntResolver, {});
```

This produces a different error in the GraphQL output: "ID cannot represent value: 1"

**Comment by hayes** [comment]
Sorry, forgot to follow up here.  I think this may be an issue with the built-in ID scalar, and it just doesn't know how to serialize BigInt values.  I think for now you are probably stuck doing something like `t.id({ resolve: thing => String(thing.id })`, or using a custom BigInt scalar rather than the ID type.
