### ISSUE TITLE
[ Help ] how do I upload files using Pothos? Thank you

### ISSUE THREAD

**Issue by chrisgate** [hayes/pothos#843]
I need to upload e.g images or Files through Mutation. Please.

**Comment by hayes** [comment]
Yoga supports file uploads, you can see an example here: https://github.com/dotansimha/graphql-yoga/blob/main/examples/file-upload-nextjs-pothos/schema.ts

**Comment by chrisgate** [comment]
Thank you @hayes  ,
I have to go back to Yoga.....The way I move back and forth from Apollo Server to Yoga shows I am new in the Graphql world and I don't know what I will meet in the future.
