### ISSUE TITLE
Cannot create property `pos` on string `PrismaTypes`

### ISSUE THREAD

**Issue by bitabs** [hayes/pothos#852]
Hi there,

Not sure why but for some reason this is being thrown unexpectedly. FYI, I don't have `pos` property anywhere. I'm trying to run `prisma generate` which fails.

<img width="2048" alt="Screenshot 2023-03-24 at 23 43 04" src="https://user-images.githubusercontent.com/16179773/227663037-4fc366d9-ff43-4036-a994-b61e622344cc.png">

If I remove pothos generator, then `prisma generate` works. So I'm suspecting this is to do with Pothos?

<img width="1078" alt="Screenshot 2023-03-24 at 23 46 39" src="https://user-images.githubusercontent.com/16179773/227663166-1eac45e6-d1f3-4f45-812a-337d7dce28cd.png">

<img width="1039" alt="Screenshot 2023-03-24 at 23 47 21" src="https://user-images.githubusercontent.com/16179773/227663229-feb33e08-8f9f-4af6-a413-6d640b650212.png">

**Comment by hayes** [comment]
Hey, did you recently upgrade to typescript@5.0?  If so, can you try upgrading to the latest version of the prisma plugin?  There were some breaking changes typescript 5.0 that caused issues with the generator

**Comment by bitabs** [comment]
You are an absolute legend! It was exactly that. Closing this as it has been resolved 🙇🏻
