### ISSUE TITLE
Infer type from object ref

### ISSUE THREAD

**Issue by mmahalwy** [hayes/pothos#862]
I often find myself creating objects like this:

```ts
const SomeObject = builder.objectRef<{ a: number, b: number }>('SomeObject').implment({...});
```

Ideally, would be great to infer the type from the object similar to zod's `z.infer<typeof >`

So something along the lines of `Pothos.infer<typeof SomeObject>` that would return the type.

**Comment by hayes** [comment]
This could probably be added at some point.  In the mean time, this is very easy to define yourself:

```ts
type InferObjectRef<Ref extends ObjectRef<unknown>> = Ref extends ObjectRef<infer T> ? T : never;

type Shape = InferObjectRef<typeof YourRef>;
```

**Comment by dylanlarrivee** [comment]
@hayes I would love to try and contribute to Pothos and saw that this is a good first issue. I am still pretty new to this so just wondering if there are any resources you might be able to point me to that would help me get going on understanding how Pothos works under the hood?

**Comment by hayes** [comment]
@dylanlarrivee definitely always happy to have new contributors.

Pothos is unfortunately not set up to be very approachable for new contributors, but this issue is fairly isolated to adding a fairly simple type.

Adding this would probably consist of the parts:

1. A new type helper for inferring types from refs
    * This might make sense to split into an Input and Output shapes
    * Looking at how the zod infer helper works might be a good place to start.  
    * The helpers would probably be defined somewhere in `packages/core/src/types/utils`
    * I'm not 100% sure what the best API, name, or location for these is, figuring out some of these details is part of the work needed for this.  The helpers themselves should be pretty easy to write.
    * For the actual implementation, you could likely accept the a `BaseTypeRef` which is extended by all the different type refs in Pothos
2. Tests
    * Adding tests for types isn't always necissary, but can be nice.  This is often more implicit than explicit in pothos.
    * What I would do is just add some usage of the new type helpers in one of the example schemas in `core/tests/examples`.  This "tests" the behavior implicitly because type-checking should fail for the usage of the helpers if the types break. 
3.  Documentation
     * documentation lives in the `website` directory in a series of `.mdx` files which are mostly just standard markdown
     * You can run the docs site locally by running `pnpm dev` in the website directory

Hope this helps!

**Comment by dylanlarrivee** [comment]
Awesome, thanks for the info. I will check this out.

I accidentally deleted my original comment so re posting here for visability:
"I would love to try and contribute to Pothos and saw that this is a good first issue. I am still pretty new to this so just wondering if there are any resources you might be able to point me to that would help me get going on understanding how Pothos works under the hood?"

**Comment by wiktor-obrebski** [comment]
I often find myself in need of this feature - it would be fantastic to have it built-in.

**Comment by focux** [comment]
I just found this issue trying to find a way to infer an input type, it would be a very useful addition.

**Comment by hayes** [comment]
Added an API for inferring types from refs: https://pothos-graphql.dev/docs/guide/inferring-types

**Comment by mmahalwy** [comment]
amazing! Thanks @hayes
