### ISSUE TITLE
Prisma preview feature `extendedWhereUnique` is not type-compatible with indirect relations as connections using `plugin-prisma`

### ISSUE THREAD

**Issue by jhanschoo** [hayes/pothos#863]
## Working example and setup notes

Minimal working example based off the `relay-prisma` example: https://github.com/jhanschoo/relay-prisma-bug

note that `npm` is used here instead of `pnpm`, and I was using the latest node v18.

## Issue

When `extendedWhereUnique` is enabled, the `select` field of the `t.connection` gets an error when using the technique described at https://pothos-graphql.dev/docs/plugins/prisma#indirect-relations-as-connections . See the working example for reproduction instructions and a workaround. Note that execution-wise it seems to work correct too.

## Potential root cause

It seems like the root cause is that `getCursorParser` function in `@pothos/plugin-prisma/src/util/cursors.ts` returns a shape that is too general, and nothing in between that definition and the in-library coercions down to its point of use at e.g. `postConnectionHelpers.getQuery` specialize it sufficiently.

Considering that this involves a 3rd-party library's preview feature, intersecting the use of a plugin and its relay feature (albeit likely a popular one), and has a simple, minimally invasive workaround, this does not seem to need resolution with any priority.

**Comment by hayes** [comment]
Thanks for the detailed report and reproduction!

Just pushed a fix here: https://github.com/hayes/pothos/commit/80c62446cc92b8a861246323bdc2ce0dbfe80af2

It should be published in the next few minutes!

**Comment by jhanschoo** [comment]
Wow that's some turnaround! Thanks haha
