### ISSUE TITLE
prismaUtils  Static generator prismaWhere without AND OR NOT

### ISSUE THREAD

**Issue by lilucode** [hayes/pothos#870]
https://github.com/hayes/pothos/blob/main/packages/plugin-prisma-utils/tests/examples/codegen/generator.ts

Why does the builder.prismaWhere api fields in the statically generated script not contain AND OR NOT fields？

**Comment by hayes** [comment]
No specific reason, it was just not something I implemented.  The generators are meant as examples or starting places, adding the specific functionality you want (like AND, OR,  NOT) should be pretty straightforward
