### ISSUE TITLE
ValidationPlugin: Zod types seem to mismatch what Pothos expect

### ISSUE THREAD

**Issue by danieljvdm** [hayes/pothos#871]
`const ipSchema = zod.string().ip();` returns a `ZodString` type

When I use it here:

```ts
 t.field({
    args: {
      endpointId: t.arg.id({ required: true }),
      ip: t.arg.string({
        required: true,
        validate: {
          schema: ipSchema,
        },
      }),
    },
    ...
```

I get a bunch of TypeErrors:

```Type '{ schema: zod.ZodString; }' is not assignable to type 'ValidationOptions<string> | undefined'.
  The types of 'schema._def.errorMap' are incompatible between these types.
    Type 'import("/redacted/node_modules/zod/lib/ZodError").ZodErrorMap | undefined' is not assignable to type 'Zod.ZodErrorMap | undefined'.
      Type 'import("/redacted/node_modules/zod/lib/ZodError").ZodErrorMap' is not assignable to type 'Zod.ZodErrorMap'.
        Types of parameters 'issue' and 'issue' are incompatible.
          Type 'Zod.ZodIssueOptionalMessage' is not assignable to type 'import("/redacted/node_modules/zod/lib/ZodError").ZodIssueOptionalMessage'.
            Type 'ZodInvalidLiteralIssue' is not assignable to type 'ZodIssueOptionalMessage'.
              Property 'received' is missing in type 'Zod.ZodInvalidLiteralIssue' but required in type 'import("/redacted/node_modules/zod/lib/ZodError").ZodInvalidLiteralIssue'.ts(2322)```

Zod version is 3.21.4, Pothos Validation is 3.9.0

**Comment by hayes** [comment]
This looks a little like you have multiple versions of zod installed, is your schema coming from another package in a monorepo or something?

**Comment by danieljvdm** [comment]
@hayes, it's a monorepo but just has one version of Zod. There is one dependency with a slightly older version of Zod but the installed version that this should be using is `3.21.4`

**Comment by hayes** [comment]
I haven't been able to reproduce, this is an example of this working for me:

https://stackblitz.com/edit/typescript-ka6und?file=index.ts

If you can provide some more details on how to reproduce the issue, happy to help debug what's going in

**Comment by hayes** [comment]
Since I haven't heard back here, I am going to close this, but happy to take a look if you can provide more details!
