### ISSUE TITLE
PothosError: builder.prismaNode requires @pothos/plugin-relay to be installed

### ISSUE THREAD

**Issue by MoSattler** [hayes/pothos#874]
Hi! 

Just trying out Pothos in a fresh project, and wanted to get the prisma integration + relay to run.

installed versions:
```
"@pothos/core": "^3.29.0",
"@pothos/plugin-prisma": "^3.47.2",
"@pothos/plugin-relay": "^3.39.0",
```

So everything is installed. But I keep getting the error
```
PothosError: builder.prismaNode requires @pothos/plugin-relay to be installed
```

code in question:
```ts
const builder = new SchemaBuilder<{
  PrismaTypes: PrismaTypes;
}>({
  plugins: [RelayPlugin, PrismaPlugin],
  prisma: {
    client: prisma,
    filterConnectionTotalCount: true,
  },
  relayOptions: {
    clientMutationId: 'omit',
    cursorType: 'String',
  },
});

builder.prismaNode('User', {
  id: { field: 'id' },
  fields: (t) => ({
    title: t.exposeString('title'),
    author: t.relation('author'),
  }),
});
```

any idea what I am doing wrong here?

**Comment by richardguerre** [comment]
Ran into the same error but when using Bun instead. If this happens to you when using bun do the following:
1. Delete the `node_modules` directories (you may have multiple if you are in a mono repo).
2. Run the following to clean Bun's cache so that dependencies are installed.
	```sh
	bun pm cache rm
	```
	You can find it at the of [this Bun doc](https://bun.sh/docs/cli/pm).
