### ISSUE TITLE
Support offset pagination for prisma connection

### ISSUE THREAD

**Issue by knpwrs** [hayes/pothos#875]
Prisma supports both offset and cursor pagination: https://www.prisma.io/docs/concepts/components/prisma-client/pagination#-cons-of-offset-pagination

As far as I can tell, the Pothos prisma plugin only supports cursor-based pagination.

While I recognize offset-based pagination doesn't scale, I have a small use case where I am ordering by a column that is not unique but I would still like to be able to paginate.

**Comment by hayes** [comment]
The Prisma plugin can handle offset pagination in a number of different ways.  The issue is there is no good GraphQL standard that is widely adopted enough to be part of the core plugin.

For the most simple approach you can add offset/limit args and use them in a query on any list relation

**Comment by hayes** [comment]
here is an example of a limit (but offset can work the same way) https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/tests/example/schema/index.ts#L168-L178

You can ignore the resolver there

**Comment by hayes** [comment]
Some existing discussion around this here as well: https://github.com/hayes/pothos/discussions/333

**Comment by knpwrs** [comment]
Thank you for that info and for the links. I wound up with this, which seems to work for my use-case:

```ts
const UploadUserComment = builder.prismaObject("UploadUserComment", {
  // ...
});

const UploadRecord = builder.prismaObject("UploadRecord", {
  select: {
    id: true,
  },
  fields: (t) => ({
    // ...
    userComments: t.connection(
      {
        type: UploadUserComment,
        resolve: async (root, args, context, info) => {
          const [res, totalCount] = await Promise.all([
            resolveOffsetConnection({ args }, async ({ offset, limit }) => {
              const query = queryFromInfo({
                context,
                info,
                path: ["edges", "node"],
                typeName: "UploadUserComment",
              });
              return prisma.uploadUserComment.findMany({
                ...query,
                where: { uploadRecordId: root.id, replyingTo: null },
                skip: offset,
                take: limit,
                orderBy: { score: Prisma.SortOrder.desc },
              });
            }),
            prisma.uploadUserComment.count({
              where: { uploadRecordId: root.id },
            }),
          ]);

          return {
            totalCount,
            ...res,
          };
        },
      },
      {
        name: "UploadRecordUserCommentsConnection",
        fields: (t) => ({
          totalCount: t.int({
            resolve: (root) => root.totalCount,
          }),
        }),
      }
    ),
  }),
});
```
