### ISSUE TITLE
Codegen generated type not match resolver arg type

### ISSUE THREAD

**Issue by dylanlarrivee** [hayes/pothos#883]
Hi,
Just starting off with Pothos and loving it so far so thank you for this great tool.

I currently have a monorepo app that has pothos/prisma/postgres backend and nextjs frontend and I have just integrated codegen to be able to use the types generated from the schema in my nextjs app. I was trying to also use the generated types in the backend code but ran into an issue where the codegen generated output type does not match the pothos resolver args type as I would expect and I end up having to use type casting to make typescript happy.  

**Services File Code**

```
// Imported from codegen file
import { QueryGetAllAlertsArgs } from '@gen/src/server.graphql';

export const getAllAlerts = async (args?: QueryGetAllAlertsArgs): Promise<alert[]> => {
  return db.alert.findMany({ orderBy: args?.orderBy ?? undefined });
};

};
```

**Resolver Queries File**
```
const AlertsOrderBy = builder.prismaOrderBy('alert', {
  fields: {
    createTime: true,
    updateTime: true,
  },
});

builder.queryFields((t) => ({
  getAllAlerts: t.prismaField({
    type: ['alert'],
    args: {
      take: t.arg.int(),
      skip: t.arg.int(),
      orderBy: t.arg({ type: AlertsOrderBy }),
    },
    resolve: (_query, _root, args) => getAllAlerts(args as QueryGetAllAlertsArgs),
  }),
}));
```

For the args parameter the type it is show at does not match what codegen and I was wondering if there was a better way to handle this so that I could just pull in any types needed on my backend code from the codegen generate file.

Thanks!
Dylan

**Comment by hayes** [comment]
Could you proved the generated types and the type error you are seeing?  It's hard to say what the issue might be from just this.

If I had to guess, the types generated for your client queries allow either null or undefined for nullable arguments, but not both.  In a resolver, the value may be either null or undefined depending on how the query was sent. 

This is obviously just a guess, and without seeing the types I can't say for sure.   GraphQL code generator has lots of plugins and options, so I have no idea what combination you are using or what might work, but hopefully that gives you somewhere to start looking

**Comment by dylanlarrivee** [comment]
Thanks for the quick response. I had just started looking into the codegen maybeValues and they are set as `maybeValue: 'null | undefined',` so that could def be part of the issue you were describing.

**Generated type**
export type QueryGetAllAlertsArgs = {
  orderBy: InputMaybe<AlertOrderBy>;
  skip: InputMaybe<Scalars['Int']>;
  take: InputMaybe<Scalars['Int']>;
};

**Type error**
Argument of type 'InputShapeFromFields<{ take: InputFieldRef<number | null | undefined, "Arg">; skip: InputFieldRef<number | null | undefined, "Arg">; orderBy: InputFieldRef<alertOrderByWithRelationInput | null | undefined, "Arg">; }>' is not assignable to parameter of type 'QueryGetAllAlertsArgs'.
  Types of property 'orderBy' are incompatible.
    Type 'alertOrderByWithRelationInput | null | undefined' is not assignable to type 'InputMaybe<T>'.
      Type 'alertOrderByWithRelationInput' is not assignable to type 'InputMaybe<T>'.ts(2345)
(parameter) args: InputShapeFromFields<{
    take: InputFieldRef<number | null | undefined, "Arg">;
    skip: InputFieldRef<number | null | undefined, "Arg">;
    orderBy: InputFieldRef<Prisma.alertOrderByWithRelationInput | null | undefined, "Arg">;
}>

**Comment by dylanlarrivee** [comment]
I also just found out that codegen has the ability to map external types into the codegen file so I just started looking into that for bringing in some prisma types to see if I can make it work that way as well.

**Comment by hayes** [comment]
Mapping to Prisma types will likely be your best bet.  The Prisma utils plugin does some conversation of types to make Prisma happy, so it is somewhat expected that generic graphql generated types wouldn't match up exactly.  

Based on what you shared, the generated types would likely work well for any non-prisma types though.

**Comment by dylanlarrivee** [comment]
Ok cool, I will play around with that. Thanks
