### ISSUE TITLE
federation-plugin: toSubGraphSchema is not a function

### ISSUE THREAD

**Issue by macrozone** [hayes/pothos#899]
i followed the guide on https://pothos-graphql.dev/docs/plugins/federation and i get

```

export const schema = builder.toSubGraphSchema({
                              ^
TypeError: builder_1.builder.toSubGraphSchema is not a function

```

its a bit odd, the types say that this function exist, but the builder does not have this function.

i made sure i added the plugin:

```
export const builder = new SchemaBuilder<SchemaTypes>({
  plugins: [PrismaPlugin, PrismaUtils, DirectivePlugin, FederationPlugin],

  prisma: {
    client: prisma,
    filterConnectionTotalCount: true,
  },
});
```

i also tried to remove the other plugins to see whether there are some incompatibilities.

versions i use:

<img width="366" alt="Bildschirmfoto 2023-05-03 um 22 01 37" src="https://user-images.githubusercontent.com/1972353/236035015-d260507c-7ab0-4ac3-a26d-df89d799625d.png">

additionaly, all other methods attached by this plugin do not work, like schema.selection

seems like this is not executed: https://github.com/hayes/pothos/blob/main/packages/plugin-federation/src/schema-builder.ts

as this is a side effect i am unsure whether this is a good practise to extend on the schema-builder prototype like that, it seems to depend now wheter this file is imported or not

**Comment by hayes** [comment]
Nothing obvious here, but it looks like your error is coming from some sort of compiled/generated/bundled code.  It's possible what ever tool you are using to build your app is somehow eliminating excluding the part of the plugin that defines that function.  The function is defined here: https://github.com/hayes/pothos/blob/main/packages/plugin-federation/src/schema-builder.ts and is imported from the plugins index file.

**Comment by macrozone** [comment]
> Nothing obvious here, but it looks like your error is coming from some sort of compiled/generated/bundled code. It's possible what ever tool you are using to build your app is somehow eliminating excluding the part of the plugin that defines that function. The function is defined here: https://github.com/hayes/pothos/blob/main/packages/plugin-federation/src/schema-builder.ts and is imported from the plugins index file.

its a freshly created project with just ts-node to run the ts code directly on node 18. I also tried bundling it with esbuild and then run the compiled js with the same result. Both environments may tree-shake out the code as it relies on a side effect by importing the file you linked. Bundlers usulay should not tree-shake away code with potential side effects though (unless you mark your package as side-effect free) and in my case there isn't even a bundler running (not sure though how ts-node handles this internally)

**Comment by macrozone** [comment]
what is smelly is that https://github.com/hayes/pothos/blob/main/packages/plugin-federation/src/index.ts only imports a specific export from https://github.com/hayes/pothos/blob/main/packages/plugin-federation/src/schema-builder.ts 

`import { entityMapping } from './schema-builder'`

but this file has other exports (which are never imported anywhere as well as side-effects.

other plugins do a `import "./schema-builder"` to explicitly import it for its side-effects.

i advice to remove any export from this file and move them somwhere else and import it for its side effects. E.g. if you would no longer need `entityMapping`, you would no longer import the file at all

**Comment by hayes** [comment]
All plugins use the same pattern for extending Pothos classes.  Do the other plugins you are using successfully add methods?

It might be worth checking if the federation plugin is somehow referencing a different copy of Pothos.

Are you using cjs or esm as the target module type for your app?

**Comment by macrozone** [comment]
> All plugins use the same pattern for extending Pothos classes. Do the other plugins you are using successfully add methods?
> 
> It might be worth checking if the federation plugin is somehow referencing a different copy of Pothos.
> 
> Are you using cjs or esm as the target module type for your app?

ts-config:

```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "strict": true
  }
}
```

while writing this i checked the typescript version, and it seems i used a relativly ancient one (4.5.4).

I now use 5.0.4 and the error is gone!

i am not sure though why 4.5.4 tree-shakes that away though...

**Comment by hayes** [comment]
Nice, glad you got it figured out.  Good catch on the import.  Agree that should be updated to pull named imports from somewhere else, I'll get that updated later today

**Comment by hayes** [comment]
published a new version of several packages that avoid importing from files that have side effects.  Hopefully that will prevent anyone from running into this in the future.  Thanks for the report, but also happy this is not an issue in newer typescript versions.
