### ISSUE TITLE
Prisma-utils inputs can't set null values

### ISSUE THREAD

**Issue by cinan** [hayes/pothos#909]
I found prisma utils normalizes input (`normalizeInputObject` function) so all `nulls` are converted into `undefined`. This way prisma won't set `null` values where user intended to (more: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined).

In example below I want to set `Page.parent` to null, so I call `mutation { updatePage(data: { parent: null }) { ... } }`, but prisma would never set `parent` value, because it's `undefined` in the end.

```js
builder.prismaUpdate('Page', {
  fields: t => ({
    parent: t.string(),
  }),
})
```

As a workaround in yarn I patched `@pothos/plugin-prisma-utils` and replaced `normalizeInputObject` return value with `object`.

**Comment by arimgibson** [comment]
@hayes mind if I take a stab at a fix for this?

**Comment by hayes** [comment]
That would be great!

**Comment by ahmedB7r** [comment]
facing the same problem

**Comment by hayes** [comment]
@arimgibson did you make any progress on this? would love to get a fix for this out soon, but don't want to duplicate effort if you've already been working on this.

**Comment by hayes** [comment]
For context, I think this may be as simple as removing this extension here: https://github.com/hayes/pothos/blob/5ac6147fed6c4cc951858d0a2bb4c197e4a362e3/packages/plugin-prisma-utils/src/schema-builder.ts#L441

The plugin currently normalizes any object with this extension set (by replacing all nulls with undefined).  This makes sense for filters, but as mentioned here causes issues for updates.  Should be very easy to fix.  Sorry for the delay in getting to this, I've had a lot of other things on my plate and this issue fell through the cracks

**Comment by arimgibson** [comment]
> @arimgibson did you make any progress on this? would love to get a fix for this out soon, but don't want to duplicate effort if you've already been working on this.

I started but didn't find any quick fixes, meant to bring back to you to discuss some more complicated ones. From what I saw, that `normalizeInputObject` function's coercion to undefined is necessary for tests to pass, as some operations specifically need to be undefined instead of null. My main idea would be to go through the code and make sure the falsy values specified are correct, then remove those lines from the normalizeInputObject function. That would leave it up to the user to know whether they should use `null` or `undefined`

**Comment by hayes** [comment]
@arimgibson `normalizeInputObject` is definitely necissary for a lot of the types.  Maybe what you can do instead would be to set an additional `pothosPrismaNullableKeys` extension (or modify the existing extension to accept options like nullable keys).

Then set that to the list of nullableFields to something like the following (just inside the `builder.prismaUpdate` method:

```ts
const nullableFields = model.fields
    .filter((field) => !field.isRequired)
    .map((field) => field.name);
```

**Comment by arimgibson** [comment]
@hayes Mmmm, that makes sense. So instead of the user defining a value of `undefined` or `null`, they would just specify `nullable: true`?

If that's what you're getting at, I'll happily give it a go and at the very least, hopefully get some of the work out of the way for you. You'd know best about the side effects and things of this change if present

**Comment by hayes** [comment]
The data is already available in the Prisma schema.  The code I pasted should just work inside the prismaUpdate method implementation (it already has all the data about the Prisma fields)

**Comment by hayes** [comment]
I think the whole change should be 2 or 3 lines.  Basically just add what I shared to to prismaUpdate, tack that I'm as an extension, then in the normalize function skip normalization if that extension is set and includes the current field

**Comment by arimgibson** [comment]
Ah okay... I think I get what you're saying. Lemme give it a go and will create a WIP PR; that way you can let me know if I'm on the right track!

**Comment by arimgibson** [comment]
Yeah nope I think I'm stuck @hayes; probably easiest if you can make the change and I'll review the code for next time!

**Comment by hayes** [comment]
pushed a fix here: https://github.com/hayes/pothos/commit/624f2d0505b0eaf1f4f2da215c47016b1485b4e1 (combined with another fix)

**Comment by arimgibson** [comment]
> pushed a fix here: [624f2d0](https://github.com/hayes/pothos/commit/624f2d0505b0eaf1f4f2da215c47016b1485b4e1) (combined with another fix)

Gotcha, good to see how you went about that fix for future reference!

**Comment by YEriin** [comment]
it seems that query with null filter also have the problem

**Comment by hayes** [comment]
@YEriin just published a new version that should allow nulls for nullable fields for filters as well

**Comment by YEriin** [comment]
@hayes thanks, but it seems not to be solved completely and only the direct fields with null can be handled but not for the nested null fields as show below.

paylod:
<img width="551" alt="Screenshot 2023-07-05 at 13 20 31" src="https://github.com/hayes/pothos/assets/24295786/413f85cf-4c1b-49fb-876a-28e0576c2f6d">

server received: 
<img width="303" alt="image" src="https://github.com/hayes/pothos/assets/24295786/857bf49a-1386-4c68-9da4-15f4d0e146bd">

**Comment by YEriin** [comment]
@hayes nice job, thanks.
