### ISSUE TITLE
totalCount on relatedConnection not fetched when part of a fragment

### ISSUE THREAD

**Issue by dantrain** [hayes/pothos#912]
I'm experiencing an issue upgrading `plugin-prisma` above v3.30.0. I have a `relatedConnection` with the `totalCount` option set to `true`. My query which includes the `totalCount` field previously worked but is now failing with "Cannot return null for non-nullable field".

I had a play around and realised the `totalCount` field is included in the query as part of a fragment, like this:

```gql
{
  viewer {
    todos {
      edges {
        node {
          id
        }
      }
      ...TodoFooterFragment
    }
  }
}

fragment TodoFooterFragment on UserTodosConnection {
  totalCount
  completedCount
}
```

If I include it as part of the query directly it works.

Digging around I think the issue may lie here:
https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/prisma-field-builder.ts#L267

It seems `getSelection(['totalCount'])` is returning `null` when `totalCount` is not included in the query directly.

Really appreciate your work on a great library, thank you!

**Comment by hayes** [comment]
Thanks for reporting this.  Just pushed a fix, should be published in a few minutes

**Comment by dantrain** [comment]
Wow that was fast, working great now. Thank you!
