### ISSUE TITLE
Relay plugin doesn't respect auth scope

### ISSUE THREAD

**Issue by MarceloPrado** [hayes/pothos#916]
Hi @hayes!
Before anything else, just wanted to say how well built pothos is. You've been making an incredible job so far! Thanks for your hard work.

I'm working on a project that uses the scope-auth, relay and prisma plugins. I've noticed a potential security issue when running the refetch queries (`node` and `nodes`): they don't seem to respect my auth scopes when the scope in a `builder.node` type.

First of all, I ensured the auth-scope is the first one in the list:

```ts
export const builder = new SchemaBuilder<{
  Context: GraphQLContext;
  PrismaTypes: PrismaTypes;
  AuthScopes: {
    owner: boolean;
  };
}>({
  // Ensure Auth is listed first
  plugins: [ScopeAuthPlugin, RelayPlugin, PrismaPlugin],
  scopeAuthOptions: {
    treatErrorsAsUnauthorized: true,
    unauthorizedError: (parent, context, info, result) => {
      throw new AuthenticationError(
        getEnv() === "dev" ? result.message : undefined
      );
    },
  },
  authScopes: async (context) => ({
    owner: context.user !== null,
  }),
  ... 
})
```

Then, I configured my schema:

```ts
const BankConnectionProviderAccount = builder.objectRef<Account>(
  "BankConnectionProviderAccount"
);
const BankConnectionProviderAccountNode = builder.node(
  BankConnectionProviderAccount,
  {
    id: { resolve: (parent) => parent.id },
    authScopes: { owner: true }, // Not working, `loadOne` and `loadMany` are being called when authorization fails
    loadOne: async (id, ctx) => {
      const bankingProvider = getBankConnectionProviderForUser(ctx.user as User);
      return await bankingProvider.getAccount(id);
    },
    loadMany: async (ids, ctx) => {
      const bankingProvider = getBankConnectionProviderForUser(ctx.user as User);
      return await Promise.all(
        ids.map(async (id) => await bankingProvider.getAccount(id))
      );
    },
    fields: (t) => ({
      name: t.exposeString("name"),
      ...
   }),
   isTypeOf: (parent) => (parent as Account).limitInCents !== undefined,
 })
```

My auth logic ensures there's a JWT in the auth header, and adds the associated user in the GraphQL context. I didn't have any issues with Pothos objects so far. The `authScopes` correctly rejects requests when added to mutation/query fields, and `prismaNode` types. However, for some weird reason, it doesn't work when added to the `builder.node`.

Would appreciate any insights! Maybe I'm understanding how it works.

**Comment by hayes** [comment]
Scopes defined on a type are run after the type is loaded, so this is expected.

Basically, scopes on a type can be defined with a function that receives the loaded object as an argument, so you could for example check if the current object is owned by the user.  For this thanks work, you need to load the object first.


So what I'd expect in your case, would be that loadOne/loadMany would be called, but then when you try to load any properties of that node you'd get authorization errors.

If you want to check auth before loading there are 2 options:  you can add the scopes to the node/nodes fields, and decode the id(s) to determine what type is being loaded/what checks to run, or you can use `await builder.runAuthScopes(context, { owner: true })` to manually check the scopes in side the loadOne/loadMany call.

**Comment by MarceloPrado** [comment]
Got it, that makes sense Michael. Thanks for your explanation. I'm closing this for now since it's expected!
