### ISSUE TITLE
Add builder patter methods for changing default nullability

### ISSUE THREAD

**Issue by Liam-Tait** [hayes/pothos#917]
Add builder pattern style methods to avoid defaults having to be defined twice for [Changing Default Nullability](https://pothos-graphql.dev/#changing-default-nullability). This helps with ergonomics and readability of these options.

- `withDefaultFieldNullability`
- `withDefaultInputFieldRequiredness` 

```diff
-export const builder = new SchemaBuilder<{
-  DefaultFieldNullability: true;
-}>({
-  defaultFieldNullability: true,
-});
+const builder = new SchemaBuilder({}).withDefaultFieldNullability();
```

```diff
-const builder = new SchemaBuilder<{
-  DefaultInputFieldRequiredness: true;
-}>({
-  defaultInputFieldRequiredness: true,
-});
+const builder = new SchemaBuilder({}).withDefaultInputFieldRequiredness()
```

Putting it the builder pattern together would end up as:
```ts
const builder = new SchemaBuilder({})
  .withScalars({ Date: DateScalar })
  .withDefaultFieldNullability()
  .withDefaultInputFieldRequiredness();
```

Related to https://github.com/hayes/pothos/issues/910 & https://github.com/hayes/pothos/pull/914

**Comment by hayes** [comment]
Looking into changing how nullability works in v4, so not sure this would be worth doing right now.  Typescript 5.2 iteration plan mentions investigating some stuff related to partial inference, so that may provide a better way to handle this as well
