### ISSUE TITLE
Prisma + dataloader integration

### ISSUE THREAD

**Issue by MarceloPrado** [hayes/pothos#922]
Hi!
Reading the docs, I couldn't find an example for integrating the dataloader with prisma. 

I have a use case that implements a custom object (`BudgetSuggestion`). This object contains references to two Prisma models: `Category` and `Transaction`:

```tsx
type BudgetSuggestion = {
  categoryId: string;
  limitInCents: number;
  largestTransactionsIds: string[];
};

const BudgetSuggestionObject = builder
  .objectRef<BudgetSuggestion>("BudgetSuggestion")
  .implement({
    description:
      "A suggestion for a budget based on a user's spending history for a category",
    fields: (t) => ({
      category: t.prismaField({
        type: "Category",
        description: "The category this budget suggestion is for",
        resolve: async (query, p) =>
          await db.category.findUniqueOrThrow({
            ...query,
            where: {
              id: p.categoryId,
            },
          }),
      }),
      limitInCents: t.exposeInt("limitInCents", {
        description:
          "How much on average does the user spend on this category? Current month is not accounted.",
      }),
      tenMostExpensiveTransactions: t.prismaField({
        type: ["Transaction"],
        description:
          "The 10 most expensive transactions for this category. It may include the current month",
        resolve: async (query, p, __, ctx) =>
          await db.transaction.findMany({
            ...query,
            where: {
              userId: ctx.user?.id ?? "",
              id: { in: p.largestTransactionsIds },
            },
          }),
      }),
    }),
  });
  ```

Now suppose I'm loading a list of budget suggestions.  In plain GraphQL, instead of triggering multiple SQL queries to resolve categories by ID, the dataloader would trigger a single query:
```
 await db.category.findUniqueOrThrow({
    ...query,
    where: {
      id: { in: dataloader.categoryIds },
    },
  }),
```

When I read the Prisma Plugin feature, I thought this was handled automatically:
> Automatic Query optimization to efficiently load the specific data needed to resolve a query (solves common N+1 issues)

However, it seems the query optimization you're referring to is including/selecting related models, and not bulk-resolving relationships. 

Are there any examples you could point to? Thanks again for the great work!

**Comment by hayes** [comment]
This is an interesting case, and I don't have a great suggestion.  The prisma plugin and the dataloader are 2 very different patterns for query optimization. 

The prisma plugin is all about generating queries that load as much data for a specific sub-selection as possible, looking at nested selections/relations.  This fundamentally makes the loaded data much harder to re-use in a dataloader, because when you are loading data for a very specific sub-selection, it makes it hard to re-use.

The prisma client also has a built in dataloader that triggers in specific cases.  In your case, prisma should be folding your catagory field into a single sql query, but this won't work for `largestTransactionsIds` as is, I think it only applies to findUnique.  I think if you were to map over the `largestTransactionsIds` and call findUnique something like:

```ts
p.largestTransactionsIds.map(id => db.transaction.findUnique({
  ...query,
  where: {
    userId: ctx.user?.id ?? "",
    id,
  },
}))
```

You'd probably need to log the sql queries prisma is running to see if this actually works as expected, but that would be what I'd try.

The alternative is to use dataloaders, and then just don't use t.prismaField.  This will defer the loading of relations to happen when they are used, and should fall back to the fallback loading of relations which similarly depends on prismasbuilt in dataloader to load missing relations.

**Comment by MarceloPrado** [comment]
> prisma should be folding your catagory field into a single sql query

I wasn't aware of its internal dataloader, but from my inspection, Prisma still hits multiple SQL queries for this GraphQL query:
```
query MyQuery {
  budgetSuggestions {
    category{
      emoji
      name
      
    }
    limitInCents
  }
}
```

Here's its logs:
<img width="580" alt="CleanShot 2023-05-27 at 18 37 44@2x" src="https://github.com/hayes/pothos/assets/8047841/f1fa69b6-be90-41c0-9065-8bc40274bfa5">

Unfortunately Prisma is quite bad in terms of perf optimizations - a tool like Drizzle or `kysely` would resolve it better - at least when it concerns to JOINS. I heard Prisma team is looking at perf though, so there's a high change things will improve.

Anyway, enough with the rambling. Thanks for your inputs. I'll defer this optimization for now, since it's not a perf-sensitive endpoint. And I agree with your point - dataloader and prisma plugins are two different things, with their own optimizations/tradeoffs.

**Comment by hayes** [comment]
Interesting, not sure why Prisma isn't batching those, you can read a bit about their dataloader pattern here: https://www.prisma.io/docs/guides/performance-and-optimization/query-optimization-performance#solving-n1-in-graphql-with-findunique-and-prismas-dataloader

It does work selects/includes, so I don't think the spread of query there should be an issue, but not sure.

**Comment by MarceloPrado** [comment]
Thanks for the pointer. Interestingly, if I replace my `findUniqueOrThrow` with `findUnique`, Prisma batching kicks in. It seems like it only works when `.findUnique` is used.

**Comment by MarceloPrado** [comment]
Just tested your suggestion and it works great. It's tricky and very subtle, but this version now works fine:

```tsx
tenMostExpensiveTransactions: t.prismaField({
  type: ["Transaction"],
  description:
    "The 10 most expensive transactions for this category. It may include the current month",
  resolve: async (query, p) => {
    // By using `.findUnique` instead of `.findMany`, Prisma is able to
    // merge these requests into a single SQL query, avoiding n+1 +
    // exhausting the connection pool.
    const transactions = await Promise.all(
      p.largestTransactionsIds.map((id) =>
        db.transaction.findUnique({ ...query, where: { id } })
      )
    );

    return transactions.filter(isDefinedAndNotNull);
  },
}),
 ```

**Comment by hayes** [comment]
findUniqueOrThrow not working is a bug, there are a number of issues open in the prisma repo.  This is pretty unfortunate as Pothos uses this method internally and it used to batch everything correctly.  I'll either see if this can be fixed quickly upstream, or add a workaround to pothos so it isn't affected by this issue, thanks for figuring that out!

**Comment by MarceloPrado** [comment]
@hayes great work Michael, it seems this will land in the next release! https://github.com/prisma/prisma-engines/pull/4019

**Comment by MarceloPrado** [comment]
upgraded to prisma 5.1.1 and confirmed it's working fine now 🙂
