### ISSUE TITLE
Pass SchemaBuilder instance into a function without loosing plugin type additions.

### ISSUE THREAD

**Issue by bzvestey** [hayes/pothos#929]
I would like to pass my SchemaBuilder instance that I am building up into a function without loosing the type information added to it by the plugins.

Given file `./schema.ts` with the below contents:
```ts
export const schemaBuilder = new SchemaBuilder<{}>({
  // If you are using other plugins, the federation plugin should be listed after
  // plugins like auth that wrap resolvers
  plugins: [
    DirectivePlugin,
    FederationPlugin,
  ],
});
```

I would like to be able to have `schemaBuilder.toSubGraphSchema()` available in a function in `./server.ts` that has schema builder passed in:
```ts
import { SchemaTypes } from "@pothos/core";
import SchemaBuilder from "@pothos/core/dts/builder.js";

export async function startServer<T extends SchemaTypes>(schema: SchemaBuilder<T>) {
  const server = new ApolloServer({
    // This failed, as it doesn't know that `.toSubGraphSchema` function exists on the schema builder object
    schema: schema.toSubGraphSchema({
      linkUrl: "https://specs.apollo.dev/federation/v2.3",
    }),
  });
}
```

Then I would have an `./index.ts` that combines them:
```ts
import { schemaBuilder } from "./schema"
import { startServer } from "./server"

startServer(schemaBuilder);
```

**Comment by hayes** [comment]
Plugin types are sort of a global side-effect of importing the plugin.  If you import the federation plugin in your file that defines the helper, it should see the correct types

**Comment by bzvestey** [comment]
I see, I need to make sure that I am using `PothosSchemaTypes.SchemaBuilder` and as long as I also have `import "@pothos/plugin-federation";` in my imports, then I get the type side effects.

Thank you @hayes!

For others reference in the future, I just updated the `./server.ts` to look like below to make this work:
```ts
import { SchemaTypes } from "@pothos/core";
import "@pothos/plugin-federation";

export async function startServer<T extends SchemaTypes>(schema: PothosSchemaTypes.SchemaBuilder<T>) {
  const server = new ApolloServer({
    schema: schema.toSubGraphSchema({
      linkUrl: "https://specs.apollo.dev/federation/v2.3",
    }),
  });
}
```
