### ISSUE TITLE
[Documentation Request] Don't suggest class syntax first

### ISSUE THREAD

**Issue by Hebilicious** [hayes/pothos#930]
Hello @hayes, I can see Pothos has progressed a lot since the last time I checked it out.
Browsing the documentation, I have a gut feeling that potentials users are being turned off by the fact that the class syntax is documented first, and that the other 2 syntax are not well presented. 

Have you thought of making the Typescript syntax (with objectRef and .implement) the "main" one ? 
Or even the SimpleObject syntax the "main" one (I personally only use this style ...)
By main one I mean use it everywhere in the docs  / readme example, and present the 2 other ones in an alternative syntax section.

It's nice to have options, but there's a large amount of JS developers who are allergic to classes (maybe react hooks transition PTSD 😄)

There's a new code first graphql library that is rising very quickly in popularity, and it might be because their docs are more "catchy" ? I think Pothos is great and well more fledge out, and this change will hopefully boost its popularity.

**Comment by hayes** [comment]
Yes, this is definitely something I would like to do.at some point.  Classes were never really meant to be prominent in the docs.  PRe are more than welcome, but 100% agree that classes are over emphasized in a few places (especially in the relay docs)

**Comment by hayes** [comment]
I updated the objects guide to use objectRef as the default
