### ISSUE TITLE
[Help] Print Federation schemas

### ISSUE THREAD

**Issue by chrisgate** [hayes/pothos#931]
I could not print after trying all the ways stated here https://pothos-graphql.dev/docs/plugins/federation#printing-the-schema

Maybe my skill in pothos is not enough

Please help with possible example

Thanks

**Comment by chrisgate** [comment]
const allSchemas = await loadSchema('src/schemas/*.graphql', { loaders: [new GraphQLFileLoader()] })
  fs.writeFileSync("federation.graphql", printSchemaWithDirectives(allSchemas));
  
with the above I got **Error: Unknown directive "@link".**

Thank you

**Comment by hayes** [comment]
Sorry, I don't have enough context here to know what's going on.

I don't know what `loadSchema` is doing.  This looks maybe unrelated to pothos.  Pothos doesn't really know anything about combining schemas for federation.  Are the schemas in the src/scheams directory the schemas printed from pothos?

**Comment by JipSterk** [comment]
you could use [rover](https://www.apollographql.com/docs/rover/)
if you want to download a subgraph schema you could use the following command:
```rover subgraph introspect http://localhost:2000/graphql > schema.gql``` (change the port number for your subgraph service)

if you want to download the supergraph you could use the following configuration:
```supergraph.yml
federation_version: =2.3.2
subgraphs:
  films:
    routing_url: https://films.example.com
    schema:
      file: ./relative/path/to/subgraph/schema/films.graphql
  people:
    routing_url: https://people.example.com
    schema:
      file: ./relative/path/to/subgraph/schema/people.graphql
```
and run the command: ```rover supergraph compose --config supergraph.yml > ./supergraph.gql```

**Comment by arimgibson** [comment]
@chrisgate are you working with multiple subgraphs and needing to print all of those? I can dig up some code for a setup I had that used a task runner with Pothos to print schemas from multiple subgraphs then use Rover to start federation locally with all the schemas.

Or, are you just using a single graph and need to print that single schema? If so, that should be just a single line of code.

Let me know what matches your usecase best and I can send some code I have written for other projects

**Comment by chrisgate** [comment]
The first case is mine...I have multiple subgraphs a.k services and I want to print them as Federation locally.

Thank you @arimgibson

**Comment by arimgibson** [comment]
Okay, I understand @chrisgate. I'll find the code I used for that and send it along, and can also add a PR to the docs with an example about how to compose a supergraph schema using Pothos, if that'd be welcome @hayes? Don't want to replicate the Apollo Rover docs too much, but can link to their docs for some of it

**Comment by arimgibson** [comment]
@chrisgate the `Unknown Directive` part is probably not an issue with Pothos though... I've run into something fairly similar when I was first doing this. Instead of using the `printSchemaWithDirectives` (which I'm assuming you're importing from `graphql-tools`, use `printSubgraphSchema` from `@apollo/subgraph` as the docs mention. I'm pretty sure that was the fix for me when I ran into that issue

**Comment by chrisgate** [comment]
I have used what u mentioned before..let me explained the scenario 

...on every of my services a.k.a SubGraph I print with printSubgraphSchema to a location on my disk "src/schemas" calling them serviceName.graphql.

next is to load them so I can combine them into one:
  --that was where I was using GraphQLFileLoader to load it so i can combine and it was at that point **I got Error: Unknown directive "https://github.com/link"**
  
  I am curious to see how it is done in any example project anyways
  
  
  Thank you once again

**Comment by arimgibson** [comment]
Ah okay, so the issue is actually with GraphQL File Loader I believe; it probably doesn't support directives. The proper way to load the schemas would be using rover as @JipSterk mentioned. Write a config file that has an entry for each subgraph, and then run the `rover` command they provided. Don't use the loader or anything from fs as rover will handle it all for you

Can do this inside your code by using Node's `exec`

**Comment by chrisgate** [comment]
Thanks @JipSterk I was able to use Rover as suggested and thank @arimgibson your exec suggestion is exactly what I used

as always thanks @hayes for this library.

what do I want to use it for? good question

  I am trying to hack a subscription into Federation thru Websocket

Thanks

**Comment by chrisgate** [comment]
I am having more error-related issues with Federation and Prisma Relay [Project](https://github.com/hayes/pothos/issues/942)
