### ISSUE TITLE
Creating unions with the same backed prisma model

### ISSUE THREAD

**Issue by MarceloPrado** [hayes/pothos#932]
Hi @hayes, how's it going?

I'm having issues figuring out the best way to implement a union type which is backed by the same prisma model. I'm seeing the `PothosSchemaError: Duplicate typename: Another type with name {X} already exists.`. While I fully understand what's causing the error, I couldn't find a example in the docs similar to my usecase.

### Background

Suppose you have an event-based architecture that notifies you via webhooks whenever certain events happen. Each notification indicates a successful or failed event. When it's a failure event, the webhook payload comes with additional metadata, like the error code and the reason (which comes from a 3rd party, and thus, you can't store in your DB cleanly). You could start with simplified `prisma` model:

```prisma
enum WebhookResultStatus {
  SUCCESS,
  FAILED
}

model WebhookResult {
  // other fields omitted for brevity
  status WebhookResultStatus,
  metadata Json?
}
```

Now, you want to expose this model in a friendlier and type-safe way to your API consumers. Let's say you're trying to build the following GraphQL schema:

```graphql
type FailedWebhookResultMetadata {
  code: String!
  message: String
}

type FailedWebhookResult implements Node {
  id: ID!
  status: "FAILED"
  errorMetadata: FailedWebhookResultMetadata
}

type SuccessfullWebhookResult implements Node {
  id: ID!
  status: "SUCCESS"
}

type WebhookResult = FailedWebhookResult | SuccessfullWebhookResult

```

This is what I'm trying to do using the prisma and relay plugin.

### Question

I'm trying to create the example above with something similar to:
```ts
const FailedWebhookResultMetadata = builder.simpleObject(
  "FailedWebhookResultMetadata",
  {
    fields: (t) => ({
      code: t.string({ nullable: false }),
      message: t.string({ nullable: true }),
    }),
  }
);

const FailedWebhookResult = builder.prismaNode("WebhookResult", {
  id: { field: "id" },
  fields: (t) => ({
    status: t.field({
      type: WebhookResultStatus,
      resolve: (parent) => parent.status,
    }),
    errorMetadata: t.field({
      type: FailedWebhookResultMetadata,
      nullable: true,
      resolve: (parent) => parseErrorMetadata(parent.metadata),
    }),
  }),
});

const SuccessfullWebhookResult = builder.prismaNode("WebhookResult", {
  id: { field: "id" },
  fields: (t) => ({
    status: t.field({
      type: WebhookResultStatus,
      resolve: (parent) => parent.status,
    }),
  }),
});

export const WebhookResultNode = builder.unionType("WebhookResult", {
  types: [FailedWebhookResult, SuccessfullWebhookResult],
  resolveType: (parent) =>
    parent.status === WebhookResultStatus.FAILED
      ? FailedWebhookResult
      : SuccessfullWebhookResult,
});

```

As you can see, the type I really care about is `WebhookResultNode`. This is what gets added to my resolvers using `t.field` (also, nit: it's a bummer I can't use t.prismaField here due to the union type).

Once I try running this code, I see the `PothosSchemaError: Duplicate typename: Another type with name WebhookResult already exists.` error. I'm not sure what's the best path forward here - while I could create simpleObjects for each union type, it doesn't feel like the right direction - I don't want to rebuild the `prismaNode` behavior

Would appreciate your insights!
Thanks

**Comment by hayes** [comment]
You probably want to use the typeVariant API: https://pothos-graphql.dev/docs/plugins/prisma#type-variants

**Comment by MarceloPrado** [comment]
Completely missed that section 😣. Thanks, seems exactly what I need
