### ISSUE TITLE
[HELP] prisma-relay and Federation: Non-shareable field errors

### ISSUE THREAD

**Issue by chrisgate** [hayes/pothos#942]
I am using @JipSterk  example project to navigate my way in using those technologies

**Project**  [[pothos-federation-prisma-relay](https://github.com/JipSterk/pothos-federation-prisma-relay)](https://github.com/JipSterk/pothos-federation-prisma-relay)
I have below errors whenever I added more than one **prismaConnection** in diff service

**accounts-service**
builder.queryField("users", (t) =>
  t.prismaConnection({
    type: "User",
    cursor: "id",
    resolve: (query) =>
      db.user.findMany({ ...query, orderBy: { createdAt: "desc" } }),
  })
);

**comments-service**
builder.queryField("comments", (t) =>
  t.prismaConnection({
    type: "Comment",
    cursor: "id",
    resolve: (query) =>
      db.comment.findMany({ ...query, orderBy: { createdAt: "desc" } }),
  })
);

**@acme/gateway:codegen:supergraph:     UNKNOWN: Non-shareable field "PageInfo.hasNextPage" is resolved from multiple subgraphs: it is resolved from subgraphs "accounts-service" and "comments-service" and defined as non-shareable in all of them
@acme/gateway:codegen:supergraph:     UNKNOWN: Non-shareable field "PageInfo.hasPreviousPage" is resolved from multiple subgraphs: it is resolved from subgraphs "accounts-service" and "comments-service" and defined as non-shareable in all of them
@acme/gateway:codegen:supergraph:     UNKNOWN: Non-shareable field "PageInfo.startCursor" is resolved from multiple subgraphs: it is resolved from subgraphs "accounts-service" and "comments-service" and defined as non-shareable in all of them
@acme/gateway:codegen:supergraph:     UNKNOWN: Non-shareable field "PageInfo.endCursor" is resolved from multiple subgraphs: it is resolved from subgraphs "accounts-service" and "comments-service" and defined as non-shareable in all of them**

... I have had those  UNKNOWN: Non-shareable fields errors in my real project but I decided to clone @JipSterk project to see what I missed

I am hoping @hayes can help with the missing piece.

Thanks

**Comment by chrisgate** [comment]
[From Apollo Website](https://www.apollographql.com/docs/technotes/TN0029-relay-style-connections/#can-i-use-relay-style-connections-with-apollo-federation)

how can I achieve below with our lovely Pothos
`type PageInfo @shareable {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}`

**Comment by hayes** [comment]
The federation plugin adds a `shareable` option you can add to the options for a type.

To add option like shareable to types that the relay plugin generates automatically, you can specify them via options passed to the builder:

```ts
export const builder = new SchemaBuilder<{...}>({
  plugins: [DirectivesPlugin, FederationPlugin, RelayPlugin],
  relayOptions: {
    clientMutationId: 'omit',
    cursorType: 'String',
    pageInfoTypeOptions: {
      shareable: true,
    },
  },
});
```

**Comment by chrisgate** [comment]
@hayes You are a true GENIUS.

Thank you it works
