### ISSUE TITLE
TypeError: _builder__WEBPACK_IMPORTED_MODULE_1__.builder.prismaObject is not a function

### ISSUE THREAD

**Issue by chitter99** [hayes/pothos#955]
# Describe the Bug
We have encoutered a old issue again on the latest verison. As described on this [issue](https://github.com/hayes/pothos/issues/725), pothos fails under next.js in a pnpm monorepo. 
```
../packages/graphql/src/schema.ts (5:8) @ prismaObject

  3 | import { builder } from "./builder";
  4 | 
> 5 | builder.prismaObject("User", {
    |      ^
  6 | fields: (t) => ({
  7 |   id: t.exposeID("id"),
  8 | }),
```

# Link to the code that reproduces this issue
https://github.com/chitter99/strange-pothos-issue-with-pnpm-monorepo-and-next-js
https://codesandbox.io/p/github/chitter99/strange-pothos-issue-with-pnpm-monorepo-and-next-js

# To Reproduce
clone project
install
```
pnpm install
pnpm --filter @packages/database generate
pnpm --filter @apps/app dev
```
got to http://localhost:3000/api/graphql

# Expected Behavior
show graphql-yoga playground on http://localhost:3000/api/graphql

**Comment by hayes** [comment]
I spent some time trying to track down whats going on here, but as far as I can tell, everything is set up correcly on the Pothos side.  There may be something weird going on with the way webpack/next.js evaulates imports.

Here is what I found:

The issue becomes more obvious if you add the following to your next.config.mjs:

```js
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@packages/graphql", "@packages/database"],
  webpack: (config, { isServer }) => {
    if (isServer) {

      return {
        ...config,
        externals: [
          ...config.externals,
          {
            '@pothos/core': '@pothos/core',
            '@pothos/plugin-prisma': '@pothos/plugin-prisma',
          }
        ]
      }
    }

    return config;
  }
};
```

If you run `pnpm build` and look into `.next/server/pages/api/graphq.js` you will see something like:

```js
/***/ 9869:
/***/ ((module) => {

module.exports = require("@pothos/core");

/***/ }),

/***/ 7873:
/***/ ((module) => {

module.exports = import("@pothos/plugin-prisma");;
```

What stands out about this is that `@pothos/core` is loaded with `require` while `@pothos/plugin-prisma` is loaded with `import`.  I can't find any reason why it would do this, but it's definitely the issue.  I've tried a lot of iterations of how exports are defined in package.json, and I can't find anything that makes this work correctly.   I'd open an issue with next instead

**Comment by chitter99** [comment]
Thank you for your quick help! With your research I was able to solve the issue. I forced webpack to use the commonjs externals format. Also note that I moved up the custom externals so that it overrides next.js's default behavior.
```typescript
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@packages/graphql", "@packages/database"],
  webpack: (config, { isServer }) => {
    if (isServer) {
      return {
        ...config,
        externals: [
          {
            "@pothos/core": "@pothos/core",
            "@pothos/plugin-prisma": "commonjs @pothos/plugin-prisma",
          },
          ...config.externals,
        ],
      };
    }

    return config;
  },
};
```

After that I stumbled upon another issue. 
```
Error: Cannot use GraphQLSchema "{ __validationErrors: undefined, description: undefined, extensions: {}, astNode: undefined, extensionASTNodes: [], _queryType: Query, _mutationType: undefined, _subscriptionType: undefined, _directives: [@deprecated, @include, @skip, @specifiedBy], _typeMap: { Boolean: Boolean, Float: Float, ID: ID, Int: Int, Query: Query, String: String, User: User, __Directive: __Directive, __DirectiveLocation: __DirectiveLocation, __EnumValue: __EnumValue, __Field: __Field, __InputValue: __InputValue, __Schema: __Schema, __Type: __Type, __TypeKind: __TypeKind }, _subTypeMap: {}, _implementationsMap: {} }" from another module or realm.
```

I fixed that by using a module override in the `package.json` of the next.js app and adding `graphql` as dependency there.
```json
...
  "pnpm": {
    "overrides": {
      "graphql": "$graphql"
    }
  }
...
  "dependencies": {
...
    "graphql": "16.7.1"
...
}
```

See the changes made to the repository for [more detail](https://github.com/chitter99/strange-pothos-issue-with-pnpm-monorepo-and-next-js/commit/2cbaa6414bd157d3f4c792e9ca904d622a55c856).

**Comment by hayes** [comment]
Nice, glad you got it figured out!
