### ISSUE TITLE
[@pothos/plugin-scope-auth] option to change default from any to all

### ISSUE THREAD

**Issue by homoky** [hayes/pothos#958]
In resolvers we need at the moment to provide `$all`, but we want `$all` between all authscopes everywhere. Based on docs there is no option to set default or any other setting on authscope plugin.

**Comment by hayes** [comment]
definitely something that I had intended to add, the biggest issue is how to name the option

**Comment by hayes** [comment]
just published a new version with a new `defaultStrategy` option that can be set to `all`
