### ISSUE TITLE
[Prisma Plugin] nullable fields are not suggested in the expose methods and display error in VSCode

### ISSUE THREAD

**Issue by kloon15** [hayes/pothos#960]
Hi,
Im just learning GraphQL and everything around it and wondering if i missed smth, but nullable fields show up as an error in VSCode. If i remove the null property then they are showing up correctly.

![image](https://github.com/hayes/pothos/assets/1431170/a66588d6-2d81-4937-bdb0-e72b01734f6f)

**Comment by kloon15** [comment]
I found the solution in a youtube comment buried under a video, i have to add `{ nullable: true }`.

**Comment by hayes** [comment]
This was something that was fixed for the core expose methods a while back, I just ported the fix to the prisma plugin as well.  It will now correclty auto-complete nullable fields, but show an error for the options object if making the field nullable is required
