### ISSUE TITLE
ReplayOptions require all default options when using `{strict: false}`

### ISSUE THREAD

**Issue by meotimdihia** [hayes/pothos#962]
ReplayOptions require all options when using `{strict: false}`

We can reproduce the problem by clone this demo project: https://github.com/prisma/awesome-links/tree/main and change  `strict: false`

![image](https://github.com/hayes/pothos/assets/300961/3c6ab85c-aa32-43f5-8fc8-ea1a0d9e6d2e)
`
Type '{}' is missing the following properties from type '{ idFieldName: string; idFieldOptions?: Partial<Omit<ObjectFieldOptions<ExtendDefaultTypes<{ PrismaTypes: PrismaTypes; Context: Promise<{ user?: undefined; accessToken?: undefined; } | { user: Claims; accessToken: string; }>; }>, ... 4 more ..., PageInfoShape>, "args" | ... 2 more ... | "nullable">>; ... 29 more ......': idFieldName, clientMutationId, cursorType, brandLoadedObjects, and 2 more.
`

**Comment by hayes** [comment]
as noted there are likely to be other issues when not using strict mode, but I just published a fix for this specific issue
