### ISSUE TITLE
Typescript error for scalar inputs after updating to v3.32

### ISSUE THREAD

**Issue by garth** [hayes/pothos#969]
Given the following scaler:

```ts
import { JSONResolver } from 'graphql-scalars'

builder.addScalarType('RichText', JSONResolver, {})
```

After updating to v3.32 I get the following typescript error:

```ts
builder
  .inputRef<{
    id: string | number
    description: any
  }>('Input')
  .implement({
    fields: (t) => ({
      id: t.id({ required: true }),
      description: t.field({ type: 'RichText' }), // ts error: Type instantiation is excessively deep and possibly infinite.
    }),
  })
```

Here are the before/after pothos versions:

```diff
-    "@pothos/core": "^3.30.0",
+    "@pothos/core": "^3.32.0",
     "@pothos/plugin-errors": "^3.11.1",
-    "@pothos/plugin-prisma": "^3.52.0",
-    "@pothos/plugin-scope-auth": "^3.19.2",
+    "@pothos/plugin-prisma": "^3.53.0",
+    "@pothos/plugin-scope-auth": "^3.20.0",
```

Reverting the pothos dependences fixes the issue.

**Comment by hayes** [comment]
Can you share what the type of RichText is?

**Comment by garth** [comment]
Sorry, I missed that part:

```ts
export type Scalars = {
  RichText: {
    Output: any
    Input: any
  }
}
```

**Comment by hayes** [comment]
I have not been able to reproduce this error, I suspect there might be some discrepancy in typescript version of tsconfig settings that's causing this to behave differently for me, but looking through the types, I have an idea of how to improve things a bit that may also fix this issue.    

Just published a new version, can you upgrade and let me know if that resolves the issue for you?

**Comment by garth** [comment]
The new version works great. The error is gone.

Thanks for your support!
