### ISSUE TITLE
Apollo Federation support

### ISSUE THREAD

**Issue by applicazza** [hayes/pothos#97]
Hello, 

Firstly, huge thanks for such an amazing library.

Secondly, what would be the recommended way to add Apollo Federation support to the library?

**Comment by hayes** [comment]
Good question! 

I haven't used apollo federation myself, so I don't have an easy answer.  It is definitely something that I should add a plugin for, and skimming over the specs, I have some ideas about how it would be implemented, but it is definitely not trivial and will take a decent amount of API design and careful consideration on how the types would work.  There are some concepts that don't fit nicely into GiraphQLs existing type system that might make it complicated to get everything to be fully type-safe.

In the shorter term, i would imagine there must be a way to get it working without a plugin, but I would have to dig more into the available APIs for Apollo's federation package.  I'll keep thinking about this, but don't have a specific timeline on when I can get the plugin implemented, or look into the easier ways to integrate things without a plugin.

**Comment by hayes** [comment]
Started thinking though some of the details of this.  Here is a rough idea of the API I have in mind.  To implement the following schema:

```graphql
type Review @key(fields: "id") {
  id: ID!
  body: String
  author: User @provides(fields: "username")
  product: Product
}

extend type User @key(fields: "email") {
  username: String! @external
  email: String! @external
  emailDomain: String! @requires(fields: "email")
}

extend type Product @key(fields: "upc") {
  upc: String! @external
}
```

you would write something like:

```ts
const Product = builder.externalEntity('Product', {
  key: ['upc'],
  externalFields: (t) => ({
    upc: t.string(),
  }),
});

const User = builder.externalEntity('User', {
  key: ['email'],
  externalFields: (t) => ({
    email: t.string(),
    username: t.string(),
  }),
  fields: (t) => ({
    requires: ['email'],
    emailDomain: ({ email}) => email.split('@')[1],
  }),
});

builder.entityObject(Review, {
  name: 'Review',
  key: ['id'], // This part I don't know how to make type-safe.
  // arg here needs to be based on key above, so I also don't know how to make it type-safe
  resolveReference: ({ id }) => Review.loadById(id),
  fields: (t) => ({
    id: t.exposeId('id'),
    body: t.exposeString('body', { nullable: true }),
    author: t.field({
      type: User,
      provides: ['username'],
      resolve: review => {
        return {
          __typename: 'Review',
          id: review.authorId,
          username: review.author.email.split('@')[0]
        }
      },
    }),
    product: t.field({
      type: Product,
      resolve: review => {
        return { __typename: 'Product', id: review.productId }
      },
    }),
  }),
})
```

Field selections for `@requires`, `@provides`, and @key on external objects are all required to be based on external fields.  This means we can use inference based on the externalFields return type to ensure that the field selections for those fields make sense.  The biggest issue is that the `@keys` for entities owned by a service don't have the same restriction.  This means that the keys can reference fields defined outside the object definition (either through nested fields, or methods like `builder.objectField(...)`.  This makes it impossible to infer the correct types for the keys on an entity, and by extension we can't correctly type the resolveReference method since we don't know they types for the keys that are going to be passed in.

There are a few things I can do to get it working for most use-cases, but it would not be reliable.  This might be okay, since I think I could type basic fields like ids directly on the entity correctly, and then fall back to unknown for fields that can't be directly inferred.

**Comment by hayes** [comment]
Just a quick update.  I am still working on this, but I don't have a lot of time right now.  There are a few type issues that are proving difficult to find a good solution for.  It will probably be at least a couple more weeks before I have time to put together anything that is actually usable.

**Comment by hayes** [comment]
Sorry I haven't gotten around to releasing anything for this yet.  Ran into some more complicated type issues that kinda halted progress on this until I have time to think more through how types will work in GiraphQL 3.0  There are some other higher priority changes I am working on that do not require a major refactor of the core library.  I probably won't be releasing anything for federation in the near future.  It's still on my radar of things I want to support, but looking at the amount of effort required, breaking changes, and level of demand, it is currently lower on my list of priorities.

If you are seeing this issue, and this is a feature you need, let me know.  If this becomes a more popular request, it is something I might be able to re-prioritize in the future.

**Comment by hayes** [comment]
With federation 2 coming out soon, I've started working on this again.  No guarantees or timelines on further progress, but I've started laying the groundwork for a plugin here: https://github.com/hayes/giraphql/pull/212.

The current API is a little more manual and not quite as type-safe as I would like, but should be better than nothing.  Still lots to do.  I've got most of the logic for defining schemas in place, now I need to figure out the best options for making it executable.

**Comment by hayes** [comment]
Probably won't be merging until federation comes out of alpha, but I did create a snapshot release with a mostly working plugin.

Current limitations:
- no `@provides` directive
- only works with graphql@15
- no documentation other than the example app
- no tests
- resolveReference only has types for the first argument

Other than that, it seems to be functional.

**Comment by jjm340** [comment]
Just a +1 to this feature request - I'd love to use this library, but federation is a must-have for us so waiting for this feature. Thanks for building this lib in the first place.

**Comment by hayes** [comment]
apollo gateway just released an updated version to support graphql@16 which was one of the main blockers for getting this plugin released, I'll try to find some time later this week to update the plugin, and see if things are stable enough to release to create an initial release of the plugin

**Comment by hayes** [comment]
Renaming to Pothos took more time than expected, but this is at the top of my priorities again, I'll be working on this plugin today

**Comment by hayes** [comment]
🎉 Finally got everything working well enough to get an initial release of the federation plugin!

https://www.pothos-graphql.dev/docs/plugins/federation
