### ISSUE TITLE
Multiple orderBy

### ISSUE THREAD

**Issue by fkozlicki** [hayes/pothos#970]
Selecting multiple sort options doesn't work.

![image](https://github.com/hayes/pothos/assets/93607858/3ad4df4e-f155-44d5-bff4-6f6b7fe8a156)

It is transformed into 

![image](https://github.com/hayes/pothos/assets/93607858/5e048757-e615-4b6a-95dd-09f4391afac9)

instead should be 

![image](https://github.com/hayes/pothos/assets/93607858/cd65bc75-a111-4313-85cf-4e748fe53384)

(prisma allows multiple sort options)

**Comment by hayes** [comment]
any context on what this is for, is this the prisma-utils plugin?

**Comment by fkozlicki** [comment]
yes, look this is what i am trying to do
`builder.prismaObject('Post', {
	fields: (t) => ({
		id: t.exposeID('id'),
		title: t.exposeString('title'),
		content: t.exposeString('content'),
		createdAt: t.expose('createdAt', {
			type: 'Date',
		}),
		votes: t.relation('votes', {}),
		author: t.relation('author'),
		comments: t.relation('comments'),
	}),
});

const PostSort = builder.prismaOrderBy('Post', {
	fields: {
		createdAt: true,
		title: true,
	},
});

builder.queryField('posts', (t) =>
	t.prismaField({
		type: ['Post'],
		args: {
			offset: t.arg.int({
				defaultValue: 0,
				required: true,
			}),
			limit: t.arg.int({
				defaultValue: 5,
				required: true,
			}),
			filter: t.arg({
				type: PostFilter,
			}),
			sort: t.arg({
				type: PostSort,
			}),
		},
		resolve: async (query, _parent, args, ctx) => {
			const { offset, limit, filter, sort } = args;

			console.log('SORT', sort);

			const posts = await ctx.prisma.post.findMany({
				...query,
				skip: offset,
				take: limit,
				where: filter ?? undefined,
				orderBy: sort ?? undefined,
			});

			return posts;
		},
	})
);
`
i have logged sort as you can see and it look like this

`{ createdAt: 'asc', title: 'desc' }`

but definetly should be this

`[{ createdAt: 'asc' }, { title: 'desc' }]`

**Comment by hayes** [comment]
sorting is order dependent, so we can't just take the multiple selections and flatten them into a list.  If you want to support multiple sorts, you should do it like: `t.arg({ type: [PostSort] }) }` and accept a list of sort objects (this matches what prisma does).

The sort type will eventually be updated to use `@oneOf` once that feature is properly supported by graphql-js

**Comment by ccfiel** [comment]
@fkozlicki https://github.com/hayes/pothos/issues/1016

**Comment by hayes** [comment]
going to leave this open until proper `@oneOf` support lands
