### ISSUE TITLE
Not required and not nullable arguments

### ISSUE THREAD

**Issue by avele** [hayes/pothos#975]
I couldn't find a solution on how to make an argument both optional and non-nullable at the same time. For example:

```ts
builder.mutationField('updateSomething', (t) =>
	t.prismaField({
		type: SomeType,
		args: {
			name: t.arg.string(),
        }),
...
```

The code above infers the type of "name" as `string | null | undefined`, which is not assignable to my Prisma model, since it can only be a string (or undefined at it's just not updated in this case). At the same time, I don't want to force the GraphQL client to always pass "name" if they need to update some other fields, for example.

Whats the best way with Pothos to achieve non nullable and non required argument type at the same time?

**Comment by hayes** [comment]
There are a few options.  The types here are intended to accurately reflect what GraphQL allows.  Basically GraphQL doesn't differentiate nullable and optional, and allows clients to send both null or undefined, and doesn't have any built in normalization. 

* This can be addressed in your resolver as described here: https://github.com/hayes/pothos/discussions/889
* Normalization can be enforeced by a plugin (this is what the prisma-utils plugin does) A future validation plugin might also support something like this
* you can make a field non-nullable and provide a default value (this is a little different than what you are looking for though)

I generally just do something like `where { field: field.args.thing ?? undefined }` in my resolver

**Comment by avele** [comment]
I recently discovered pothos' validation plugin with Zod schemas. Now, I'm curious if there's a way to enforce stricter types for args at least once they are in the resolver function. Since validation runs before the resolver's execution, I believe the args types should be narrowed down to match the zod schema by this point. However, in my tests, it doesn't seem to work this way. The types aren't narrowed in the resolver, whether I use inline validation for an argument or field validation with a `z.object` schema. @hayes, could you please comment on this?

**Comment by avele** [comment]
I recently discovered the Pothos validation plugin with Zod schemas. Now, I'm curious if there's a way to enforce stricter types for args in the resolver function. Since validation runs before the resolver's execution, I believe the args types should be narrowed down to match the Zod schemas by this point. However, in my tests, it doesn't seem to work this way. The types aren't narrowed in the resolver, whether I use inline validation for an argument or field validation with a z.object schema that describes every arg. @hayes, could you please comment on this?

**Comment by hayes** [comment]
the validation plugin doesn't do any type narrowing based on schema.  Pothos 4.0 has some big changes that will allow plugins to better build APIs that can perform type narrowing, and may include a redesigned validation plugin, but this isn't really possible in Pothos today
