### ISSUE TITLE
Does @pothos/plugin-prisma@3.53.0 includes a breaking change ?

### ISSUE THREAD

**Issue by Florian-Guillot-Axa** [hayes/pothos#982]
Before (3.52.0) `t.exposeID('id')`

Typescript says that expose (ID, string, etc..) methods NEEDs a second parameter, even empty.
After (3.56.0) `t.exposeID('id', {})`

Was it planned, or is it just a misconfiguration on my side ?

**Comment by hayes** [comment]
This is not intentional, I'll try to figure out what's going on with that

**Comment by hayes** [comment]
should be fixed now
