### ISSUE TITLE
Global auth scopes

### ISSUE THREAD

**Issue by avele** [hayes/pothos#985]
For certain use cases, having default or global authentication scope options would be beneficial, allowing a specific scope to be applied to every request. As it stands, if I want to enforce scope verification for nearly all queries and mutations, I have to individually specify the scope option for each request, with only a few exceptions.

**Comment by hayes** [comment]
This should be easy to set up, You can define type level scopes on the Query and Mutation types.  For fields where you want to disable these checks, you can add the `skipTypeScopes` option

```ts
builder.mutationType({
  authScopes: {
    loggedIn: true,
  },
  fields: (t) => ({
    logIn t.field({
      // don't need to be logged in to use the logIn mutation
      skipTypeScopes: true,
      type: AuthResult,
      args: {...},
      resolve: () => {...},
    }),
    // other mutations require the loggedIn scope
  })
});
```

**Comment by avele** [comment]
Oh, thank you so much, that's exactly what I needed. In my current case, skipping all type scopes works well. However, I'm curious - is it possible to skip specific type scopes rather than all of them?

**Comment by hayes** [comment]
No not currently, You'd need to re-add the scopes you want to preserve I think, but I'd be open to a PR that adds that as a feature

**Comment by avele** [comment]
I think more versatile approach would be ability to override type scopes values in fields. I just checked and if same scope is set in both type and field it takes value of type's one.

**Comment by hayes** [comment]
this won't currently work.

simple example:
```ts
builder.objectType('User', {
  authScopes: (user) => {
     readUser: user.id,
  },
  fields: (t) => ({
    bestFriend: t.field({
       type: 'User',
       authScopes: (user) => ({
         readUser: user.bestFriendId
       }),
       resolve: () => ...
     })
  })
})
```
