### ISSUE TITLE
Typescript help (conditional context properties based on what shield rules are used on)

### ISSUE THREAD

**Issue by giva9712** [hayes/pothos#991]
Hi,
I have the createContext function which decodes JWT from the request header and adds token payload as a user property but the user property of context is optional because anonymous users call some queries.

Can change the type of resolver context based on used shield rules on it?

For example, is it possible to make the user property type not optional based on what shield rules are used on the query or mutation?

![image](https://github.com/hayes/pothos/assets/40331144/b78ace34-520d-4c16-aedb-1341f2849ebf)

**Comment by giva9712** [comment]
FYI, I am using the below shield plugin implementation.
https://github.com/hayes/pothos/tree/main/examples/graphql-shield

**Comment by hayes** [comment]
Not really.  You could look into the `withAuth` helper that the scope-auth plugin implements to solve this problem, but this is not trivial to set up and get working correctly.

**Comment by giva9712** [comment]
Thanks for your response!
I have used both `withAuth` of scope-auth to check auth and used `shield` to verify authorization.
