### ISSUE TITLE
GraphQL aliased subqueries with different parameters return identical results

### ISSUE THREAD

**Issue by juliobetta** [hayes/pothos#995]
## Description:
When I execute a query with aliased subqueries that have different parameters, the results returned are identical. This behavior is unexpected, as the subqueries should return distinct values based on the provided parameters.

## Implementation

```ts
const AccountValuesFilter = builder.prismaWhere("Value", {
  fields: (t) => ({
    date: builder.prismaFilter("Date", {
      ops: ["gte", "lte", "equals"],
    });
  })
});

export const Account = builder.prismaNode("Account", {
  name: "Property",
  id: { field: "id" },
  values: t.relatedConnection("values", {
    cursor: "id",
    totalCount: true,
    defaultSize: 10000,
    args: {
      date: t.arg({ type: AccountValuesFilter }),
    },
    query: (args) => {
      console.log("-> args", args);
      return {
        where: args.filter ?? {}
      };
    },
  })
});
```

The query looks like the following:

```graphql
{
  account(id: "1") {
    currentValues: values(filter: { date: { equals: { "2022-01-01" } } }) {
      edges { 
        node { 
          date
          value 
        } 
      }
    }
    previousValues: values(filter: { date: { equals: "2021-01-01" } } }) {
      edges { 
        node { 
          date 
          value 
        } 
      }
    }
  }
}
```

Here's the results: 

```json
{
  "data": {
    "account": {
      "currentValues": {
        "edges": [
          {
            "node": {
              "date": "2021-07-01",
              "value": 68551864.7
            }
          }
        ]
      },
      "previousValues": {
        "edges": [
          {
            "node": {
              "date": "2021-07-01",
              "value": 68551864.7
            }
          }
        ]
      }
    }
  }
}
```

Notice that both `currentValues` and `previousValues` have the same `date` value, even though I'm filtering by different dates. I logged the `args` value and it seems that the issues happens after `query()`.

```
-> args {
  date: 2022-07-01T00:00:00.000Z
}
-> args {
  date: 2021-07-01T00:00:00.000Z
}
```

## Expected Behavior:
The aliased subqueries with different parameters should return distinct results based on the provided parameters.

## Actual Behavior:
The aliased subqueries with different parameters return identical results, suggesting that the library might be reusing the parameters from the first subquery.

## Library Version:
Pothos Core 3.33.0

```
"@pothos/core": "3.33.0",
"@pothos/plugin-add-graphql": "3.1.1",
"@pothos/plugin-errors": "3.11.1",
"@pothos/plugin-prisma": "3.57.0",
"@pothos/plugin-prisma-utils": "0.11.0",
"@pothos/plugin-relay": "3.43.1",
"@pothos/plugin-simple-objects": "3.7.0",
"@pothos/plugin-tracing": "0.5.8",
"@pothos/plugin-validation": "3.10.0",
"@prisma/client": "5.2.0"
"prisma": "5.2.0"
```

## Additional Information:

This issue happens not only with `relatedConnection`, but also with `field` with `select` and `args` attributes defined.

```tsx
// ...
score: t.float({
  nullable: true,
  args: t.arg({ type: "Date" }),
  select: args => {
    scores: {
      select: {
        value: true,
      },
      where: { date: args.date },
      take: 1,
    },
  },
  resolve: ({ ids }) => ids?.[0].value ?? null
}),
```

**Comment by juliobetta** [comment]
I just noticed that it works it the args isn't deeply nested. for instance, if I introduce another arg like `orderBy` and pass in a different value, the query works as expected.

```gql
{
  account(id: "1") {
    currentValues: values(orderBy: { date: Asc }, filter: { date: { equals: { "2022-01-01" } } }) {
      edges { 
        node { 
          date
          value 
        } 
      }
    }
    previousValues: values(orderBy: { date: Desc }, filter: { date: { equals: "2021-01-01" } } }) {
      edges { 
        node { 
          date 
          value 
        } 
      }
    }
  }
}
```

So my guess is that it does a shallow comparison. make sense?

**Comment by hayes** [comment]
hey, thanks for the report.  Unfortunately I haven't been able to reproduce the issue.

I created a repo with a minimal reproduction based on your description, but it doesn't cause the same issue, any chance you could see if you can modify the example to more accurately reproduce the issue you are running into? 

Here is my attempted reproduction: https://github.com/hayes/pothos-prisma-alias-bug

**Comment by juliobetta** [comment]
Awesome, thanks! I've just created [a PR](https://github.com/hayes/pothos-prisma-alias-bug/pull/1) there!

**Comment by hayes** [comment]
should be fixed now! Definitely an interesting bug, thanks for helping to track this down
